open-policy-agent/regal

pkg/linter/linter.go
This fails sometimes when the waiting goroutine completes before the linting tasks. In such cases an empty result is returned.
=> Wait for linting tasks to start before waiting

README.md, docs/development.md, pkg/rules/fmt.go
Hey Team! 👋 
The project looks awesome and I can't wait to use it on some projects I have ideas for.
While reading the `README` and going through all the URLs I noticed the `opa-fmt` one was missing a `/` and would give you a `404`.
A bit of a silly `pr` I know in terms of scope but just thought I'd send a quick fix 😅
=> Update to the opa-fmt url as it was returning 404s from the README

.goreleaser.yaml
This is to address this error:
```
failed to publish artifacts: publish: repository can only contain the
characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: StyraInc/regal
```
See run https://github.com/StyraInc/regal/actions/runs/5254120685/jobs/9492333809
=> Use lowercase chars in registry name

bundle/regal/ast.rego, bundle/regal/ast_test.rego
Fix ast.function_decls so that identically named functions won't result in eval_conflict_error as the map is created
Fixes #168
=> Don't crash on identically named functions

bundle/regal/rules/bugs/constant_condition_test.rego, bundle/regal/rules/bugs/not_equals_in_loop_test.rego, bundle/regal/rules/bugs/rule_named_if_test.rego, bundle/regal/rules/bugs/rule_shadows_builtin_test.rego, bundle/regal/rules/bugs/top_level_iteration_test.rego, bundle/regal/rules/bugs/unused_return_value_test.rego, bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom_has_key_construct_test.rego, bundle/regal/rules/idiomatic/custom_in_construct.rego, bundle/regal/rules/idiomatic/custom_in_construct_test.rego, bundle/regal/rules/imports/avoid_importing_input_test.rego, bundle/regal/rules/imports/implicit_future_keywords_test.rego, bundle/regal/rules/imports/import_shadows_import_test.rego, bundle/regal/rules/imports/redundant_alias_test.rego, bundle/regal/rules/imports/redundant_data_import_test.rego, bundle/regal/rules/style/avoid_get_and_list_prefix_test.rego, bundle/regal/rules/style/external_reference_test.rego, bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/line_length_test.rego, bundle/regal/rules/style/prefer_snake_case_test.rego, bundle/regal/rules/style/todo_comment.rego, bundle/regal/rules/style/todo_comment_test.rego, bundle/regal/rules/style/unconditional_assignment.rego, bundle/regal/rules/style/unconditional_assignment_test.rego, bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/style/use_assignment_operator_test.rego, bundle/regal/rules/style/use_in_operator_test.rego, bundle/regal/rules/testing/todo_test.rego
We really need this as a linter rule, but using the strict mode compiler from OPA is not straightforward at the moment, so this had to be done manually. Looking for a proper fix later.
=> Remove unused imports

bundle/regal/ast.rego, bundle/regal/rules/testing/test_outside_test_package_test.rego
=> test-outside-test-package: functions prefixed test_ aren't tests

README.md, bundle/regal/ast.rego, bundle/regal/ast_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/invalid_metadata_attribute.rego, bundle/regal/rules/bugs/invalid_metadata_attribute_test.rego, bundle/regal/rules/style/no_whitespace_comment.rego, bundle/regal/rules/style/no_whitespace_comment_test.rego, docs/rules/bugs/invalid-metadata-attribute.md, docs/rules/style/no-whitespace-comment.md
- Add `no-whitespace-comment` rule in the `style` category, because comments should start with a whitespace!
- Add `invalid-metadata-attribute` rule in the `bugs` category. This one checks that all attributes of a metadata block are valid, i.e. not custom outside of the custom map.
=> Comment and metadata rules

.gitignore, bundle/regal/rules/idiomatic/custom_in_construct.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/line_length.rego, e2e/cli_test.go, e2e/testdata/violations/most_violations.rego, e2e/testdata/violations/rule_named_if.rego, internal/io/io.go
Which exposed flaws in a few rules:
- custom-in-construct would not work with multiple wildcards
- function-arg-return wrong input format for fetching config
- line-length wrong input format for fetching config
While we by no means are done with e2e tests, I think it's OK to say we now at least *have* e2e tests, and much of course thanks to @srenatus previous work on this.
Resolves #53
=> Add e2e test of all rules

cmd/test.go, e2e/cli_test.go, e2e/testdata/custom_rules/custom.rego
Also add e2e test to validate that the bundle is added correctly.
Fixes #196
=> Add Regal bundle to test cmd runner

bundle/regal/regal.rego, cmd/lint.go, cmd/test.go, docs/custom-rules.md, e2e/cli_test.go, e2e/testdata/ast_type_failure/custom_type_fail.rego, internal/compile/compile.go, internal/embeds/embeds.go, internal/io/io.go, internal/test/rego_test.go, main.go, schemas/regal-ast.json
Currently enabled for the `regal test` command, which is the most likely entrypoint for rule authors, whether for built-in Regal rules or custom ones.
While it would be useful to provide this also for `regal lint` — we'll probably want to do this together with the strictness rules, as we currently don't require compilation, and it's not clear that we'll want to unless a rule is configured that needs this, like most of the strictness rules would.
Additionally, the schema is provided when running the Rego tests via `go test ./...`, which should help catch errors we make ourselves.
It would be nice if custom rule authors didn't have to include the schema in the metadata annotation, but I've yet to figure out the best way of doing that, as we can't bundle a custom policy and also have them …
=> Enhanced type checking using Regal AST schema

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/use_in_operator.rego, bundle/regal/rules/idiomatic/use_in_operator_test.rego, docs/rules/idiomatic/use-in-operator.md, docs/rules/style/use-in-operator.md
Hey @anderseknert and Team! 👋 
Thought I'd try to lend a hand!
In terms of the `README`, I was not 100% sure how you envisioned it e.g.:
- Leave the readme where it is and update it saying it moved.
- Move the readme to the new location under `idiomatic` and update it saying it was previously under `style`
Let me know what you think is best here and I will update it 😄 
Not sure if I missed anything else! Please LMK and I'll get back to it!
This Fixes https://github.com/StyraInc/regal/issues/185
Thanks 🚀
=> #185, moving the use-in-operator to idiomatic and its relevant files

.pre-commit-hooks.yaml, README.md
Add a `.pre-commit-hooks.yaml` file so that `regal`, more specifically `regal lint` can be utilised as a pre-commit hook via the popular [pre-commit](https://pre-commit.com) project.
=> feat: add pre-commit hook

.pre-commit-hooks.yaml, README.md, build/download-and-run.sh
- Using a shell script, check if `regal` binary is not yet present in pre-commit repo clone and download right binary for system and architecture.
- should work for Linux and MacOS, only tested on Linux atm.
=> Add self-downloading pre-commit hook

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/non_raw_regex_pattern.rego, bundle/regal/rules/idiomatic/non_raw_regex_pattern_test.rego, docs/rego-style-guide.md, docs/rules/idiomatic/non-raw-regex-pattern.md, e2e/testdata/violations/most_violations.rego
Following the Rego Style Guide, this rule ensures regex patterns are provided as raw strings in order to avoid having to escape things like `\` inside of the regex.
Fixes #222
=> Rule: non-raw-regex-pattern

.github/workflows/build.yaml
On PRs we receive both the `on.push` and `on.pull_request` events and triggering multiple events at the same time ends up in triggering workflow runs multiple times as noticed by @anderseknert. Thanks Anders!
Avoid using wildcard in push branches and only limit to known branch names only used outside PRs.
Fix #230.
Signed-off-by: Leonardo Taccari <leonardo@faire.ai>
---
For possible further references... If we give a look to <https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-multiple-events>, quoting interesting part directly here:
> If multiple triggering events for your workflow occur at the same time, multiple workflow runs will be triggered.
...and indeed if we look at the last PR merged, i.e. #228 we can see that the `build` was run once for …
=> Run GitHub Actions workflow only once

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/custom/naming_convention_test.rego, cmd/lint.go, docs/custom-rules.md, docs/development.md, docs/rules/custom/naming-convention.md, e2e/cli_test.go, e2e/testdata/configs/custom_naming_convention.yaml, e2e/testdata/custom_naming_convention/policy.rego
This should hopefully help people satisfy the most common organizational requirements without having to write their own rules. First off is the naming-convention rule, with more to follow later.
Fixes #19
=> Add custom category and rule for naming conventions

README.md
Absolute links are used for hrefs in this doc, makes sense to use them for srcs too.
=> [docs] Use absolute links for images

README.md
This is intended to make the readme content more portable when rendered elsewhere.
=> Use abs link for config file link

docs/rules/imports/avoid-importing-input.md, docs/rules/style/avoid-get-and-list-prefix.md, docs/rules/style/prefer-snake-case.md
IMHO it makes sense to first present *why*, then the cases for when exceptions might make sense.
Also made H2's for these sections.
=> Move "Exceptions" to after "Rationale"

.gitattributes
Fixing the issue where *.rego.tpl was identified as "Smarty".
=> Add .gitattributes for proper language detection

build.sh, build/fetch_builtin_data.sh, bundle/regal/opa/builtins/data.json
This was just calling another script, so rather redundant.
Rename `fetch_data.sh` -> `fetch_builtin_data.sh` as that better describes what the script does.
Actually run the script to update the built-in data available in Regal policy.
=> Remove build.sh script

bundle/regal/ast.rego, bundle/regal/ast_test.rego, bundle/regal/config/exclusion.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/use_some_for_output_vars.rego, bundle/regal/rules/idiomatic/use_some_for_output_vars_test.rego, docs/rules/idiomatic/non-raw-regex-pattern.md, docs/rules/idiomatic/use-some-for-output-vars.md, e2e/testdata/violations/most_violations.rego
This commit adds AST functions to find vars in scope of a location, which means scanning "up" in the scope for e.g. rules or other vars to check if they are present. This allows us to see if a possible "output var" is defined using some, or if it is an "input" var that's assigned elsewhere in the policy.
Fixes #250
=> Rule: use-some-for-output-vars

README.md
I keep forgetting to run:
```
go run main.go table --write-to-readme bundle
```
After I've added a new rule. Will create an issue to have that check added to the CI pipeline.
=> Add `use-some-for-output-vars` to table in README

.pre-commit-hooks.yaml, docs/pre-commit-hooks.md
The current pre-commit hook configuration only allows the hook to run on a `pre-commit` hook. The default configuration enables the hook for all hook types supported by pre-commit as per the [docs](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages), e.g. on a `push` hook which is very useful for CI.
Also a minor fix for the docs to use a ref that works.
=> Enable pre-commit hook for all hook types

cmd/lint.go, e2e/cli_test.go, internal/io/io.go, pkg/config/config.go, pkg/config/filter.go, pkg/linter/linter.go, pkg/linter/linter_test.go, pkg/rules/rules.go
Also:
* Allow files to be provided either from file paths, *or* programmatically as modules.
* Marshal config directly to Config struct, and prefer to use the struct rather than passing around the config as a map.
Fixes #265
=> Filter out files _before_ parsing

.github/workflows/build.yaml, README.md, cmd/constants.go, cmd/lint.go, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
This will have violations printed in PRs as annotations in the source code at the location of the violation.
In addition to this, the GitHub output format also prints the summary as a "Job Summary", which is a rather nice touch!
Fixes #260 
**Annotations**
**Job Summary**
=> Add GitHub output format

README.md, bundle/regal/ast.rego, bundle/regal/ast_test.rego, bundle/regal/config/exclusion.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/not_equals_in_loop.rego, bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/style/prefer_snake_case_test.rego, bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego, docs/rego-style-guide.md, docs/rules/style/prefer-some-in-iteration.md, pkg/linter/linter_test.go
Building on top of previous work to find vars and to determine the "scope" of a variable, this commit adds a new rule in the style category to prefer `some x in y` over `x := y[_]`.
There are also a few fixups here related to the new rule, and some that were forgotten about in the previous rule added.
Note that there are some situations where a variable may thought of as being in scope while not actually being in scope — such as when iteration happens after a comprehension, as we have no way of keeping the nesting level "state" currently. This should not lead to false positives but could lead to a few cases being missed, which I think is OK for the time being. Will need to investigate better methods for determining scope, and likely outside of Rego.
Fixes #243
=> Rule: prefer-some-in-iteration

bundle/regal/ast.rego, bundle/regal/rules/bugs/rule_named_if.rego, bundle/regal/rules/bugs/rule_shadows_builtin.rego, bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/style/avoid_get_and_list_prefix.rego, bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/style/use_assignment_operator_test.rego, bundle/regal/rules/testing/identically_named_tests.rego, bundle/regal/rules/testing/todo_test.rego, internal/embeds/templates/builtin/builtin.rego.tpl, internal/embeds/templates/custom/custom.rego.tpl
The name attribute is not present in ref-head rules, so make sure things keep working when those are around.
Fixes #276
Note though that the rules don't yet necessarily take all ref names into account. Will look at that separately. Just fix the bug for now.
=> Ensure rule "name" logic works without rule.head.name

bundle/bundle.go, cmd/lint.go, cmd/test.go, internal/embeds/embeds.go, internal/io/io.go, main.go
No functional changes, I hope!
=> bundle: rearrange embed.FS setup

README.md, bundle/regal/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/prefer_snake_case_test.rego, bundle/regal/rules/testing/metasyntactic_variable.rego, bundle/regal/rules/testing/metasyntactic_variable_test.rego, docs/rules/testing/metasyntactic-variable.md, e2e/testdata/violations/most_violations.rego, internal/embeds/templates/builtin/builtin_test.rego.tpl, pkg/linter/linter_test.go
Add rule to check for "foo", "bar" and other metasyntactic variables.
Fixes #244
This PR also unifies the logic of this rule and prefer-snake-case, as well as their tests.
=> Rule: metasyntactic-variable

bundle/regal/config/config.rego, bundle/regal/config/config_test.rego, bundle/regal/config/exclusion.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/main.rego, bundle/regal/result.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/prefer_some_in_iteration.rego
This function expected an object derived from a rule annotation, and while we no longer use that this function remained the same. Instead we now expect just the category and title of the rule.
=> Refactor: improve config.for_rule ergonomics

bundle/regal/rules/style/file_length.rego, bundle/regal/rules/style/file_length_test.rego, cmd/lint.go, e2e/cli_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/linter/linter.go
More capabilities to be added in time, but for now:
* Disable `print` output unless the debug flag is provided
* Print the location of the user configuration file found
* Print the final configuration merged from provided and user conf
* Fix bug that made configuration be parsed and merged twice
=> Add `--debug` flag to `regal lint` command

cmd/test.go, e2e/cli_test.go, internal/compile/compile.go, internal/test/test.go
...by rewriting some refs on loading: data.regal becomes data.internal.regal,
both in package definitions and imports, e.g.
package regal.main
import data.regal.config
becomes
package regal.internal.main
import data.internal.regal.config
**Update** ☝️ This didn't work. Custom rules might use `data.regal` in their code, and direct refs would have to be rewritten too (so `data.regal.config.whatever` without an import).
⏩ We're now using a ModuleLoader to load packages from the embedded Regal module into `data.regal` as needed. This allows for running all of
- `regal test bundle` # all of it
- `regal test bundle/regal/main_test.rego` # individual test files
=> test: allow running "regal" on its own bundle 

bundle/regal/config/config.rego, bundle/regal/config/config_test.rego, e2e/cli_test.go, e2e/testdata/configs/rule_without_level.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go
Previously, this would lead to the rule level getting set to "" (empty string), which "worked" as it would still print the violation, but since it wasn't set to `error` it would not change the exit code of the lint command.
If the level is not provided in user configuration now, we simply inherit the value from the provided configuration.
Fixes #285
=> Allow not providing level in user configuration

e2e/cli_test.go
Rather than causing a panic, exit gracefully with a message in case the binary doesn't exist.
I entertained the idea of building the binary if needed, but since these tests run in parallel, that would be problematic.
Tried using the [TestMain](https://pkg.go.dev/testing#hdr-Main) function to check only once, but there seems to be no way to get print output from that function unless `-v` is used, as none of the t.Log functions are available there.
Fixes #294
=> Check for presence of binary before running e2e tests

README.md, bundle/regal/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/chained_rule_body.rego, bundle/regal/rules/style/chained_rule_body_test.rego, bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/testing/metasyntactic_variable.rego, docs/development.md, docs/rules/style/chained-rule-body.md, e2e/testdata/violations/most_violations.rego, internal/embeds/templates/builtin/builtin_test.rego.tpl
While `opa-fmt` fixes this, this is peculiar enough that the rule docs alone make for an informative source to point at.
Also some minor improvements here and there:
* Fix other rules that would report false positives when chained rules bodies were present
* Remove a trailing quote in the builtin test template used by `rego new rule`
* Add some guiding principles for new rules in development.md
Fixes #292
=> Rule: chained-rule-body

.github/workflows/build.yaml, cmd/table.go
And add check in CI so that we don't forget about this when any change would update the table, like when a new rule is added, or the name/description of a current one is modified.
Fixes #258
=> Add `--compare-to-readme` flag to `regal table`

bundle/regal/ast.rego, bundle/regal/rules/idiomatic/non_raw_regex_pattern.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/function_arg_return_test.rego, bundle/regal/rules/testing/dubious_print_sprintf.rego, bundle/regal/rules/testing/print_or_trace_call.rego
And use this to guard expensive `walks` when possible
This gives a modest performance improvement:
**main**
```
go run main.go lint --enable-all ~/tmp/kics/assets  199.62s user 8.53s system 604% cpu 34.459 total
```
**change**
```
go run main.go lint --enable-all ~/tmp/kics/assets  183.42s user 8.19s system 588% cpu 32.560 total
```
But importantly, it'll allow more rules to use this guard in the future, as well as quickly retrieve all built-in functions called in a policy.
Also, fix a correctness issue in `function-arg-return`, where it previously would only report functions with a single part in their name, i.e. `indexof` but not `regex.match`.
=> Store list of refs for use by rules

README.md, bundle/regal/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/result.rego, bundle/regal/rules/custom/forbidden_function_call.rego, bundle/regal/rules/custom/forbidden_function_call_test.rego, bundle/regal/rules/style/function_arg_return.rego, docs/rules/custom/forbidden-function-call.md
This rule allows teams and orgs to provide a list of built-in functions that Regal should treat as linter errors.
Fixes #223
=> Rule: `forbidden-function-call` (custom)

build/do.rq, build/fetch_builtin_data.sh, bundle/regal/opa/builtins/data.json, docs/development.md
And have some fun while trying out `rq` as a build tool:
- Allow more than one task to be provided to `do.rq`
- Add `do.rq tasks` command to list all tasks (hack alert!)
- Replace shell script to fetch built-in metadata definitions with `do.rq fetch_metadata` command
- Add metadata annotations to package and tasks (used in `tasks` command via hack)
- Update development docs to include prerequisites and references to the `rq` tool, and a section for how to prepare a PR.
`do.rq tasks` in action:
Fixes #269
=> Add rq `pr` task to help prepare for PRs

.gitattributes
As we're not seeing syntax highlighting of these files, let's try with the name it's actually [given](https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml#L4790C1-L4790C18) :P
=> Use Open-Policy-Agent as linguist language

build/do.rq
`build` is not `build(fresh)`, and will only rebuild the ./regal binary if passed `true`. If passed `false`, it will not rebuild the binary if some binary is present in the given location.
`build(false)` is thus to be used when any regal version will do, like for printing tasks.
=> build/do.rq: build binary for tasks list if needed

build/do.rq
I believe there's more to be done for windows support, but it's one barrier less, maybe.
=> do.rq: don't depend on 'ls'

pkg/config/config.go, pkg/config/config_test.go
As these are assigned to "real" struct attributes, they should not be present in extra attributes too.
Add test to verify.
From discussion in #304
=> Unmarshalling: Remove extra attributes "level" and "ignore"

e2e/cli_test.go, pkg/config/filter.go
* Ignore .git and .idea directories
* Use more efficient algorithm for filtering than the one provided by OPA
Fixes #330
=> File filtering improvements

bundle/regal/main.rego, e2e/cli_test.go, e2e/testdata/aggregates/rego/policy_1.rego, e2e/testdata/aggregates/rego/policy_2.rego, e2e/testdata/aggregates/rules/custom_rules_using_aggregates.rego, pkg/linter/linter.go, pkg/report/report.go
Feature described by: https://github.com/StyraInc/regal/issues/282
Summary: 
This change allows custom rules to collect aggregate data while processing a file AST, which can be used later by other linter rules that require a global context.
Highlights of the change:
1. Added a new feature in the linter to collect aggregates. This is done by creating a new type `Aggregate` that collects data while processing a file AST and can be used later by other rules that need a global context.
2. Modified the `lintWithRegoRules` function to include the aggregates in the evaluation process.
3. Created a helper function `evalAndCollect` to extract common code that processes each file in a goroutine.
4. Updated the end-to-end testing to include the aggregates in the testing process. This includes …
=> Implement Aggregates Collection and Usage

bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/bugs/top_level_iteration_test.rego
The `top-level-iteration` is meant to detect rules that have iteration without function body. Referencing parameters or constants should be okay without a function body. This change allows that.
=> Allow parameters and constants in top level rule

README.md, bundle/regal/ast_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/result_test.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/custom/naming_convention_test.rego, bundle/regal/rules/style/rule_length.rego, bundle/regal/rules/style/rule_length_test.rego, bundle/regal/rules/style/unconditional_assignment.rego, bundle/regal/rules/testing/print_or_trace_call_test.rego, docs/rules/style/file-length.md, docs/rules/style/line-length.md, docs/rules/style/rule-length.md, e2e/cli_test.go, e2e/testdata/violations/most_violations.rego, internal/embeds/schemas/regal-ast.json, internal/parse/parse.go
Made easy by now having the `text` attribute present in the AST. Thanks for that @charlieegan3!
Fixed existing violations against this rule, which were almost exlusively in tests. Sprinkled a few ignore directives in the places where it wasn't possible to make rules any shorter.
Fixes #236
=> Rule: `rule-length`

README.md, internal/test/rego_test.go, main.go, pkg/linter/linter_test.go
We don't need that anymore since @johanfylling bumped us up to v0.57.0
=> Remove code that set the ref head env var

README.md, bundle/regal/ast.rego, bundle/regal/config/config.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/constant_condition.rego, bundle/regal/rules/style/default_over_else.rego, bundle/regal/rules/style/default_over_else_test.rego, bundle/regal/rules/style/rule_length.rego, bundle/regal/rules/style/rule_length_test.rego, docs/rules/style/default-over-else.md, e2e/testdata/violations/most_violations.rego, pkg/version/version.go
Prefer default assignment over catch-all `else`. This rule was originally meant to endorse the new default function construct, but having tested it out thoroughly for this rule, I'm now more inclined to have it flagged. I find that counter-intuitive, and as such more likely to cause harm than good. Those who disagree may configure the `prefer-default-functions` option. Either way, default assignment over the equivalent `else` feels more idiomatic to me, so the rule feels relevant despite not doing what was originally intended.
Fixes #211
=> Rule: `default-over-else`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/main.rego, bundle/regal/rules/idiomatic/no_defined_entrypoint.rego, bundle/regal/rules/idiomatic/no_defined_entrypoint_test.rego, docs/rules/idiomatic/no-defined-entrypoint.md, e2e/testdata/aggregates/three_policies/policy_1.rego, e2e/testdata/aggregates/two_policies/policy_1.rego
Aggregate rule number two, in which we aggregate entrypoint annotations, and fail if we don't find any.
Fixes #154
=> Rule: `no-defined-entrypoint`

cmd/lint.go, internal/metrics/metrics.go, pkg/linter/linter.go, pkg/report/report.go
This sets a profiler on eval in each goroutine, and then accumulates the result from each into a final report. At this point we're only including this in the JSON output format (similar to `--metrics`) but we'll want to support this for each format some time later.
Fixes #334
```shell
go run main.go lint -f json --profile bundle
```
```json
{
"violations": [],
"summary": {
"files_scanned": 98,
"files_failed": 0,
"files_skipped": 0,
"num_violations": 0
},
"profile": [
{
"location": "/regal/ast.rego:278",
"total_time_ns": 1329484096,
"num_eval": 4,
"num_redo": 27214,
"num_gen_expr": 4
},
{
"location": "/regal/config/config.rego:90",
"total_time_ns": 1122320502,
"num_eval": 176,
"num_redo": 88,
"num_gen_expr": 4
},
{
"location": "/regal/ast.rego:218",
"total_time_ns": 984304114,
"num_eval": …
```
=> Add `--profile` option to `regal lint`

bundle/regal/ast.rego, bundle/regal/rules/bugs/constant_condition.rego, bundle/regal/rules/bugs/constant_condition_test.rego, bundle/regal/rules/bugs/rule_named_if.rego, bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom_in_construct.rego, bundle/regal/rules/idiomatic/no_defined_entrypoint.rego, bundle/regal/rules/idiomatic/no_defined_entrypoint_test.rego, bundle/regal/rules/idiomatic/use_some_for_output_vars.rego, bundle/regal/rules/style/rule_length.rego, bundle/regal/rules/style/unconditional_assignment.rego
* `rule-named-if`: Skip iteration if no rule named "if"
* Detect generated rule bodies without uncertainty
* Move commonly used idioms and helper to ast package
* Added a few comments for docs here and there
=> Some small tweaks

.github/workflows/build.yaml, build/do.rq, cmd/lint.go
So that we don't silence the GitHub workflow commands
Fixes https://github.com/StyraInc/regal/issues/356
=> Add run_quiet to rq build script

docs/rules/bugs/invalid-metadata-attribute.md, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
Using *only* annotations makes it hard to tell from the actions check view what went wrong, or more specifically, *where*. Now users will see both the pretty table, _and_ get annotations in the PR.
Fixes #345
=> Let `--format github` log pretty output to console

.gitignore, pkg/config/config.go
The logic traversing directories looking for a `.regal` directory did not take a possible volume name (like `C:`) into account. With this, all tests (unit + e2e)  now pass on Windows as well as UNIX.
=> Fix issues blocking Windows usage

.github/workflows/build.yaml, e2e/cli_test.go
Now with Regal working for Windows. Could not get `rq` to work here though so wer're not using that on the Windows runner for the time being.
Also fixed an issue in the e2e tests where stderr wasn't correctly read, and simplified the common case of checking for exit code with a helper function.
Two tests creating new files from templates using the `regal new rule` command are currently skipped on Windows, as they fail for some reason I don't have the time to look into now. The commands work, but `regal test` doesn't seem to find the created temp dir. Not critical at all, so I don't feel bad about skipping those for now.
=> Windows runner test

bundle/regal/rules/style/default_over_else.rego, bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/style/use_assignment_operator_test.rego
Also simplified the logic of this rule for other types of rule assignment.
Fixes #385
=> `use-assignment-operator`: check for assignment operator in else assignment

bundle/regal/rules/style/unconditional_assignment.rego, bundle/regal/rules/style/unconditional_assignment_test.rego, docs/rules/style/unconditional-assignment.md
```rego
x contains y if {
y := 1
}
```
Would be better simplified to:
```rego
x contains 1
```
Fixes #384
=> `unconditional-assignment`: extend to include multi-value rules

bundle/regal/rules/style/no_whitespace_comment.rego, bundle/regal/rules/style/no_whitespace_comment_test.rego, docs/rules/style/no-whitespace-comment.md
This allows policy authors to list patterns other than whitespace that should be considered OK by this rule.
Fixes #379
=> `no-whitespace-comment`: add `except-pattern` config attribute

bundle/regal/ast.rego, bundle/regal/rules/bugs/constant_condition.rego, bundle/regal/rules/bugs/constant_condition_test.rego, bundle/regal/rules/style/rule_length.rego
=> Fix `constant-condition` flagging multi-value rules without body

bundle/regal/ast.rego, bundle/regal/ast_test.rego
=> Fix false positive on function without body in `constant-condition`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/equals_pattern_matching.rego, bundle/regal/rules/idiomatic/equals_pattern_matching_test.rego, docs/rules/idiomatic/equals-pattern-matching.md, e2e/testdata/violations/most_violations.rego
Prefer to use pattern matching for equality in function args.
Currently limited to simple rules where the equality check is the only condition in the rule head or rule body (and this limitation is described in the rule docs). I'm hoping to improve this in the future, but as I think there's value in this already, so let's ship and iterate.
Fixes #397
=> Rule: `equals-pattern-matching`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/custom/prefer_value_in_head.rego, bundle/regal/rules/custom/prefer_value_in_head_test.rego, docs/rules/custom/prefer-value-in-head.md
This is a custom rule allowing teams to standardize on this as a preference should they want to.
Fixes #398
=> Rule: `prefer-value-in-head`

bundle/regal/rules/testing/identically_named_tests.rego, bundle/regal/rules/testing/identically_named_tests_test.rego, docs/rules/style/rule-length.md
We did not have that option when this rule was written, but we do now.
Also some unrelated doc fixes for the `rule-length` rule.
=> `identically-named-tests`: add precise location

README.md, bundle/regal/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/custom/one_liner_rule.rego, bundle/regal/rules/custom/one_liner_rule_test.rego, bundle/regal/rules/custom/prefer_value_in_head_test.rego, docs/rules/custom/one-liner-rule.md
Custom rule to suggest one-liner syntax where possible. Taking into account:
* Line length of shortened rule must not exceed max line length (configurable, default 120)
* Comments in rule body cancels suggestion, as we can't turn those to one-liners without changing "semantics" of the comment
Fixes #420
=> Rule: `one-liner-rule`

bundle/regal/rules/idiomatic/equals_pattern_matching.rego, bundle/regal/rules/idiomatic/equals_pattern_matching_test.rego
=> `equals-pattern-matching`: fix false positive with `else`

bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/rule_length.rego, bundle/regal/rules/style/rule_length_test.rego, docs/rules/style/rule-length.md, e2e/testdata/violations/most_violations.rego
This is set to `false` by default, as we don't want to "punish" comments in rules.
Fixes #432
=> `rule-length`: add `count-comments` configuration option

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/result.rego, bundle/regal/rules/bugs/inconsistent_args.rego, bundle/regal/rules/bugs/inconsistent_args_test.rego, bundle/regal/rules/idiomatic/equals_pattern_matching_test.rego, docs/rules/bugs/inconsistent-args.md, e2e/testdata/violations/most_violations.rego
Warn on inconsistent argument names in repeated function declarations.
Fixes #444
=> Rule: `inconsistent-args`

cmd/new.go
Tbh, we should probably reconsider if we should add capabilities as part of unmarshalling? But for now let's just fix the bug.
Fixes #446
=> Don't set capabilities on `regal new rule`

bundle/regal/main.rego
For the provided rules, we don't need to check this over and over. Not making a dent on eval time, but somewhat nicer looking code.
=> Refactor: collect rules to run only once

bundle/regal/ast.rego, bundle/regal/main.rego, bundle/regal/rules/custom/forbidden_function_call.rego, bundle/regal/rules/idiomatic/non_raw_regex_pattern.rego, bundle/regal/rules/imports/prefer_package_imports.rego, bundle/regal/rules/style/external_reference.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/todo_comment.rego, bundle/regal/rules/style/yoda_condition.rego, bundle/regal/rules/testing/dubious_print_sprintf.rego, bundle/regal/rules/testing/print_or_trace_call.rego
The rules that walk refs may benefit from having the AST tree walked *once* with refs collected, and then simply iterate over that collection. Also, a few  micro-optimizations in the hotspots reported by `--profile`.
Eval time reduced by 4-5%, so nothing dramatic, but still good.
=> Optimization: less use of walk

README.md, bundle/regal/capabilities.rego, bundle/regal/config/provided/data.yaml, bundle/regal/regal.rego, bundle/regal/rules/bugs/if_empty_object.rego, bundle/regal/rules/bugs/if_empty_object_test.rego, bundle/regal/rules/bugs/unused_return_value_test.rego, bundle/regal/rules/custom/forbidden_function_call_test.rego, bundle/regal/rules/custom/one_liner_rule.rego, bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/non_raw_regex_pattern_test.rego, bundle/regal/rules/imports/import_shadows_builtin_test.rego, bundle/regal/rules/style/function_arg_return_test.rego, bundle/regal/rules/testing/dubious_print_sprintf_test.rego, bundle/regal/rules/testing/print_or_trace_call_test.rego, docs/rules/bugs/if-empty-object.md, e2e/testdata/violations/most_violations.rego
Flag empty "body" like `{}` as that's no longer considered a body.
Also some light refactoring here, breaking out capabilities checks to a separate package. More to happen here soon!
Fixes #451
=> Rule: `if-empty-body`

README.md, bundle/regal/capabilities.rego, bundle/regal/config/config_test.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/use_contains.rego, bundle/regal/rules/idiomatic/use_contains_test.rego, bundle/regal/rules/idiomatic/use_if.rego, bundle/regal/rules/idiomatic/use_if_test.rego, docs/rules/idiomatic/use-contains.md, docs/rules/idiomatic/use-if.md, e2e/testdata/capabilities/custom_has_key.rego, e2e/testdata/capabilities/custom_has_key_2.rego, e2e/testdata/custom_naming_convention/policy.rego, e2e/testdata/violations/most_violations.rego, pkg/linter/linter_test.go
Recommend the use of `if` and `contains` when available as capabilities.
Some fixes to tests where we didn't live up to this standard ourselves. Great!
(Note that this is targeting the `if-empty-object` branch as that contained a few improvements that I wanted here, so that should be merged before this PR)
Fixes #468
=> Rule: `use-if` and `use-contains`

bundle/regal/ast.rego, bundle/regal/rules/idiomatic/use_contains.rego, bundle/regal/rules/idiomatic/use_if.rego, docs/rules/idiomatic/use-contains.md, docs/rules/idiomatic/use-if.md, pkg/config/config.go
And not the later commit we're pointing at for rego.v1 functionality. We don't want to promote capabilities that users will need a dev version of OPA to get.
Also, don't run `use-contains` and `use-if` if `rego.v1` is imported, as that's enforced by OPA already.
=> Use capabilities from v0.58.0

README.md
This is being done to make it more consistent, this should have happened in the last PR. https://github.com/StyraInc/regal/pull/485
=> docs: Extend note in readme

bundle/regal/rules/bugs/unused_return_value.rego, bundle/regal/rules/bugs/unused_return_value_test.rego
=> Fix: false positive with `print` and `unused-return-value`

go.mod
As noted in #490, by using a `replace` directive, we're unable to then `go
install` this project:
```
% go install github.com/StyraInc/regal@latest
go: downloading github.com/StyraInc/regal v0.13.0
go: github.com/StyraInc/regal@latest (in github.com/StyraInc/regal@v0.13.0):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
Instead, we can replace this with a direct pinning to the commit we want to pull.
Closes #490.
=> Replace `replace` directive with direct version pinning

bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego, cmd/parse.go, docs/rules/style/prefer-some-in-iteration.md, internal/parse/parse.go, pkg/builtins/builtins.go, pkg/linter/linter.go
As this is a more expressive form, we should allow it by default with an option to have it disabled.
Also an unrelated renaming issue in Go code, which did not warrant its own PR.
Fixes #351
=> `prefer-some-in-iteration`: except subattribute iteration

.github/workflows/build.yaml, README.md, build/do.rq, bundle/regal/rules/style/avoid_get_and_list_prefix.rego, bundle/regal/rules/style/avoid_get_and_list_prefix_test.rego, docs/.markdownlint.yaml, docs/architecture.md, docs/development.md, docs/editor-support.md, docs/integration.md, docs/pre-commit-hooks.md, docs/rego-style-guide.md, docs/rules/bugs/not-equals-in-loop.md, docs/rules/custom/prefer-value-in-head.md, docs/rules/idiomatic/prefer-set-or-object-rule.md, docs/rules/idiomatic/use-if.md, docs/rules/style/default-over-else.md, docs/rules/style/function-arg-return.md, docs/rules/style/line-length.md, docs/rules/style/prefer-some-in-iteration.md, docs/rules/style/todo-comment.md, docs/rules/style/use-in-operator.md, docs/rules/testing/metasyntactic-variable.md, docs/rules/testing/test-outside-test-package.md, docs/rules/testing/todo-test.md
Disable some overly pedantic rules, but good to help keep our docs consistent.
=> Add markdownlint for linting docs

.github/workflows/build.yaml
This allows us to test the build on linux, mac and windows with the same set of steps. Previously, rq hadn't worked on windows and macOS is a new addition.
=> [build]: Add matrix PR build

bundle/regal/ast.rego, bundle/regal/rules/bugs/redundant_existence_check.rego, bundle/regal/rules/idiomatic/use_in_operator.rego, bundle/regal/rules/idiomatic/use_in_operator_test.rego
=> `use-in-operator`: extend check to include static refs

bundle/regal/rules/imports/prefer_package_imports.rego, bundle/regal/rules/imports/prefer_package_imports_test.rego
=> `prefer-package-imports`: except data.regal imports in custom rules

pkg/version/version.go
```
Version:    0.7.0
Go Version: go1.20.7
Platform:   darwin/amd64
Commit:        unknown
Timestamp:  2023-08-11T08:51:41Z
Hostname:   github.actions.local
```
I found it slightly misaligned there... probably not intentionally so
=> pkg/version: remove spurious whitespace from String()

docs/rules/style/function-arg-return.md
Just inflating my commit count like it mattered something 🙃 Kidding, just can't let that typo slide.
=> function-arg-return: fix docs typo

bundle/regal/ast.rego, bundle/regal/ast_test.rego
all_refs was missing refs in imports and certain types of rules.
This change updates the all_refs rule to return these refs making them available to rule authors.
=> bundle: update all_refs to get more refs

pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
And don't include notices on deprecated/obsolete rules at all in report.
Fixes #513
=> SARIF: Use `none` for `level` in notices

bundle/regal/ast.rego
This avoids a loop over rules twice. Fixes an issue added in https://github.com/StyraInc/regal/pull/512
=> [ast]: Improve all_refs performance

docs/adopters.md
This adds minder to `docs/adopters.md`. For more info on Minder's regal
adoption, see: https://stacklok.com/blog/writing-minder-rule-types-with-open-policy-agent-and-rego
=> Add Minder to list of open source projects that have adopted regal

docs/adopters.md
This adds minder to docs/adopters.md. For more info on Stacklok's Regal
adoption, see: https://stacklok.com/blog/writing-minder-rule-types-with-open-policy-agent-and-rego
=> Add Stacklok to the list of companies that have adopted Regal

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/comments.rego, bundle/regal/ast/imports.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/default_over_not.rego, bundle/regal/rules/style/default_over_not_test.rego, docs/rules/style/default-over-not.md, e2e/testdata/violations/most_violations.rego
Also, start to break up ast.rego into more files, as we started to violate the `file-length` rule. We should continue on this work in follow-up PRs, but for now just make sure we aren't breaking our own rules.
Fixes #517
=> Rule: `default-over-not`

bundle/regal/main.rego, bundle/regal/main_test.rego, bundle/regal/rules/style/todo_comment.rego
=> Allow ignore directive anywhere in comment

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/duplicate_rule.rego, bundle/regal/rules/bugs/duplicate_rule_test.rego, bundle/regal/util/util.rego, docs/rules/bugs/duplicate-rule.md, e2e/testdata/violations/most_violations.rego
As the name implies, flag duplicate rules when found. See the docs included in the PR for more details, including current limitations.
This rule should be an aggregate rule, but it was hairy enough to pull off with a single file scope, so I decided to hold off on that for now. This provides value already, so let's ship it and consider looking into making this aggregate later.
Fixes #427
=> Rule: `duplicate-rule`

.golangci.yaml, cmd/lint.go, pkg/rules/fmt.go
See https://golangci-lint.run/usage/linters#revive for config details, and https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md for all descriptions.
=> ci: enable unused-parameters and unused-receivers in revive linter

docs/custom-rules.md
This fixes a broken link I noticed while making a custom rule. Thanks!
=> docs: fix broken link to ast.rego

internal/lsp/server.go
This message also doesn't have params, and so we need to make sure we handle that correctly in the debug logging.
Related to https://github.com/open-policy-agent/vscode-opa/pull/98
=> lsp: Support lsp client shutdown message

.github/workflows/update-docs.yaml
=> docs: add workflow to auto update docs

.github/workflows/update-docs.yaml
I am not entirely convinced this will allow the workflow to trigger the jobs in another repo, but this is a test as the alternative isn't ideal.
=> Update permissions to allow running actions

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/double_negative.rego, bundle/regal/rules/style/double_negative_test.rego, cmd/table.go, docs/rules/style/double-negative.md, e2e/testdata/violations/most_violations.rego
@anderseknert this is 'your' rule so feel free to rebase this branch and take the commit.
=> rules: Add double negative rule

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/main.rego, bundle/regal/rules/performance/with_outside_test_context.rego, bundle/regal/rules/performance/with_outside_test_context_test.rego, docs/rules/performance/with-outside-test-context.md, e2e/testdata/violations/most_violations.rego
See docs in PR for description.
This also introduces a new `performance` category.
Fixes #548
=> Rule: `with-outside-test-context`

bundle/regal/ast/ast.rego, bundle/regal/rules/style/external_reference.rego, bundle/regal/rules/style/external_reference_test.rego
By taking variables declared in the return value into account when counting vars in scope.
Fixes #560
=> Fix false positive in `external-reference`

bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego
Don't flag iteration inside of arrays, sets or objects as using `some` in that context isn't possible.
Fixes #553
=> Fix false positive in `prefer-some-in-iteration`

internal/lsp/cache.go, internal/lsp/clients/clients.go, internal/lsp/messages.go, internal/lsp/server.go, internal/lsp/uri/uri.go, internal/lsp/uri/uri_test.go
I have been doing some testing on Windows and found that the URI formats representing files and identifying them work in different ways. This PR contains changes to the language server implementation that allow Regal LS to work with a VS code client on windows.
Namely, this PR adds a new package with functions to perform the required translations on URI values needed to operate in the context of each supported client - currently VS code only.
=> lsp: Correctly handle URIs and paths on Windows

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/config/config.rego, bundle/regal/result.rego, bundle/regal/rules/custom/prefer_value_in_head.rego, bundle/regal/rules/idiomatic/equals_pattern_matching.rego, bundle/regal/rules/style/external_reference.rego, bundle/regal/rules/style/external_reference_test.rego, bundle/regal/rules/style/unnecessary_some.rego, docs/rules/style/external-reference.md
This took quite some effort as the first iteration of this rule was rather basic. While this makes it a bit annoying with its pedantry, at least it's now **correct**. One benefit of this is that `ast.find_vars` now also takes function arg return value bindings into account, which may have positive impact on other rules as well.
Fixes #191
=> Address `external-reference` missing cases

bundle/regal/rules/custom/prefer_value_in_head.rego, bundle/regal/rules/custom/prefer_value_in_head_test.rego, docs/rules/custom/prefer-value-in-head.md
And rename it in the docs as it was previously called `only-literals`.
Fixes #568
Fixes #567
=> Fix broken `only-scalars` config in `prefer-value-in-head` rule

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/rule_shadows_builtin.rego, bundle/regal/rules/bugs/rule_shadows_builtin_test.rego, bundle/regal/rules/imports/import_shadows_builtin.rego
=> Fix: `rule-shadows-builtin` to flag shadowed namespaces

bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego
When scalar values are on one side of e.g. `5 == input[_]` we should not recommending using `some`, but `in`.
Fixes #566
=> Fix `prefer-some-in-iteration` false positive on contains check

README.md, bundle/regal/ast/ast.rego, bundle/regal/config/config_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/circular_import_test.rego, bundle/regal/rules/imports/ignored_import.rego, bundle/regal/rules/imports/ignored_import_test.rego, docs/rules/imports/ignored-import.md
Flagging any reference in a policy that does not make use of an import where applicable.
Fixes #540
=> Rule: `ignored-import`

internal/lsp/messages.go, internal/lsp/server.go
This PR makes two changes:
- https://github.com/StyraInc/regal/issues/578 raised an issue with the unmarshalling of the initializationOptions field. We don't use this field so it has been dropped.
- We an issue when there is no root URI set in the initialize request. This PR disables workspace functions such as aggregate violations and linting of unopened files when this is the case (when a single file has been opened).
=> Language server initialisation adjustments

docs/rules/bugs/unused-return-value.md
This md ref link was working on GH, but didn't work on docs.styra.com.
=> Correct unassigned-return-value link

bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego
This fixes one of the errors reported in #528
=> Fix: `prefer-some-in-iteration` false positive iteration in fn args

docs/rules/bugs/unused-return-value.md
This allows the page to be present in GH, but no appear in docs.styra.com.
Changes already applied to docs repo
see: https://github.com/StyraInc/docs/pull/26
=> docs: make old rule draft

bundle/regal/ast/ast.rego, bundle/regal/ast/imports.rego, bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/bugs/top_level_iteration_test.rego
Fixes #590
That issue only mentions `top-level-iteration`, but I found the same behavior in `use-some-for-output-vars`, so this fixes that too.
=> Fix false positive in rules not counting imports in scope

.gitignore, .vscode/settings.json, README.md
Options like `checkOnSave` would previously not work when hacking on Regal, as a custom capabilities file would need to be provided. Using the latest version of the OPA extension, this is now supported via the `opa.env` option.
Note that actually setting `checkOnSave` or similar options is left up to each developer.
=> Add support for editing Regal in VS Code

internal/lsp/lint.go
This ensures that an error is shown when the parsing fails because the file is empty.
In this case, the astError is a single error rather than a slice.
We should add a new opa-errors entry for empty module.
=> lsp: Handle case where a rego file is empty

docs/editor-support.md
This adds a note about the availability of the nvim-lspconfig support added in
https://github.com/neovim/nvim-lspconfig/pull/3071
Thanks @folliehiyuki for the guidance on this one!
=> docs: Add note about nvim-lspconfig

docs/rules/imports/circular-import.md
=> docs: use 4 spaces for indentation in `circular-imports` docs

.github/workflows/build.yaml
No Windows binaries as of yet since `build/do.rq pull_request` silently fails, or does nothing, on Windows. At least when called from Powershell. The big discovery here however — we likely never actually built on Windows in these worflows before, or even on MacOS! This since the `runs-on` attribute didn't make use of the matrix OS value, but was instead hard-coded to use `ubuntu-latest` 🙃
We'll have to get back to the Windows build at some point, but for now we'll settle on only building on that platform for releases via goreleaser, just as we unknowingly seem to have done up until this point anyway.
Fixes #608
=> Publish binaries from build workflow #2

cmd/languageserver.go, internal/lsp/cache.go, internal/lsp/hover.go, internal/lsp/hover_test.go, internal/lsp/messages.go, internal/lsp/server.go, internal/lsp/testdata/hover/graphreachable.md, internal/lsp/testdata/hover/indexof.md, internal/lsp/testdata/hover/jsonfilter.md
This PR adds support for the `textDocument/hover` feature of the language server protocol. Currently, only the built-in functions of OPA are supported, which likely satisfies the most common requirement. In the future, we could extend this to cover also user defined functions or rules, where annotations are used to provide data for the hover response.
Screenshot from VS Code with Regal running from this branch.
=> lsp: `textDocument/hover` implementation

internal/lsp/server.go
Now when built-in state is not known for a file,
the hover response is empty. This is commonly the case when the file that has just been opened has failed to parse and never parsed in the time that the server has been running.
Fixes https://github.com/StyraInc/regal/issues/618
=> lsp: Missing built-in data is not a hard error

internal/lsp/lint.go, internal/lsp/server.go, internal/lsp/server_test.go, pkg/config/filter.go, pkg/config/filter_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go
Fixes: https://github.com/StyraInc/regal/issues/589
This PR makes the filtering logic support a new rootDir prefix. When set, this will be stripped from file paths before testing their ignore status. 
https://github.com/StyraInc/regal/assets/1774239/e2234823-6c27-4df7-b546-062ee13afc60
=> lsp: Support file ignore config

internal/lsp/hover.go, internal/lsp/inlayhint.go, internal/lsp/inlayhint_test.go, internal/lsp/messages.go, internal/lsp/rego.go, internal/lsp/server.go
This PR adds support for inlay hints of function arguments. Similar to the hover feature, only built-in functions are supported at this point.
Also did some minor refactoring in the hover function to have it use the same method for collecting built-in functions from a module as the inlay hint system does.
=> lsp: add inlay hint support

cmd/languageserver.go
Setting --verbose will now be required to see request responses from the server.
Related to: https://github.com/StyraInc/regal/issues/615
=> lsp: Make verbose logging configurable

.regal/config.yaml, cmd/languageserver.go, internal/lsp/command.go, internal/lsp/diff.go, internal/lsp/format.go, internal/lsp/messages.go, internal/lsp/server.go
https://github.com/StyraInc/regal/assets/1774239/88b8b6ab-8e23-48b5-b78a-2ebc4aa84700
=> Code action for OPA fmt

internal/lsp/uri/uri.go, internal/lsp/uri/uri_test.go
This addresses an issue when the URIs used for workspaces contain spaces - for example.
Fixes https://github.com/StyraInc/regal/issues/629
=> lsp: URI decode workspace URIs

cmd/languageserver.go, internal/lsp/connection.go, internal/lsp/server.go
While working on https://github.com/StyraInc/regal/pull/630, I needed to be able to see requests, responses and notifications to the server from the client and from the server to the client.
I learned that there is functionality in the jsonrpc2 lib that we use to do this nicely. This PR implements a new logging configuration to make use of this using an adapted version of the LogMessage function that is found in the library and using the OnRecv and OnSend functions.
Because of this, I have removed the logging responsibility from the server and moved it to the connection. The server now should log errors only and that should be the default mode of operation.
Enabling verbose logging will show you all messages being sent on the connection. ExcludeMethods and IncludeMethods can be used to …
=> Refactor LSP logging

internal/lsp/hover.go
This is a idempotent function, so no need to render the content each time it's called.
=> Cache result of `createHoverContent`

internal/lsp/command.go, internal/lsp/server.go
https://github.com/StyraInc/regal/assets/510711/1c66db15-41c0-469b-9730-ecf7b703145b
Fixes #637
=> Add code action for `use-rego-v1`

internal/lsp/format.go, internal/lsp/messages.go, internal/lsp/server.go
Although currently disabled in server capabilities while we work out how this should work with VS Code, where there is already a client-side formatter registered.
=> Implement textDocument/formatting

internal/lsp/server.go
I have not been able to work out why these are sent but they don't seem to impact the running functionality of the server and supporting them seems to be optional.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#dollarRequests
For now, this updates the server to do nothing when receiving such a request. This avoids some log lines that we don't do anything about.
I would like to come back to this though as it seems like there's more here that we might be missing. So it has been labelled as TODO.
=> lsp: Accept but ignore cancelled requests

cmd/languageserver.go, go.mod, go.sum, internal/lsp/clients/clients.go, internal/lsp/config/watcher.go, internal/lsp/config/watcher_test.go, internal/lsp/server.go, internal/lsp/server_test.go
Related https://github.com/StyraInc/regal/issues/626
https://github.com/StyraInc/regal/assets/1774239/d8108b47-568c-4ce9-a0fc-5fd608960b8e
=> lsp: Load config from parent dirs

docs/rules/style/double-negative.md
=> Fix wrong category for `double-negative` rule

bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/style/use_assignment_operator_test.rego
We previously just reported this as 1 regardless of where it was. Now we try to extract the correct column from the text in the location, or fall back to 1 if we can't find it.
=> Calculate correct column of `=` in `use-assignment-operator`

internal/lsp/server_test.go
TestLanguageServerMultipleFiles is sometimes locking up as the handler can't save new messages as the channel is waiting to be read and the part of the test that is waiting to read those particular messages is later and waiting for another file first.
This makes the buffered channels larger to allow more messages to be received for each file so that we can no block and check the messages we want in order as before.
https://github.com/StyraInc/regal/actions/runs/8724753207/job/23936066079
=> lsp: Increase test buffered channel size

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/unresolved_import.rego, bundle/regal/rules/imports/unresolved_import_test.rego, bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/util/util.rego, docs/rules/imports/unresolved-import.md
Requested since 2017! This aggregate rule will try to resolve any import provided in policy, while allowing the user to configure paths that should be resolved at runtime, like data refs.
See the docs included in the PR for more details.
Fixes #300
=> Rule: `unresolved-import`

internal/lsp/command.go, internal/lsp/commands/parse.go, internal/lsp/commands/parse_test.go, internal/lsp/messages.go, internal/lsp/server.go, pkg/fixer/fixes/fmt_test.go, pkg/fixer/fixes/nowhitespacecomment.go, pkg/fixer/fixes/nowhitespacecomment_test.go, pkg/fixer/fixes/useassignmentoperator.go
https://github.com/StyraInc/regal/pull/653 added fixes for no-whitespace-comment and use-assignment-operator. This PR adds code actions for these in the regal lsp.
Fixes https://github.com/StyraInc/regal/issues/659
Fixes https://github.com/StyraInc/regal/issues/649
=> lsp: Implement code actions for new fixes

.github/workflows/build.yaml, .golangci.yaml, e2e/cli_test.go, internal/lsp/foldingrange.go, internal/lsp/foldingrange_test.go, internal/lsp/opa/scanner/scanner.go, internal/lsp/opa/tokens/tokens.go, internal/lsp/server.go, internal/lsp/types/types.go
Adding [folding range](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange) support for:
* Imports
* Comments (when grouped on more than one line)
* Blocks from tokens like `{}`, `[]`, `()`
Scanner stolen from OPA so feel free to review that, but fixes should go into OPA ;)
Fixes #648
=> lsp: Support folding ranges

internal/lsp/documentsymbol.go, internal/lsp/documentsymbol_test.go, internal/lsp/server.go, internal/lsp/types/symbols/symbols.go, internal/lsp/types/types.go
More weekend fun! This provides a basic implementation of `textDocument/documentSymbol`. I say basic because we currently scan for nested symbols, but only package, rules and functions, with some nice touches like providing details on what kind of rule it is, and the type it returns, and so on. I think this covers what most actually need, but we can certainly refine this later and add things like variables inside of rule bodies, and so on.
=> lsp: handle `textDocument/documentSymbol`

internal/lsp/opa/oracle/oracle.go, internal/lsp/server.go, internal/lsp/types/types.go
This was rather simple, as this was already handled by the `opa oracle find-definition` command. The API for that was however internal, so I've copied the single file handling that from OPA.
PR marked WIP as two things warrants some discussion:
* Similarly to formatting, this LSP feature seems to conflict with client side implementations, and you'll see duplicate "definitions" in VS Code when this is enabled both in the client and from the LSP server. We should probably make this conditional on Regal in VS Code.
* The `GetAllModules` function that exists on the cache does not seem to take into account files that have been marked as ignored via `.regal/config.yaml`. This lead to an annoying situation when this was used in the Regal repo, as some files we've ignored did not compile, and …
=> lsp: handle `textDocument/definition` requests

internal/lsp/documentsymbol.go, internal/lsp/server.go, internal/lsp/types/types.go
This was rather trivial with document symbols supported. It's now made possible to search for symbols across the whole workspace, which is rather nice!
=> lsp: implement `workspace/symbol`

cmd/languageserver.go, internal/lsp/server.go
We have been erroring on shutdown requests as they have no params set. This PR changes that and makes sure the server waits for the exit message before closing the connection.
The client shows:
```
[Error - 18:21:10] Server process exited with code 0.
```
This is an odd one based on the code here:
https://sourcegraph.com/npm/vscode-languageclient@492942af8005ce98cbd47721d4a7790a0310d4e3/-/blob/lib/node/main.js?L474:37-474:68
It would look like we exit ok here, but that seems to be perhaps parsed as "0" the string... One for another day.
Before:
https://github.com/StyraInc/regal/assets/1774239/203792e1-3cb9-447a-a984-b53d167b11f3
After
https://github.com/StyraInc/regal/assets/1774239/dccb6b0e-cdcf-45bd-abd2-2de623b17af5
=> lsp: More graceful shutdown

bundle/regal/rules/imports/unresolved_import.rego, bundle/regal/rules/imports/unresolved_import_test.rego
Thanks @nevumx for reporting this
=> Fix false positive in `unresolved-import` and map rules

cmd/lint.go, pkg/config/config.go
As reported in #682, the server panics when the dir for whatever reason is "". I don't yet know how to trigger this, and the result of this fix is likely that the config file won't be found when this happens. But as a temporary measure I prefer to have Regal run with default configuration compared to crashing.
=> Avoid panic when searching for `.regal/config.yaml`

pkg/config/config.go
Not sure if it's worth having two different exit conditions, but I guess it doesn't hurt with some granularity?
=> fix: Avoid panic in config finder

internal/lsp/server.go
This is really the first line that contains a parse error, and so a better name would be clearer.
=> lsp: Rename lastValidLine variable

internal/lsp/documentsymbol.go
This is already reported by the document type, and constants aren't special enough to warrant extra description.
Fixes #705
=> lsp: don't add "constant" to the document symbol description

pkg/report/report.go
AddProfileEntries was creating a copy from the supplied update rather than the global store of counts.
Fixes https://github.com/StyraInc/regal/issues/457
=> report: Fix profile count aggregation

bundle/regal/ast/imports.rego, bundle/regal/rules/bugs/impossible_not.rego, bundle/regal/rules/bugs/impossible_not_test.rego, docs/rules/bugs/impossible-not.md
Improve this new rule to have the `report` rule handle single file violations, while the aggregate report ignores violations where the `not` ref and the partial rule is in the same file.
=> Single file `impossible-not`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/main.rego, bundle/regal/result.rego, bundle/regal/rules/style/messy_rule.rego, bundle/regal/rules/style/messy_rule_test.rego, docs/rules/style/messy-rule.md, e2e/testdata/violations/most_violations.rego
Help identify incremental rule definitions that aren't grouped together.
Also fix two violations against this rule that we had in our own codebase.
Fixes #672
=> Rule: `messy-rule`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/trailing_default_rule.rego, bundle/regal/rules/style/trailing_default_rule_test.rego, docs/rules/style/function-arg-return.md, docs/rules/style/trailing-default-rule.md, e2e/testdata/violations/most_violations.rego
Simple rule to check that `default` rules are placed before non-default rules.
Fixes #699
=> Rule: `trailing-default-rule`

.golangci.yaml, internal/lsp/documentsymbol.go, internal/lsp/documentsymbol_test.go, internal/lsp/server.go, internal/lsp/types/types.go, pkg/reporter/reporter.go
In case either `opa-fmt` or `use-rego-v1` is enabled, we'll send back a warning to the client whenever they save a document containing CRLF line endings. This to avoid confusion when the user tries to fix formatting using `opa fmt`, but the editor adding back CRLF line endings after.
Also disable the nestif linter, as it's annoying.
Fixes #693
=> Send warning to client on CRLF line endings

internal/lsp/server.go
Where the specification says we should. Did not change this for the notification type events, as they don't render responses. Perhaps we should change the signature of those functions to not return a result?
=> Return `null` instead of empty structs

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/impossible_not.rego, bundle/regal/rules/style/double_negative.rego, docs/rules/style/external-reference.md, docs/rules/style/prefer-some-in-iteration.md
* Only walk negated expressions once
* Update docs on `external-reference` to reflect current message
* Use rego.v1 in `prefer-some-in-iteration` docs
=> Various fixes

go.mod, go.sum, internal/lsp/lint.go, pkg/hints/hints.go, pkg/hints/hints_test.go
When regal encounters a parse error, we can sometimes workout the correct opa errors page to send the user to. This PR makes use of some existing code that matches errors to help pages.
=> lsp: show correct OPA error hint links

bundle/regal/rules/bugs/redundant_existence_check.rego, bundle/regal/rules/bugs/redundant_existence_check_test.rego
=> Fix false positive in `redundant-existence-check` when `with` is used

internal/lsp/lint.go
When a new file is created, it is empty. We need to address this since I think we are sent the contents. However, this is a fix for an index bug when processing these errors.
Before
https://github.com/StyraInc/regal/assets/1774239/5fbcb712-05ca-4f65-ad6b-8ee867256aa1
After
https://github.com/StyraInc/regal/assets/1774239/82c00e25-8613-4f90-87cf-ad24dc7d10b4
=> lsp: Fix ast error line index bug

cmd/test.go, go.mod, internal/lsp/commands/parse_test.go, internal/lsp/documentsymbol_test.go, internal/lsp/uri/uri_test.go, internal/novelty/holidays.go, pkg/config/filter_test.go, pkg/fixer/fixes/fmt_test.go, pkg/fixer/fixes/nowhitespacecomment_test.go, pkg/fixer/fixes/useassignmentoperator_test.go, pkg/linter/linter_test.go, pkg/rules/fmt_test.go
=> Use Go 1.22

internal/lsp/command.go, internal/lsp/lint.go, internal/lsp/server.go, internal/lsp/types/types.go
Make optional attributes optional, and omit when empty.
=> Better align with specification based on Zed client testing

internal/lsp/server.go
In the spec, items is not optional and so must be an empty list if there are none.
=> lsp: ensure completion items is not null

README.md, docs/cicd.md
Hey Team! :wave: 
This closes #405 and adds a separate CICD doc :smiley: 
I moved the Github one (as-is) from the README and added what we use for Regal in Gitlab CICD (which works for us).
LMK in terms of wording or structure if its okay and if not I will update it :+1: 
Thanks!
=> CICD Docs (Github/Gitlab)

internal/lsp/cache/cache.go
Fixes: https://github.com/StyraInc/regal/issues/750
=> lsp: Return copies of cache maps

cmd/fix.go, e2e/cli_test.go, pkg/fixer/fileprovider/fs.go, pkg/fixer/fixes/useassignmentoperator.go
This uses the same logic to filter files when loading them for fixing as used in linting.
Fixes: https://github.com/StyraInc/regal/issues/761
=> cmd/fix: Filter files loaded for fixing

internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/providers/rulerefs.go, internal/lsp/completions/providers/utils.go, internal/lsp/server.go
Items for packages will now be sorted by 'depth',
show partial package refs where a package is comprised of many sub packages and continuously trigger completions in order to be able to provide up-to-date suggestions based on file changes.
Fixes https://github.com/StyraInc/regal/issues/752
before
https://github.com/StyraInc/regal/assets/1774239/c2ed40e9-5817-4f6e-8c4f-690233c71154
after
https://github.com/StyraInc/regal/assets/1774239/d754f6d3-1353-4442-aca6-6c1324bdc9ba
=> lsp/completions: Implement better package items

internal/lsp/completions/manager.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/rulerefs.go, internal/lsp/completions/providers/rulerefs_test.go, internal/lsp/completions/providers/utils.go
Fixes: https://github.com/StyraInc/regal/issues/753
https://github.com/StyraInc/regal/assets/1774239/fe4684ff-8b8a-4891-ad40-19d12df06937
=> lsp: Provide data ref completions in rules

internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/refs/refs.go
This means that any info at the top level package can still be shown in completion popups.
Fixes: https://github.com/StyraInc/regal/issues/767
The correct fix, where any package in a module should also have the inherited data from the above package if there is a scope subpackages annotation. Currently, modules are parsed and loaded in any order, when they are, their docs are generated and cached in refs. The issue with this is that if a higher level package is loaded later, then the sub packages metadata is not present in time. We'd need to implement some complicated invalidation and reloading logic to achieve this I think, or make it so that ref docs are generated on the fly.
I think this fix is good enough for now.
=> lsp: Show subpackage scope

internal/lsp/completions/manager.go, internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/commonrule.go, internal/lsp/completions/providers/commonrule_test.go, internal/lsp/completions/providers/input.go, internal/lsp/completions/providers/input_test.go, internal/lsp/completions/providers/ruleheadkeyword.go, internal/lsp/completions/providers/ruleheadkeyword_test.go, internal/lsp/completions/providers/rulerefs.go, internal/lsp/completions/providers/utils.go, internal/lsp/types/types.go
These new completion providers will complete keywords and common rule names in a limited number of but common scenarios.
https://github.com/StyraInc/regal/assets/1774239/670db180-b494-4ad8-a225-82aed14feb8d
also
Fixes https://github.com/StyraInc/regal/issues/768
https://github.com/StyraInc/regal/assets/1774239/c92ba19b-19c8-493f-814b-e0f8ab235b77
=> lsp: Rule head & input doc completion improvements

build/capabilities.json, docs/custom-rules.md, internal/compile/compile.go, pkg/builtins/builtins.go, pkg/linter/linter.go
We never used it ourselves, and now that OPA has a built-in for this there's even less need to keep this around. I doubt anyone relied on it, but let's call it out in the next release notes anyway.
=> breaking: Remove `regal.json_pretty` built-in function

README.md, bundle/regal/ast/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/leaked_internal_reference.rego, bundle/regal/rules/bugs/leaked_internal_reference_test.rego, cmd/fix.go, cmd/new.go, docs/rules/bugs/leaked-internal-reference.md, e2e/testdata/violations/most_violations.rego, internal/embeds/templates/builtin/builtin.md.tpl
Help enforce convention of using underscore prefixes for rules and functions to mean internal by flagging references to them from outside the package.
Fixes #94
Also in this PR:
- Fix casing of category in generated rule doc template
- Some more metadata annotations added in the `ast` package
- Fix warning about pointless nil check in fix.go
=> Rule: `leaked-internal-reference`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/internal_entrypoint.rego, bundle/regal/rules/bugs/internal_entrypoint_test.rego, docs/rules/bugs/internal-entrypoint.md, e2e/cli_test.go, internal/embeds/schemas/regal-ast.json
Ensure internal rules aren't used as entrypoints.
Fixes #783
=> Rule: `internal-entrypoint`

README.md, docs/editor-support.md
=> Add info on Zed extension

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/rule_named_if.rego, bundle/regal/rules/bugs/rule_shadows_builtin.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/performance/with_outside_test_context.rego, bundle/regal/rules/style/avoid_get_and_list_prefix.rego, bundle/regal/rules/testing/identically_named_tests.rego, bundle/regal/rules/testing/todo_test.rego, internal/embeds/templates/builtin/builtin.rego.tpl, internal/embeds/templates/custom/custom.rego.tpl
As `name` was rather ambiguous, and only gave the first part of the name, and `ref_to_string` is usable on any ref — let's just have that.
=> Refactor: remove `name` function in favor of `ref_to_string`

internal/lsp/completions/providers/input.go, internal/lsp/completions/providers/input_test.go
This is not consistent with other completions
=> lsp/completions: Drop period from input new text

docs/CONTRIBUTING.md
This is needed as the file is not present on docs.styra.com
=> docs: abs link for do.rq

internal/lsp/server.go
While the specification isn't clear here, Neovim apparently had issues dealing with the empty object response. And since all the other editors seem to handle a null response too, let's just go with that instead.
Fixes #810
=> Return `null` in textDocument/diagnostic handler

bundle/regal/ast/comments.rego, bundle/regal/ast/imports.rego, bundle/regal/main.rego, bundle/regal/main_test.rego, bundle/regal/util/util.rego, docs/CONTRIBUTING.md, e2e/cli_test.go, e2e/testdata/aggregates/ignore_directive/first.rego, e2e/testdata/aggregates/ignore_directive/second.rego, e2e/testdata/aggregates/rules/custom_rules_using_aggregates.rego, internal/embeds/schemas/aggregate.json, internal/lsp/server.go, pkg/linter/linter.go, pkg/report/report.go
Also some light refactoring, but should hopefully not be too distracting.
Fixes #803
=> Support ignore directives in aggregate rules

internal/lsp/completions/providers/builtins.go
When not supplying a text edit, the editor will just insert the text instead. This is a problem when picking up a suggestion from a word started earlier.
Fixes #808 
before 
https://github.com/StyraInc/regal/assets/1774239/14e48d70-09ed-429c-84ac-28b18e12bf92
after
https://github.com/StyraInc/regal/assets/1774239/bb7b72e4-77d1-45e2-9e99-3bcc84bc5d1e
=> lsp: Use text edit for builtins providers

bundle/regal/rules/bugs/impossible_not_test.rego, bundle/regal/rules/bugs/inconsistent_args_test.rego, bundle/regal/rules/imports/circular_import_test.rego, bundle/regal/rules/style/double_negative_test.rego, bundle/regal/rules/style/rule_name_repeats_package_test.rego
Instead of hard-coding doc URLs.
=> Use config.docs.resolve_url consistently

cmd/fix.go, cmd/lint.go
If a config file contains nothing or only comments, then we can roll over it with a more helpful message rather than erroring.
Fixes https://github.com/StyraInc/regal/issues/805
=> lint/fix: roll over empty config

internal/lsp/completions/refs/used.go
When using sync.Once this is not needed.
=> Skip nil check for sync.Once

bundle/regal/config/provided/data.yaml, cmd/lint.go, docs/remote-features.md, internal/lsp/server.go, internal/update/update.go, internal/update/update.rego, internal/update/update_test.go, pkg/config/bundle.go, pkg/config/config.go, pkg/config/global.go, pkg/linter/linter.go, pkg/linter/linter_test.go
This adds functionality to the regal LS and lint commands what will check the current version against the latest release in GH.
In order to keep the number of requests down, the version is cached to disk in the .regal dir. The task runs in another goroutine to keep things fast too.
Config has been updated with a features key, and
REGAL_FEATURES_REMOTE_CHECK_VERSION can also be set to disable to functionality.
Sharing for review, if we think it looks good, I'll add some docs and we can get this in.
Fixes #802
=> Check Regal version at start-up

internal/lsp/completions/manager.go, internal/lsp/completions/manager_test.go
It seems like this is handled client side by some editors, but Zed triggered completion requests inside of comments. While we could have each provider handle this, I think an early exit in the manager already is a better solution, as there's unlikely to be any provider that wants to do suggestions in a comment. If that changes in the future, we'll handle it then.
Fixes #826
=> Don't call completion providers inside of comments

.golangci.yaml, internal/lsp/completions/providers/import.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/ruleheadkeyword.go
Also:
- improve handling of manually invoked suggestions
- don't suggest "import" after "import "
Fixes #830
=> Don't suggest `if` or `contains` following import

internal/lsp/hover/hover.go, internal/lsp/hover/testdata/hover/graphreachable.md, internal/lsp/hover/testdata/hover/indexof.md, internal/lsp/hover/testdata/hover/jsonfilter.md
Since Zed doesn't render markdown tables yet, we'll just present the arguments as a list instead. We could make an exception for Zed, but I think I prefer having this be consistent across editors, and the table format wasn't a requirement here.
Fixes #827
=> Fix markdown content rendering for Zed editor

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/if_object_literal.rego, bundle/regal/rules/bugs/if_object_literal_test.rego, docs/rules/bugs/if-empty-object.md, docs/rules/bugs/if-object-literal.md
This replaces `if-empty-object`, and covers any object literal.
Fixes #822
=> Rule: `if-object-literal`

internal/lsp/completions/providers/ruleheadkeyword.go, internal/lsp/completions/providers/ruleheadkeyword_test.go
This handles the manual trigger case better.
Fixes https://github.com/StyraInc/regal/issues/811
https://github.com/StyraInc/regal/assets/1774239/e6d7bb88-ca6f-4781-aa8b-71d371e0f7a1
=> Better support rule head keyword completions

bundle/regal/ast/ast.rego, bundle/regal/lsp/completion/kind.rego, bundle/regal/lsp/completion/location/location.rego, bundle/regal/lsp/completion/location/location_test.rego, bundle/regal/lsp/completion/main.rego, bundle/regal/lsp/completion/providers/locals/locals.rego, bundle/regal/lsp/completion/providers/locals/locals_test.rego, internal/embeds/schemas/regal-ast.json, internal/lsp/completions/manager.go, internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/input.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/providers/policy_test.go, internal/lsp/completions/providers/utils.go, internal/lsp/rego/rego.go, internal/util/util.go, pkg/linter/linter.go
This is the first provider that is using Rego policy to determine suggestions!
That makes the PR more extensive than normally, but much of this will be reusable for future providers, or even existing ones we may choose to convert.
Fixes #792
=> Completion suggestions for variables in local scope

README.md, internal/lsp/cache/cache.go, internal/lsp/server.go, internal/lsp/types/types.go
Adding functionality to manage the contents of ignored files when formatting documents.
Addresses some issues with ignored files missed in https://github.com/StyraInc/regal/pull/837
=> [lsp] Add support for ignored files in ls formatting

bundle/regal/lsp/completion/location/location.rego, bundle/regal/lsp/completion/providers/locals/locals.rego, bundle/regal/lsp/completion/providers/locals/locals_test.rego
Locals are now suggested anywhere inside of a word boundary, including function a call argument list, map keys/values, arrays, etc.
Added a couple of useful helpers as part of this that we should be able to use for other completion providers too.
Fixes #844
=> Completion of locals in more places

docs/rules/style/prefer-some-in-iteration.md
This is one of the most visited docs pages, so filling in some blanks and adding some links to relevant content.
=> Add more to docs on `prefer-some-in-iteration`

bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/bugs/top_level_iteration_test.rego
=> Fix `top-level-iteration` false positive with ref head vars

bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs_test.rego, internal/lsp/cache/cache.go, internal/lsp/completions/manager.go, internal/lsp/completions/manager_test.go, internal/lsp/completions/providers/used_refs.go, internal/lsp/server.go, internal/lsp/server_test.go, internal/lsp/types/types.go
This also ensures that config is loaded before doing the initial load of the workspace. This means that loaded ignored files do not need to then be immediately dropped.
Also
Fixes https://github.com/StyraInc/regal/issues/832
Fixes https://github.com/StyraInc/regal/issues/843
=> Clear the store when reloading config

bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs_test.rego, internal/lsp/completions/providers/policy_test.go, internal/lsp/lint.go, internal/lsp/server.go, internal/lsp/store.go, internal/lsp/types/internal.go
Running `workspace_rule_refs` on each key change was proving to be too slow, so I've used a mechanism more similar to the old provider where the refs are computed ahead of time when the file contents changes.
=> Precompute refs in file at update

docs/adopters.md
Hello. I've released a GitHub action for Regal integrating with reviewdog.
I would like you to add it to the doc. Thank you!
=> Add reviewdog/action-regal to the adopters file

bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego, internal/lsp/types/types.go
Snippets are special inserts that allow users to enter values and press tab to move to the next location.
https://github.com/StyraInc/regal/assets/510711/04c412a8-1933-4a0d-b041-69059927bd81
https://code.visualstudio.com/docs/editor/userdefinedsnippets
Add snippets for:
- `some v in coll`,
- `some k, v in coll`
- `every v in coll`
- `every k, v in coll`
Got interested in trying this after learning that Zed supports snippets in the latest release. I've tried and confirmed this works in both VS Code and in Zed.
=> Add snippets provider

bundle/regal/lsp/completion/providers/commonrule/commonrule.rego, bundle/regal/lsp/completion/providers/default/default.rego, bundle/regal/lsp/completion/providers/import/import.rego, bundle/regal/lsp/completion/providers/package/package.rego, bundle/regal/lsp/completion/providers/packagename/packagename.rego, bundle/regal/lsp/completion/providers/regov1/regov1.rego, bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego
Also in this PR is a minor fixup, where many `invoke_suggestion` functions have been replaced by `startswith` alone, as `startswith("foo", "")` is true, and doesn't need special handling.
https://github.com/StyraInc/regal/assets/510711/ee7a9e87-ed74-4f93-b3b2-764674efbf46
=> Add snippet suggestion for metadata annotation

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/search.rego, bundle/regal/lsp/completion/location/location_test.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/testing/metasyntactic_variable.rego
Store result of vars found in `walk` into an intermediate object, keyed by rule index and the variable's "context".
The result is quite an improvement:
```
❯ hyperfine --warmup 2 'regal_main lint bundle' 'regal_new lint bundle'
Benchmark 1: regal_main lint bundle
Time (mean ± σ):      4.387 s ±  0.174 s    [User: 31.888 s, System: 0.906 s]
Range (min … max):    4.260 s …  4.820 s    10 runs
Benchmark 2: regal_new lint bundle
Time (mean ± σ):      3.502 s ±  0.120 s    [User: 24.250 s, System: 0.688 s]
Range (min … max):    3.308 s …  3.700 s    10 runs
Summary
regal_new lint bundle ran
1.25 ± 0.07 times faster than regal_main lint bundle
```
=> perf: refactor to avoid excessive `walk`ing

README.md, bundle/regal/ast/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/circular_import.rego, bundle/regal/rules/style/pointless_reassignment.rego, bundle/regal/rules/style/pointless_reassignment_test.rego, docs/rules/style/pointless-reassignment.md, e2e/testdata/violations/most_violations.rego, internal/embeds/templates/builtin/builtin_test.rego.tpl
Also:
- fix the one violation of this rule found in our code :P
- add metadata annotations to a bunch of rules
Fixes #867
=> Rule: `pointless-reassignment`

.github/workflows/scorecard.yml
=> Use OSSF scorecard

.github/workflows/build.yaml, .github/workflows/push-tags.yaml, .github/workflows/update-docs.yaml
Use `read-all` at the top level. Not sure if we actually need anything more somewhere, but I guess this is one way to find out.
=> Fix token permissions

README.md, bundle/regal/ast/search.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/argument_always_wildcard.rego, bundle/regal/rules/bugs/argument_always_wildcard_test.rego, docs/rules/bugs/argument-always-wildcard.md, e2e/testdata/violations/most_violations.rego
I did not expect that I'd have to fix any issues in Regal as a result of this, but that was a rather nice surprise!
Fixes #872
=> Rule: `argument-always-wildcard`

README.md, bundle/regal/ast/search.rego, bundle/regal/config/exclusion.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/var_shadows_builtin.rego, bundle/regal/rules/bugs/var_shadows_builtin_test.rego, docs/rules/bugs/rule-shadows-builtin.md, docs/rules/bugs/var-shadows-builtin.md, e2e/testdata/violations/most_violations.rego
Also in this PR is a slight change of behavior, where variables found in comprehension heads are no longer treated as assigned. This as they _aren't_, and the assignment happens in the comprehension body (or outside the comprehension). This change will uncover a few more `use-some-for-output-vars` issues in policy, which was also fixed as part of this PR.
Fixes #823
=> Rule: `var-shadows-builtin`

bundle/regal/lsp/completion/main.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs_test.rego, internal/lsp/completions/manager.go
Since character position is a `uint`, this would fail when returned to the Go handler.
Also:
- Remove some prints we did to debug performance
- Some cleanups to align rulerefs with other providers
Fixes #887
=> Fix negative number returned by rulerefs provider issue

bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs_test.rego, internal/lsp/completions/refs/defined.go
This one can be quite heavy to process as there are potentially thousands of suggestions if typing in just `data`. Filter out tests from the list, and let the client do the sorting. Also some minor optimizations in Rego code processing.
=> Completions: `rulerefs` optimizations

bundle/regal/ast/ast.rego, bundle/regal/rules/style/prefer_some_in_iteration.rego, bundle/regal/rules/style/prefer_some_in_iteration_test.rego, docs/rules/style/prefer-some-in-iteration.md
This was due to an unfortunate combination of trying to be lenient about `coll[_]` used in the position of a function arg (as that's not *directly* replaceable by `some .. in` **but** not excluding operators like `:=` from functions (where it _should_ be replaced by `some .. in`) **and** many tests for this rule missing to provide the built-in functions as a mocked dependency.
Will need to think some about how to best avoid this to happen again.
Also:
- Replace `ast.policy` in tests with `ast.with_rego_v1`
- Fix docs that used `=` for assignment rather than `:=`
Fixes #901
=> Fix bug causing `prefer-some-in-iteration` not to be reported

bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/style/prefer_snake_case_test.rego
If ref part is missing location, default to location of rule.
Fixes #899
=> Fix some `prefer-snake-case` violations not getting reported

bundle/regal/rules/style/pointless_reassignment.rego, bundle/regal/rules/style/pointless_reassignment_test.rego
Fixes #904
I find the times to be comparable for the regal bundle + a simple violating file.
```sh
regal $ hyperfine --warmup 3 './regal-main lint . --disable-all --enable=pointless-reassignment' './regal-pointless lint .
--disable-all --enable=pointless-reassignment'
Benchmark 1: ./regal-main lint . --disable-all --enable=pointless-reassignment
Time (mean ± σ):      1.171 s ±  0.077 s    [User: 6.188 s, System: 0.192 s]
Range (min … max):    1.108 s …  1.370 s    10 runs
Benchmark 2: ./regal-pointless lint . --disable-all --enable=pointless-reassignment
Time (mean ± σ):     665.8 ms ±  11.3 ms    [User: 2891.0 ms, System: 100.2 ms]
Range (min … max):   644.2 ms … 688.2 ms    10 runs
Summary
./regal-pointless lint . --disable-all --enable=pointless-reassignment ran
1.76 ± 0.12 times …
```
=> rule: Fix pointless reassign issue when using with

docs/language-server.md
This page needed to be updated to support display on docs.styra.com
=> docs: Update language server docs

bundle/regal/ast/keywords.rego, bundle/regal/ast/keywords_test.rego, bundle/regal/ast/search.rego, bundle/regal/ast/search_test.rego, bundle/regal/rules/bugs/constant_condition.rego, bundle/regal/rules/bugs/not_equals_in_loop.rego, bundle/regal/rules/bugs/redundant_existence_check.rego, bundle/regal/rules/bugs/unused_return_value.rego, bundle/regal/rules/performance/with_outside_test_context.rego, internal/lsp/cache/cache.go, internal/lsp/examples/examples.go, internal/lsp/examples/index.json, internal/lsp/hover/hover.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_test.go, internal/lsp/types/internal.go
Where examples to https://docs.styra.com/opa/rego-by-example are available, then show the links to these pages.
https://github.com/StyraInc/regal/assets/1774239/85fc6034-e7db-4b99-8d5a-e85a4f0e48de
=> lsp/hover: Show example links

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/search.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/unused_output_variable.rego, bundle/regal/rules/bugs/unused_output_variable_test.rego, docs/rules/bugs/unused-output-variable.md, e2e/testdata/violations/most_violations.rego, internal/lsp/examples/examples.go
One of the rules I've wanted since the project was started, but not until now would this have been wildly expensive to add. With the recent fixes that allow us to reuse the result of `walk`ing the AST, that's no longer the case. Still, this required quite some time and effort to get right!
NOTE: this rule currently only considers output variables as found in references, i.e. `x` in  `input[x]` and NOT `x` in `some x, _ in input`. While that would be easy to add, I'm not sure if those are really "output variables" or should be considered as such... 🤔 or if we should just have another rules for "unused iteration variable" or something like that. Either way, this is a big step forward!
Fixes #60
=> Rule: `unused-output-variable`

README.md, bundle/regal/rules/bugs/unused_output_variable.rego, bundle/regal/rules/bugs/unused_output_variable_test.rego
Found when testing this against some policies in the wild
=> Ensure `unused-output-variable` actually is output variable

bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/argument_always_wildcard.rego, bundle/regal/rules/bugs/argument_always_wildcard_test.rego, docs/rules/bugs/argument-always-wildcard.md
And have functions starting with "mock_" excepted by default.
Fixes #923
=> Add `except-function-name-pattern` option to `argument-always-wildcard`

README.md, cmd/constants.go, cmd/lint.go, docs/cicd.md, go.mod, go.sum, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
fixes #928 
The output groups violations by files in a testsuite and expresses each violation inside a file as a testcase. The files are sorted so that we have stable output during tests and each failure message contains the documentation link for a failed rule.
I'm not entirely sure whether notices should be part of the output as well. I've skipped them because most other reporters do not output them either.
=> add JUnit output format

internal/lsp/server_test.go
=> lsp: Address bug in multi file test case 

README.md, docs/adopters.md, docs/editor-support.md
Some minor updates to the packaging and editor integration docs, mainly:
- updates to nvim integration options since there are so many
- updates to installation options in readme since there are more package managers with Regal now I've opted to like to packages instead.
=> docs: Update notes on neovim and packaging

bundle/regal/ast/search.rego, bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/style/prefer_snake_case_test.rego, bundle/regal/util/util.rego
=> Include function args in `ast.vars` (and `prefer-snake-case` rule)

bundle/regal/rules/bugs/redundant_existence_check.rego, bundle/regal/rules/bugs/redundant_existence_check_test.rego
=> Extend `redundant-existence-check` to fail redundant ref checks

README.md, bundle/regal/capabilities.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/use_strings_count.rego, bundle/regal/rules/idiomatic/use_strings_count_test.rego, docs/rules/idiomatic/use-strings-count.md, e2e/cli_test.go, e2e/testdata/violations/most_violations.rego
=> Rule: `prefer-strings-count`

internal/lsp/clients/clients.go
Fixes https://github.com/StyraInc/regal/issues/950
=> lsp: Add Neovim as known client identifier

internal/lsp/server.go
When files are ignored, they will have no file contents in the cache, and so completions are impossible. This leads to an error message which is now avoided by just returning an empty list.
Fixes https://github.com/StyraInc/regal/issues/879
=> lsp: Skip textDocument/completion for ignored files

internal/lsp/server.go
Fixes https://github.com/StyraInc/regal/issues/944
https://github.com/user-attachments/assets/20ad421c-749e-4363-9747-6aa755e4d7a4
=> Notify fix failure

cmd/fix.go, e2e/cli_test.go, internal/lsp/server.go, mess.rego, pkg/fixer/fixer.go, pkg/fixer/fixer_test.go
Summary of changes:
- when running the fix cmd, the rego.v1 formatter will be run for files regardless of `rego.v1` being imported.
- when formatting on save in a language server client, the rego.v1 formatter will run, and all fixable violations will also be corrected at save time.
This is implemented by adding the concept of mandatory fixes, where these are run on all files even if there are no violations, before the linter based fixes are run.
LSP on save:
https://github.com/user-attachments/assets/7be3d304-62ab-4b3a-8b71-2364b758033a
Fix cmd:
=> lsp/format,cmd/fix: Apply rego.v1 formatting by default

docs/fixing.md, docs/language-server.md, internal/lsp/format.go, internal/lsp/server.go, internal/lsp/types/types.go, pkg/fixer/fixer.go, pkg/fixer/fixer_test.go, pkg/fixer/fixes/fixes.go
Also:
- Removed the code that would send a response back for formatter options that `opa fmt` can't handle. This was a good idea, but since there isn't any obvious way for users to fix that, it hurts more than it helps
- Removed the fmt fix from the default fixer options as formatting is done anyway by the rego-v1 fixer
Fixes #839
=> Allow using `regal fix` as a formatter

.github/workflows/update-example-index.yaml
Commits to main are protected and rejected.
=> lsp: Update example index with PRs not commits

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/search.rego, bundle/regal/rules/bugs/unused_output_variable.rego, bundle/regal/rules/bugs/var_shadows_builtin.rego, bundle/regal/rules/custom/naming_convention.rego, bundle/regal/rules/idiomatic/use_some_for_output_vars.rego, bundle/regal/rules/idiomatic/use_strings_count.rego, bundle/regal/rules/style/default_over_else.rego, bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/style/unnecessary_some.rego, bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/testing/metasyntactic_variable.rego, mess.rego
- Use `ast.found.refs` instead of `walk` in `use-some-for-output-vars`
- Cheaper `walk` over `else` in `default-over-else` and `use-assignment-operator`
- Remove some unnecessary code in `external-reference`
The plan was also to consolidate `ast.found.symbols` with `ast.found.refs`, but that had disastrous consequences leading to something I think is a bug in OPA. I have demonstrated that to @charlieegan3, but will need to consult the OPA team once they're back from vacation.
=> perf: Walk less

README.md, bundle/regal/ast/search.rego, bundle/regal/main.rego, internal/lsp/eval.go, internal/lsp/eval_test.go, internal/lsp/server.go, internal/lsp/types/types.go
- This is currently limited to VS Code clients, but may be extended to other clients too in the furure, if they can support it on their side.
- Implementation wil recursively look for an `input.json` file and pick the one closest to the file evaluated, down to the level of the workspace root (if any file is found).
=> lsp: Add code lens support for evaluating rules

docs/CONTRIBUTING.md, docs/adopters.md, docs/cicd.md, docs/language-server.md, docs/rules/bugs/rule-shadows-builtin.md, docs/rules/bugs/var-shadows-builtin.md, docs/rules/idiomatic/prefer-set-or-object-rule.md, docs/rules/imports/redundant-alias.md, docs/rules/testing/metasyntactic-variable.md
There were a number of spelling mistakes in the documentation. This PR fixes them as the spelling will soon be enforced in docs.styra.com.
=> docs: Fix spelling mistakes

.gitignore, internal/lsp/eval.go, internal/lsp/eval_test.go, internal/lsp/server.go
And use a reader instead of a string for input as suggested by @charlieegan3
=> LSP: Provide output.json option for non-VS Code clients

internal/lsp/server.go
This means that the keywords for the file have not been computed yet and should be shortly.
There is unlikely much that this message would help with so I have removed it.
The error when processing hover content updates should be enough to establish that the keywords are not being computed, if that ever were to be the case.
=> lsp: No error when missing keywords for hover

internal/lsp/server.go
https://github.com/user-attachments/assets/444f31df-cf8c-4f7a-ae1a-f9dc651441f2
This also notifies the client on errors:
https://github.com/user-attachments/assets/7c553972-9ae8-4d84-a707-68201659e144
=> lsp: Generate correct rule name when during Eval

internal/lsp/eval.go, internal/lsp/eval_test.go, internal/lsp/server.go
=> lsp: include `print` output in eval response

bundle/regal/rules/testing/metasyntactic_variable.rego, bundle/regal/rules/testing/metasyntactic_variable_test.rego
=> Add end location to `metasyntactic-variable` violations

bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/line_length_test.rego
This one was particularly bad before, as only the last character on the line would indicate an issue, making it really hard to see. Now we flag the whole line.
=> Add end location to `line-length` violation

bundle/regal/rules/idiomatic/non_raw_regex_pattern.rego, bundle/regal/rules/idiomatic/non_raw_regex_pattern_test.rego
This was another one that annoyed me recently, so fixed it :)
=> Add end location to `non-raw-regex-pattern` violations

internal/lsp/server.go
In the Regal workspace, the time to find the workspace .rego files went from 70 ms to 7 ms. Nice!
=> lsp/perf: don't traverse .git or .idea dirs

.golangci.yaml, internal/lsp/bundles/bundles.go, internal/lsp/bundles/bundles_test.go, internal/lsp/bundles/cache.go, internal/lsp/bundles/cache_test.go, internal/lsp/eval.go, internal/lsp/server.go
This makes it possible to workspace eval rules based on data.
https://github.com/user-attachments/assets/0b79221b-21bc-4344-8873-a849222c9533
=> lsp: Implement bundle use in workspace Eval

bundle/regal/lsp/completion/providers/inputdotjson/inputdotjson.rego, bundle/regal/lsp/completion/providers/inputdotjson/inputdotjson_test.rego, internal/embeds/schemas/regal-ast.json, internal/io/io.go, internal/lsp/completions/providers/policy.go, internal/lsp/eval.go, internal/lsp/eval_test.go, internal/lsp/server.go
This provider suggests completions based on the nested attributes found in the `input.json` file, if such a file exists.
=> Add `input.json` completion provider

README.md, bundle/regal/ast/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/result.rego, bundle/regal/rules/bugs/sprintf_argument_mismatch.rego, bundle/regal/rules/bugs/sprintf_argument_mismatch_test.rego, bundle/regal/util/util.rego, docs/rules/bugs/sprintf-arguments-mismatch.md, e2e/testdata/violations/most_violations.rego
=> Rule: `sprintf-arguments-mismatch`

bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/result.rego
Some special case we previously needed to handle no longer apply since we moved to the roast format. Also fixed a TODO asking to move over to `strings.count` when released, and that is now :)
=> Remove some code made redundant by roast

pkg/reporter/reporter.go
Fixes https://github.com/StyraInc/regal/issues/1014
This is the most simple implementation I could think of for this one!
```
…/regal regal-fix-prompt ➜ go run main.go lint package.rego
Rule:           opa-fmt
Description:    File should be formatted with `opa fmt`
Category:       style
Location:       package.rego:1:1
Text:           package p
Documentation:  https://docs.styra.com/regal/rules/style/opa-fmt
Rule:           use-rego-v1
Description:    Use `import rego.v1`
Category:       imports
Location:       package.rego:1:1
Text:           package p
Documentation:  https://docs.styra.com/regal/rules/imports/use-rego-v1
Rule:           use-assignment-operator
Description:    Prefer := over = for assignment
Category:       style
Location:       package.rego:3:3
Text:           x = 5 …
```
=> lint: Advertise regal fix command

bundle/regal/ast/imports.rego, internal/lsp/bundles/cache.go, internal/lsp/lint.go, internal/lsp/server.go, pkg/config/filter.go
Fixes #1017
Which turned into a bug hunt..
Also fixed:
- ast.resolved_imports crashing on duplicate identifiers
- node_modules not excluded from fs walk, as @srenatus reported
Opening the OPA repo now works as expected. The 500+ linter issues notwithstanding.
=> fix: don't serialize error location using roast but encoding/json

bundle/regal/rules/style/rule_name_repeats_package.rego, bundle/regal/rules/style/rule_name_repeats_package_test.rego
Also made some adjustments to make the rule follow more modern conventions, and more importantly, to report end locations.
Fixes #1015
=> fix: respect ref head rules in `rule-name-repeats-package`

bundle/regal/rules/testing/file-missing-test-suffix/file_missing_test_suffix.rego, bundle/regal/rules/testing/file-missing-test-suffix/file_missing_test_suffix_test.rego, bundle/regal/rules/testing/test-outside-test-package/test_outside_test_package.rego, bundle/regal/rules/testing/test-outside-test-package/test_outside_test_package_test.rego
This is a Styra DAS convention, and while I'd say `*_test` is preferred, I think it's OK to allow this single exception.
Also update this rule to report end location.
=> Allow tests to be in 'test' package

internal/lsp/server.go
Fixes https://github.com/StyraInc/regal/issues/1008
Now look like this:
=> lsp: Clean workspace root from eval errors

internal/embeds/schemas/regal-ast.json
These don't matter to the type checker, so wasn't caught before.
=> Some schema fixes

.github/workflows/build.yaml, .golangci.yaml, bundle/regal/lsp/completion/location/location.rego, internal/lsp/diff.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_test.go, internal/lsp/store.go, internal/lsp/store_test.go, internal/parse/parse.go
This was caused by us no longer passing JSONOPtions to the parser that parsed workspace files, and so when passed to the store, the locations went missing in the roundtrip the store would do before persisting the data.
The store is now created with the roundtrip option disabled, and we'll make sure ourselves that the data is serialized correctly, and in the case of modules — serialized to RoAST. This should mean less data stored in `data.workspace.parsed` and lower latency for policies that rely on that store, which is nice!
Also:
- bump golangci-lint and address some new issues
=> Fix missing locals completions

.github/workflows/build.yaml, .github/workflows/codeql.yml, .github/workflows/scorecard.yml, .github/workflows/update-docs.yaml, .github/workflows/update-example-index.yaml, .goreleaser.yaml, .vscode/settings.json, .vscode/tasks.json, build/do.rq, build/dprint.json, bundle/regal/config/provided/data.yaml, e2e/testdata/configs/custom_naming_convention.yaml
=> build: check yaml and json formatting with dprint

cmd/fix.go, e2e/cli_test.go, pkg/config/config.go
Now the .regal dir will be used as the root, or any bundles configured under it or manually set in the file, unless it does not exist. If this is the case, then the roots will be used as the args to the fix cmd.
=> fix: Update root detection

cmd/fix.go, e2e/cli_test.go, internal/lsp/server.go, internal/util/util.go
This matches the behaviour of the fix cmd
=> lsp: Clear old directories when renaming

bundle/regal/rules/idiomatic/directory-package-mismatch/directory_package_mismatch.rego, bundle/regal/rules/idiomatic/directory-package-mismatch/directory_package_mismatch_test.rego, e2e/cli_test.go, internal/embeds/schemas/regal-ast.json, internal/parse/parse.go, pkg/fixer/fixer_test.go, pkg/linter/linter_test.go
Since we need path components to determine the directory, use an absolute path in the policy rather than a relative one.
=> Fix `directory-package-mismatch` issue when lint called with "."

cmd/fix.go, e2e/cli_test.go
This also skips the unchanged check when working within a git repo.
=> fix: Require use of --force to fix without git

cmd/languageserver.go, internal/lsp/server.go, internal/lsp/server_template_test.go, pkg/config/config.go
Empty files will be created with a template content instead of being an error.
New empty files will be immediately updated with the template content.
Some client operations will not trigger the new file event, so in such cases, a save might be required to trigger the template update.
Fixes https://github.com/StyraInc/regal/issues/1048
https://github.com/user-attachments/assets/ebcf7699-bb96-43d6-ae21-f02a883f46e0
=> lsp: Template new empty files & template on format

internal/lsp/server.go, internal/lsp/server_test.go
=> Fix LSP formatting that broke in v0.26.0

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/main/main.rego, bundle/regal/rules/bugs/inconsistent-args/inconsistent_args.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable_test.rego, bundle/regal/rules/idiomatic/use-strings-count/use_strings_count.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports_test.rego, bundle/regal/rules/style/default-over-not/default_over_not.rego, bundle/regal/rules/style/prefer-some-in-iteration/prefer_some_in_iteration.rego, bundle/regal/rules/style/rule-length/rule_length_test.rego, bundle/regal/rules/style/unnecessary-some/unnecessary_some.rego, bundle/regal/rules/style/use-assignment-operator/use_assignment_operator.rego, bundle/regal/rules/testing/metasyntactic-variable/metasyntactic_variable.rego, bundle/regal/rules/testing/test-outside-test-package/test_outside_test_package_test.rego, bundle/regal/util/util_test.rego
I started looking into increasing the test coverage the other day, and wow, there really turned out to be some bugs under those stones!
While there are a few silly additions here just for coverage, many of the changes made here uncovered issues that when fixed had Regal report many issues in our own code! So this was definitely a worthwhile endevour.
Will continue this work for sure, but to avoid it becoming a monster, and to leave it in a good state, I'll follow up with more PRs later.
=> Increase test coverage

bundle/regal/lsp/completion/providers/booleans/booleans.rego, bundle/regal/lsp/completion/providers/booleans/booleans_test.rego
Fixes https://github.com/StyraInc/regal/issues/1010
=> lsp/completions: add boolean provider

internal/lsp/inlayhint_test.go
Otherwise this test can fail like this
```
2024/09/05 13:33:37 jsonrpc2: protocol error: io: read/write on closed pipe
--- FAIL: TestGetInlayHintsAstTerms (0.00s)
inlayhint_test.go:71: Expected 1 inlay hints, got 0
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 14 [running]:
testing.tRunner.func1.2({0x105567cc0, 0x14006a02be8})
/Users/runner/hostedtoolcache/go/1.22.5/arm64/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/Users/runner/hostedtoolcache/go/1.22.5/arm64/src/testing/testing.go:1634 +0x33c
panic({0x105567cc0?, 0x14006a02be8?})
/Users/runner/hostedtoolcache/go/1.22.5/arm64/src/runtime/panic.go:770 +0x124
github.com/styrainc/regal/internal/lsp.TestGetInlayHintsAstTerms(0x14000c71 …
```
=> tests: Fatal error when no inlay hints are found

cmd/fix.go
Fixes https://github.com/StyraInc/regal/issues/1063
=> cmd/fix: Only require git when dry-run unset

.goreleaser.yaml, build/do.rq, e2e/cli_test.go, internal/mode/standalone.go, internal/mode/standalone_flag.go, pkg/reporter/reporter.go
Projects using Regal via its Go module would no longer output the `regal fix --help` hint.
=> build: introduce regal_standalone build flag, use for lint's "fix" hint

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/rules/bugs/deprecated-builtin/deprecated_builtin.rego, bundle/regal/rules/bugs/leaked-internal-reference/leaked_internal_reference.rego, bundle/regal/rules/custom/forbidden-function-call/forbidden_function_call.rego, bundle/regal/rules/idiomatic/non-raw-regex-pattern/non_raw_regex_pattern.rego, bundle/regal/rules/imports/circular-import/circular_import.rego, bundle/regal/rules/style/yoda-condition/yoda_condition.rego, bundle/regal/rules/testing/dubious-print-sprintf/dubious_print_sprintf.rego, bundle/regal/rules/testing/print-or-trace-call/print_or_trace_call.rego, bundle/regal/util/util.rego
This held a copy of `ast.found.refs` + imported refs Which was quite redundant. Rewrote all consumers to go for `ast.found.refs` directly, and imports where needed.
Also added `util.intersects` for a common pattern used in these rules.
=> Remove `ast.all_refs`

cmd/new.go, docs/custom-rules.md, internal/embeds/templates/custom/custom_test.rego.tpl, pkg/config/config.go, pkg/config/config_test.go
Update docs to reflect use of roast format, and much more.
- Add .regal/rules as a root when exists
- Make sure `regal new rule` creates directories matching package path
- Fix missing comma and use tabs in test template leading to Regal flagging the custom test as unformatted
- Replace `ast.name` call with `ast.ref_to_string` in one of the examples. Thanks @drewcorlin1 for pointing that out!
Fixes #1003
=> Ensure custom rules docs are up to date

internal/lsp/server.go
This PR makes changes to where the contents of files come from when being moved. Previously, preference was given to the contents on disk. This turned out to be incorrect as the files on disk are often empty until saved.
I found that I was able to replicate one of the empty module problems by:
- creating a file, and not saving it
- creating a dir
- editing the file
- moving the file into the dir while the file on disk is empty
before
https://github.com/user-attachments/assets/7bbb6442-5dc1-4897-81e2-8f2356d2e7c4
after
https://github.com/user-attachments/assets/c5a5ac35-1867-4214-8ad2-3cb9aa75fcd6
=> lsp: Address empty module issues on rename

internal/lsp/server.go
Previously, we would only send empty diagnostics when the file had had diagnostics before, this did not include parse errors so when a file still had parse errors, it'd remain in client long after the server had cleared it.
This PR also makes some changes to process the cases of clearing files outside the `l.diagnosticRequestFile` loop as it was tricky to handle the types of empty updates in there.
before
https://github.com/user-attachments/assets/b5430a38-5686-44fb-bde7-422c80d915a5
after
https://github.com/user-attachments/assets/67838d79-1818-4fbe-a3da-782c6583b787
=> lsp: Always send empty diagnostics when deleted

internal/lsp/server.go, internal/lsp/uri/uri.go, internal/lsp/uri/uri_test.go
Spaces must be encoded as %20. This case causing the state worker to reload contents from disk as it appeared a file did not exist in the cache.
=> lsp: Correct Path to URI encoding

pkg/reporter/reporter.go
This list is based on map keys and was causing flakes due to the items not always being in the same order.
=> e2e: Sort output from fix hint

internal/io/io.go, pkg/config/config.go
We previously traversed the path downwards, so if we had `foo/bar/.manifest` and `foo/bar/baz` was provided, we would not find `foo/bar` as a root. Now search for manifests from the root.
Fixes #1077
=> Fix issue where .manifest files didn't register as roots

e2e/cli_test.go, e2e/testdata/bugs/issue_1082.rego, go.mod, go.sum
This also ups the OPA version used by roast to v0.68.0, aligned with Regal.
Fixes #1082
=> Bump roast to v0.2.0 to ensure annotations encodes correctly

bundle/regal/ast/comments.rego, bundle/regal/rules/style/detached-metadata/detached_metadata_test.rego
A "comment block" should only count comments in sequence when they are on the same column.
Fixes #1086
=> Fix: block comments should take column into account

docs/rules/idiomatic/directory-package-mismatch.md, internal/lsp/server.go, internal/lsp/server_template_test.go, internal/lsp/types/types.go, internal/util/util.go, internal/util/util_test.go, pkg/fixer/fixes/directorypackagemismatch.go
Fixes https://github.com/StyraInc/regal/issues/1061
https://github.com/user-attachments/assets/a6589d87-6885-459d-a0a4-28e5821453a7
I have added some tests for the templating, I was going to determine the desired name for the file in that function too but in the end it was easier to keep the renaming logic separate. Even if this is more verbose, can be revisited tomorrow if we want to do some tidying here. Posting now just to allow testing until I'm next back working on this.
=> lsp: Rename on template

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/search.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/impossible-not/impossible_not.rego, bundle/regal/rules/bugs/invalid-metadata-attribute/invalid_metadata_attribute.rego, bundle/regal/rules/idiomatic/prefer-set-or-object-rule/prefer_set_or_object_rule.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego, bundle/regal/rules/style/comprehension-term-assignment/comprehension_term_assignment.rego, bundle/regal/rules/style/comprehension-term-assignment/comprehension_term_assignment_test.rego, bundle/regal/rules/style/pointless-reassignment/pointless_reassignment.rego, cmd/new.go, docs/rules/style/comprehension-term-assignment.md, e2e/testdata/violations/most_violations.rego
Flag redundant assignment of simple values that could be used directly as the comprehension term (or key/value).
Fixes #1073
=> Rule: `comprehension-term-assignment`

internal/lsp/inlayhint_test.go
Since the rest of the test is making use of the hints, we need to stop execution if the length check fails.
=> lsp: Make length check of inlay hints fatal

.github/workflows/build.yaml, internal/lsp/config/watcher.go, internal/lsp/config/watcher_test.go, internal/lsp/server.go, internal/lsp/server_template_test.go, internal/lsp/server_test.go
There were three areas/issues:
- An error var in a config watcher test was accessed in two places
- server loaded config was accessed in a number of places without locking
- a panic caused by early closing of the net.Pipe in the lsp server tests.
This PR addresses these issues and runs the race check on PRs during the Linux build.
Fixes https://github.com/StyraInc/regal/issues/1099
=> Address races in test cases

bundle/regal/lsp/codelens/codelens.rego, bundle/regal/lsp/codelens/codelens_test.rego, bundle/regal/lsp/util/location/location.rego, internal/lsp/rego/rego.go, internal/lsp/rego/rego_test.go, internal/lsp/server.go, pkg/builtins/builtins.go
Following the excellent work on debugger support by @johanfylling, this PR introduces a code lens for debugging, which triggers a command that simply returns a launch configuration where the package or rule clicked is set as the entrypoint.
The code lens provider is now also rewritten in Rego.
=> Add `Debug` Code Lens

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/rule_head_locations_test.rego, bundle/regal/lsp/completion/ref_names.rego, bundle/regal/lsp/completion/ref_names_test.rego, internal/lsp/completions/providers/policy.go, internal/lsp/eval.go, internal/lsp/server.go, pkg/linter/linter.go
While I started looking into #1104 I encountered some cases where `ast.ref_to_string`, and it's `static` counterpart would return wrong representations. We already had a bit of a homegrown format, which was convenient for some things, but would also leak out in places where it shouldn't be. Now use the same format as OPA for representing refs as strings.
Also added the query in error messages where we fail to prepare or eval in a couple of places, as the lack of those made debugging this issue much harder than it had to be.
=> More stringent ast.ref_to_string

bundle/regal/rules/bugs/sprintf-arguments-mismatch/sprintf_arguments_mismatch.rego, bundle/regal/rules/bugs/sprintf-arguments-mismatch/sprintf_arguments_mismatch_test.rego
While this rule likely never will catch all violations, as some are just too expensive to find for something very unlikely — it should never report false positives.
Fixes #1104
=> fix: `sprintf-arguments-mismatch`false positive when var used as format

docs/editor-support.md
I wrote a brief explanation about Neovim's DAP support.
=> docs/editor: write about nvim-dap

internal/lsp/completions/manager.go, internal/lsp/completions/manager_test.go, internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/builtins_test.go, internal/lsp/completions/providers/input.go, internal/lsp/completions/providers/input_test.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/providers/policy_test.go, internal/lsp/completions/providers/rulehead.go, internal/lsp/completions/providers/rulehead_test.go, internal/lsp/completions/providers/ruleheadkeyword.go, internal/lsp/completions/providers/ruleheadkeyword_test.go, internal/lsp/rego/builtins.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_test.go
This PR is intended to address two issues with the test suite that happen when running tests concurrently:
TestLanguageServerSingleFile fails sometimes as the server logs an error when the context has been cancelled, and it's a panic when logging to t, after the test is over.
https://github.com/StyraInc/regal/actions/runs/10875806798/job/30174833322
TestGetInlayHintsAstTerms will fail when TestLanguageServerSingleFile is running sometimes as [TestLanguageServerSingleFile updates the contents of the map](https://github.com/StyraInc/regal/blob/7bf76856cc72a2d72a1834e5e067c64675c7fc8b/internal/lsp/server.go#L390) while TestGetInlayHintsAstTerms is iterating over it.
https://github.com/StyraInc/regal/actions/runs/10875806798/job/30184826633
Coincidentally, both these issues happened on a …
=> lsp: Address test concurrency issues

internal/lsp/server_test.go
The previous implementation would not exit after the timeout leading to test timeouts such as:
https://github.com/StyraInc/regal/actions/runs/10940194447/job/30372056611
Which we are trying to avoid...
The test goroutine was in /Users/runner/work/regal/regal/internal/lsp/server_test.go:435, so have targeted this part of the test.
=> tests: Minor test wait improvement

bundle/regal/config/config.rego, bundle/regal/main/main_test.rego, bundle/regal/rules/idiomatic/directory-package-mismatch/directory_package_mismatch.rego, bundle/regal/rules/testing/file-missing-test-suffix/file_missing_test_suffix.rego, bundle/regal/util/util.rego, pkg/config/filter.go, pkg/rules/rules.go
And print notices for rules ignored as a result of no filename being known.
```
➜ cat lab/p.rego | go run main.go lint -
1 file linted. No violations found. 2 rules skipped:
- directory-package-mismatch: disabled when filename is unknown
- file-missing-test-suffix: disabled when filename is unknown
```
Fixes #1118
=> Allow `regal lint -` to lint from stdin

cmd/fix.go, e2e/cli_test.go, pkg/fixer/fileprovider/inmem.go, pkg/fixer/fileprovider/inmem_test.go, pkg/fixer/fixer.go, pkg/fixer/report.go, pkg/fixer/reporter.go, pkg/fixer/reporter_test.go
Fixes https://github.com/StyraInc/regal/issues/1119
=> fixer: Address rename conflicts with explanation

cmd/fix.go, e2e/cli_test.go, pkg/fixer/fixer.go, pkg/fixer/rename.go, pkg/fixer/rename_test.go
This PR adds a new flag to the fix command, `--on-conflict`. This flag can be used to specify the behavior of the fix command when a file's new name conflicts with an existing file or another file's fixed name.
Setting --on-conflict to "rename" will cause the fix command to rename the file to a different name at the target location. The new name will be generated by appending a number to the end of the file name.
=> fixer: add --on-conflict flag to support renaming

internal/lsp/server_test.go
After seeing https://github.com/StyraInc/regal/actions/runs/10996729351/job/30530568473, I had another look at this one. I spotted the built-in is incorrect here, I think? Not thinking this is the main fix, but this should log to make it clear when we see the next failure.
=> tests: Address incorrect built-in function check

internal/ast/rule.go, internal/ast/rule_test.go, internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/builtins_test.go, internal/lsp/completions/providers/options.go, internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/providers/rulehead_test.go, internal/lsp/completions/refs/defined.go, internal/lsp/completions/refs/defined_test.go, internal/lsp/documentsymbol.go, internal/lsp/documentsymbol_test.go, internal/lsp/hover/hover.go, internal/lsp/inlayhint.go, internal/lsp/inlayhint_test.go, internal/lsp/lint.go, internal/lsp/rego/builtins.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_test.go
Built ins must now be provided by the caller.
We have been having a number of issues with race conditions in tests where the shared list of builtins was required to be in a different state in different tests. Namely, the single file language server test that updated the config to use a different caps list, and inlay hints which was also based on this data.
After some consideration, it appears to make sense that the built ins, being related to the loaded caps, should be provided when required, rather than being fetched from the global state. This means that the code requiring builtins can continue to operate while needing know knowledge of what the builtins list should be, as that is now a concern of the caller.
I have added field on the server to store the state of builtins for different …
=> tests: Remove global builtins state

bundle/bundle.go, cmd/lint.go, cmd/test.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/refs/used.go, internal/lsp/rego/rego.go, internal/lsp/server.go, pkg/linter/linter.go
Previously, loading of the bundle happened many times, each time it takes around 20ms. This improves the performance of the language server by loading the bundle once and reusing it since the bundle is never changed once a binary is running.
before
https://github.com/user-attachments/assets/7a23a92c-e489-436d-96c7-e67b9ce9b91d
after
https://github.com/user-attachments/assets/ca1d2c5f-b043-44b0-abd1-aea3a4909ecf
=> bundle: Load bundle once

pkg/linter/linter.go, pkg/linter/linter_test.go
This change in intended to be a step to being able to externally store and manage aggregate data from the linter to caching between runs.
This PR only adds the basic functionality for such a feature.
Related https://github.com/StyraInc/regal/issues/1133
=> linter: support single file aggregate data collection and parameterised aggregate data in Lint()

bundle/regal/rules/style/detached-metadata/detached_metadata.rego, bundle/regal/rules/style/detached-metadata/detached_metadata_test.rego
Build a more robust system for determining this regardless of scope. Lean in on the OPA parser failing anyway when scope is invalid.
Fixes #1138
=> Fix `detached-metadata` issues

pkg/version/version.go
I found that `regal version` subcommand does not show commit hash.
```bash
❯ ./regal version             
Version:    0.27.0
Go Version: go1.22.5
Platform:   linux/amd64
Commit:     unknown
Timestamp:  2024-09-17T15:00:44Z
Hostname:   github.actions.local
```
This is because the build time information is passed to `pkg/version.Commit` variable, but it does not exist there.
https://github.com/StyraInc/regal/blob/e205cd9e4a9f27c52d7d0a6e7ac250c12113def8/.goreleaser.yaml#L24
I fixed this problem by renaming `pkg/version.Vcs` to `pkg/version.Commit`.
```bash
❯ go build -ldflags='-X github.com/styrainc/regal/pkg/version.Commit=my-commit'
❯ ./regal version
Version:    unknown
Go Version: go1.22.7
Platform:   linux/amd64
Commit:     my-commit
Timestamp:  unknown
Hostname:   unknown
```
=> fix: fix var name for commit hash used for `version` subcommand

internal/lsp/hover/hover.go
> Incorrect conversion of an unsigned 64-bit integer from to a lower bit size type uint without an upper bound check.
=> internal/lsp/hover: "fix" codeql finding

e2e/cli_test.go, internal/capabilities/capabilities.go, internal/compile/compile.go, internal/embeds/embeds.go, internal/explorer/stages.go, internal/lsp/opa/tokens/tokens.go, internal/lsp/server_test.go, internal/mode/standalone.go, internal/util/util.go, pkg/fixer/reporter.go
Would be good to know why golangci-lint fails to report these, as some were fairly obvious. But oh well!
And
=> Fix some minor issues reported by IntelliJ

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/var-shadows-builtin/var_shadows_builtin_test.rego
=> Exclude `print` from "function return value in args" check

cmd/languageserver.go, docs/rules/imports/prefer-package-imports.md, go.mod, internal/lsp/cache/cache.go, internal/lsp/cache/cache_test.go, internal/lsp/completions/manager.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/providers/policy_test.go, internal/lsp/eval_test.go, internal/lsp/lint.go, internal/lsp/lint_test.go, internal/lsp/race_off.go, internal/lsp/race_on.go, internal/lsp/server.go, internal/lsp/server_aggregates_test.go, internal/lsp/server_builtins_test.go, internal/lsp/server_config_test.go, internal/lsp/server_formatting_test.go, internal/lsp/server_multi_file_test.go, internal/lsp/server_rename_test.go, internal/lsp/server_single_file_test.go, internal/lsp/server_template_test.go, internal/lsp/server_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go, pkg/report/report.go
Fixes to https://github.com/StyraInc/regal/issues/1133
This PR is a large refactoring of the language server diagnostics loops. Changes:
- when the contents of a file with aggregate violations changes, this no longer triggers a full workspace lint
- when the contents of any file changes, the aggregate rule state is now cached on the server and the results of this update, in addition to the full global state, is used to perform a linting run of all files but only linting for aggregate rules.
- new tests have been added to cover this functionality and the underlying functionality which these server changes depend on in the linter.
- server tests moved to new files since they are very long.
- increased timeouts for go test when running in go test -race …
=> lsp: Update LSP linting to run incrementally after file change

internal/lsp/server.go, internal/lsp/server_formatting_test.go, internal/lsp/server_template_test.go
This also disables templating for files in the root.
Fixes https://github.com/StyraInc/regal/issues/1164
Related to https://github.com/StyraInc/regal/issues/1141, but this needs more work
Sorry for the low res video... 
https://github.com/user-attachments/assets/18c95fce-4981-4e8b-a1c0-45418aac9573
=> lsp/templating: gracefully handle unknown root

internal/lsp/server_aggregates_test.go, internal/lsp/server_multi_file_test.go, internal/lsp/server_test.go
This protects against logging in tests after they finish which I have seen crop up 2x this week.
=> Use test logger for client handler

internal/lsp/server.go, internal/lsp/types/types.go
Refs: #1175 
This pull request adds two options to LSP's initialization options.
- `enableDebugCodelens`: to enable/disable debug codelens
- `evalCodelensDisplayInline`: to select result output methods of evaluate codelens
In the current implementation, `Debug` codelens feature requires the client is VSCode.
However like I showed in #1175, it is possible to use this feature if the client implements specific handlers for the Regal's `regal/startDebugging` request.
In this pull request, I propose to add the options to control the Regal's behavior about codelenses.
This change will be breaking to vscode-opa, but just adding two parameters to https://github.com/open-policy-agent/vscode-opa/blob/f49ab2ec0e72516749f7416daea4a246ddfe7b6b/src/ls/clients/regal.ts#L203.
I'll send a pull request to …
=> feat(lsp): add initialization options about codelenses

.github/workflows/build.yaml, .github/workflows/push-tags.yaml, .github/workflows/update-example-index.yaml, build/do.rq, build/dprint.json, build/package-lock.json, build/package.json
Based on some of the suggestions in https://github.com/StyraInc/regal/actions/runs/11218155200/artifacts/2024479406
=> Scorecard updates

pkg/linter/linter.go
This allows the linter to more gracefully exit from context cancellation.
As seen in
https://github.com/StyraInc/regal/actions/runs/11233013451/job/31225814604, this can cause test cases to timeout after there are errors.
My understanding the error being attempted to be sent to the channel is a context cancellation error.
=> linter: use a buffered error channel

docs/adopters.md
I work for [UNIwise](https://uniwise.eu/) and we use Regal for all our OPA policies, and would like to show our support for it here.
=> Add UNIwise company to adopters.md

.github/workflows/update-caps.yml
So now updating the example index and updating caps should no longer try to use the same PR.
=> workflow: use different branch (and also PR) for caps updates

docs/language-server.md
[nvim-dap-rego now provides lsp handlers for both of the evaluation and debug code lenses](https://github.com/rinx/nvim-dap-rego/blob/main/README.md#lsp-handlers).
I wrote about it in the docs/language-server.md here.
=> docs: write about evaluation code lens support in neovim

bundle/regal/rules/style/prefer-snake-case/prefer_snake_case.rego, bundle/regal/rules/style/prefer-snake-case/prefer_snake_case_test.rego, docs/rules/style/prefer-snake-case.md
Previously, only rules and vars were checked.
Fixes #1205
=> Make `prefer-snake-case` check package name

bundle/regal/config/exclusion.rego, bundle/regal/config/exclusion_test.rego, internal/lsp/lint_test.go
This is not an ideal solution, as we should not be sending URLs to the linter in the first place. But as fixing that is a much broader issue, we'll have to settle for a hack in the meantime.
Fixes #1204
=> Handle `file://` URLs in exclusion policy

pkg/config/config.go, pkg/config/config_test.go
As reported in #1202 (thanks @geirs73!)
Note however that this does not address the Windows path loading issue from the same issue though.
=> Improve error messages for incorrect capabilities version

internal/lsp/bundles/cache.go
This has the benefit of not having to stat all files along the way.
Ideally, we'd be able to build the data bundle in the same function more efficiently too, but that's a more complex operation.
=> Use filepath.WalkDir instead of filepath.Walk

pkg/reporter/reporter.go, pkg/reporter/testdata/pretty/reporter-long-text.txt, pkg/reporter/testdata/pretty/reporter.txt
This fixes https://github.com/StyraInc/regal/issues/1211 by supporting the NO_COLOR environment variable and checking if the output is a tty before using color.
The color.NoColor global is used as described here: https://github.com/fatih/color?tab=readme-ov-file#disableenable-color
=> lint/rpt: Handle no-color ttys

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/search.rego, bundle/regal/config/provided/data.yaml, bundle/regal/lsp/completion/providers/import/import.rego, bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/result/result.rego, bundle/regal/rules/bugs/sprintf-arguments-mismatch/sprintf_arguments_mismatch.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable.rego, bundle/regal/rules/idiomatic/custom-has-key-construct/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom-in-construct/custom_in_construct.rego, bundle/regal/rules/idiomatic/equals-pattern-matching/equals_pattern_matching.rego, bundle/regal/rules/performance/defer-assignment/defer_assignment.rego, bundle/regal/rules/performance/defer-assignment/defer_assignment_test.rego, bundle/regal/rules/style/default-over-else/default_over_else.rego, docs/rules/performance/defer-assignment.md, e2e/testdata/violations/most_violations.rego
Finally a new rule in the `performance` category! And this is quite a fun one. I was curious to see how many violations this would find in the Regal codebase, if any. It did find a few, and good ones to fix!
In order to keep it simple, this first implementation is perhaps a bit too cautious about what it considers deferrable. Check the implementation to see what exactly, but pretty much only assignments where the next line is a not an assignment, a potential loop, or something else that *might* make deferring the assignment undesirable.
Fixes #1147
=> Rule: `defer-assignment`

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/search.rego, bundle/regal/config/provided/data.yaml, bundle/regal/lsp/completion/location/location_test.rego, bundle/regal/rules/bugs/argument-always-wildcard/argument_always_wildcard.rego, bundle/regal/rules/bugs/inconsistent-args/inconsistent_args.rego, bundle/regal/rules/bugs/not-equals-in-loop/not_equals_in_loop.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable.rego, bundle/regal/rules/custom/naming-convention/naming_convention_test.rego, bundle/regal/rules/idiomatic/custom-has-key-construct/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom-in-construct/custom_in_construct.rego, bundle/regal/rules/idiomatic/equals-pattern-matching/equals_pattern_matching.rego, bundle/regal/rules/idiomatic/prefer-set-or-object-rule/prefer_set_or_object_rule.rego, bundle/regal/rules/idiomatic/use-in-operator/use_in_operator.rego, bundle/regal/rules/idiomatic/use-some-for-output-vars/use_some_for_output_vars.rego, bundle/regal/rules/performance/walk-no-path/walk_no_path.rego, bundle/regal/rules/performance/walk-no-path/walk_no_path_test.rego, bundle/regal/rules/style/external-reference/external_reference.rego, docs/rules/performance/walk-no-path.md, e2e/testdata/violations/most_violations.rego, internal/update/update.rego
Suggest replacing the path variable with a wildcard where possible, as the walk built-in is able to optimize such calls. More info in the docs included in the PR.
Also:
- Add `ast.is_wildcard` convenience function and use it consistently
Fixes #1154
=> Rule: `walk-no-path`

bundle/regal/rules/bugs/leaked-internal-reference/leaked_internal_reference.rego, bundle/regal/rules/bugs/leaked-internal-reference/leaked_internal_reference_test.rego, docs/rules/bugs/leaked-internal-reference.md
Option added to turn back on if needed
=> rule: Disable leaked_internal_reference for test files

bundle/regal/config/config.rego, bundle/regal/config/exclusion.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/main/main.rego, bundle/regal/main/main_test.rego, internal/lsp/lint.go, internal/lsp/lint_test.go, internal/lsp/server.go, pkg/config/filter.go, pkg/linter/linter.go, pkg/linter/linter_test.go
In the LS linting, pattern/* would not work when it would in the CLI. This was related to how abs paths were resolved and is fundamentally caused by and issue with URIs being used as file names in the linter.
Now, all files from the LS lint are ignored based on their path with the workspace root URI trimmed.
https://github.com/user-attachments/assets/30118754-61d5-4265-b68b-9fac99c204d9
=> lsp: Fix inconsistent processing of ignores

internal/lsp/server.go
This had been disabled by mistake, now files in the project root will still be formatted using the configured formatter but will still not be templated.
=> lsp: format root directory files

.github/workflows/build.yaml
Should be exactly like before, but without the security scanner complaining.
=> workflows/build: 'npm install' from subdir

.github/workflows/build.yaml
That subcommand respects package-lock.json.
=> workflows/build: use 'npm ci'

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/rule-assigns-default/rule_assigns_default.rego, bundle/regal/rules/bugs/rule-assigns-default/rule_assigns_default_test.rego, docs/rules/bugs/rule-assigns-default.md, e2e/cli_test.go, e2e/testdata/violations/most_violations.rego, internal/io/io.go, internal/lsp/diff.go, internal/lsp/documentsymbol.go, internal/lsp/foldingrange.go, internal/lsp/hover/hover.go, internal/lsp/lint.go, internal/lsp/rego/rego.go, internal/lsp/server.go
Flags rules where the default value is used as the assigned value in any other incremental definition.
Fixes #1018
(unrelated changes mostly adding some ignore directives in Go code is from me having update golangci-lint which led to a few new issues getting reported)
=> Rule: `rule-assigns-default`

internal/lsp/hover/hover.go, internal/lsp/hover/hover_test.go, internal/lsp/hover/testdata/hover/foobar.md
Other engines may expose custom builtins with does not on openpolicyagent.org, [see here](https://github.com/StyraInc/enterprise-opa/blob/v1.29.1/capabilities/v1.29.1.json#L5110).
This PR supports loading them from the Categories for a builtin.
Thanks @srenatus for the help on this one!
=> lsp/hover: Use link overrides if set

internal/lsp/server_aggregates_test.go, internal/lsp/server_config_test.go, internal/lsp/server_multi_file_test.go, internal/lsp/server_single_file_test.go, internal/lsp/server_template_test.go
It's no functional change, just makes the code a little more concise.
Hope you don't mind me messing with your test code like this. Originally, I had attempted to use labels, like
```go
outer:
for {
select {
case ... :
// stuff
break outer
}
```
but labels need to be unique within a file, and having to go with `outer1`, `outer2`, ... etc would have been awkward.
=> internal/lsp/*_test.go: replace for+success pattern

.github/workflows/build.yaml
This step is unreliable and needs more investigation. It is currently running in optional mode.
=> ci: Allow race detector to fail

bundle/regal/rules/bugs/inconsistent-args/inconsistent_args.rego, bundle/regal/rules/bugs/inconsistent-args/inconsistent_args_test.rego
While a mismatched arg is technically still a violation, the arity mismatch should probably be dealt with first, so let's have the compiler handle that.
Fixes #1250
=> Fix false positive given arity mismatch in `inconsistent-args`

internal/lsp/completions/providers/policy.go, internal/lsp/rego/rego.go, pkg/linter/linter.go, pkg/linter/linter_test.go
This doesn't have a huge impact on `regal lint` (although it does result in less allocations), but could potentially make a real difference for the LSP policies where ASTs from the whole workspace is provided under `data.workspace`.
Also, add the simple benchmark test I've been using for OPA fixes.
=> Use new setting to cache AST conversions from store

bundle/regal/main/main.rego, e2e/cli_test.go, e2e/testdata/aggregates/custom/regal/rules/testcase/empty_aggregate/empty_aggregate.rego, pkg/linter/linter.go
While custom aggregate rules would largely work before, those that report on the absence of data (like a rule named "allow") did not work. This as the aggregator sent nothing back in those caes — and contrary to the built-in rules, Regal had then no way of knowing in the next step that the aggregate report rules should be called even with no data.
I'm not super happy about the way we communicate this back to the Go side, but there's a lot I'm not happy about with regards to how aggregate data is shuffled back and forth. Some effort to fix that will however have to wait until later.
Fixes #1259
=> Fix custom rules that report on the absence of aggregates

internal/lsp/server_aggregates_test.go, internal/lsp/server_config_test.go, internal/lsp/server_multi_file_test.go, internal/lsp/server_single_file_test.go, internal/lsp/server_template_test.go
Previously, we were using Call, this will wait for a request and can block. This PR uses Notify instead, which is non-blocking and follows the spec.
=> lsp: Use notify for sending messages

.gitignore, docs/language-server.md, internal/io/io.go, internal/lsp/completions/providers/policy.go, internal/lsp/eval.go, internal/lsp/eval_test.go, internal/lsp/server.go
This addresses a request filed in the VS Code extension: https://github.com/open-policy-agent/vscode-opa/issues/308
Sadly this doesn't yet work for the debug feature as OPA currently only will do JSON decoding in that path, so next step is to submit a fix for that there.
=> Add support for using input.yaml in Evaluate code lens

.github/dependabot.yml
Monthly may seem like an excaggeration, but our only real dependency is OPA, and we update that ourselves anyway. The rest are just peripheral, and security related updates will be suggested immediately regardless.
=> Less frequent, and grouped dependabot updates

pkg/rules/rules.go, pkg/rules/rules_test.go
This creates a helper function that creates an `Input` given a module as a string in a given version of Rego. This is being added for the rego-playground primarily.
=> rules: Add InputFromTextWithOptions for Go users

.github/workflows/build.yaml, .golangci.yaml, cmd/new.go, internal/capabilities/capabilities.go, internal/embeds/embeds.go, internal/io/io.go, internal/lsp/bundles/cache.go, internal/lsp/completions/providers/ruleheadkeyword.go, internal/lsp/completions/providers/ruleheadkeyword_test.go, internal/lsp/completions/providers/utils.go, internal/lsp/diff.go, internal/lsp/documentsymbol.go, internal/lsp/foldingrange.go, internal/lsp/hover/hover.go, internal/lsp/lint.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_aggregates_test.go, internal/lsp/server_multi_file_test.go, internal/test/test.go, internal/web/server.go, pkg/config/config.go, pkg/fixer/fixes/directorypackagemismatch.go, pkg/linter/linter_test.go, pkg/reporter/reporter_test.go
Some of these were broken in the past. Enabling those now and one of them caught an actual issue, where we'd shadow the value of `err` in the command worker, and may not have some errors reported as we'd have expected.
The nolintlint rule that checks ignore directives may turn out to be too annoying, but it was at least good to have it help clear out comments that were not redundant. Leaving it on for now and we can always disable if it turns out to be irritating.
=> Enable a few more golangci-lint rules

bundle/regal/rules/style/pointless-reassignment/pointless_reassignment.rego, bundle/regal/rules/style/pointless-reassignment/pointless_reassignment_test.rego
That would happen despite the left hand side not being a var
Fixes #1285
=> Fix false positive in `pointless-reassignment`

bundle/regal/ast/ast.rego, bundle/regal/ast/search.rego, bundle/regal/rules/bugs/impossible-not/impossible_not.rego
This is absolutely wild 🙃
**Before**
```
BenchmarkRegalLintingItself-10	1	3245668375 ns/op	6689411656 B/op	127195706 allocs/op
```
**After**
```
BenchmarkRegalLintingItself-10  1	2777580459 ns/op	5235852824 B/op	107686435 allocs/op
```
And
```
hyperfine -i --warmup 1 'regal lint bundle' 'regal-new lint bundle'
Benchmark 1: regal lint bundle
Time (mean ± σ):      3.232 s ±  0.046 s    [User: 22.535 s, System: 0.623 s]
Range (min … max):    3.169 s …  3.296 s    10 runs
Benchmark 2: regal-new lint bundle
Time (mean ± σ):      2.754 s ±  0.046 s    [User: 18.641 s, System: 0.472 s]
Range (min … max):    2.689 s …  2.813 s    10 runs
Summary
regal-new lint bundle ran
1.17 ± 0.03 times faster than regal lint bundle
```
No @srenatus, I will not use benchstat! 🤣
=> Avoid allocations by not calling custom functions on hot path

cmd/debugger.go, cmd/parse.go, go.mod, go.sum, internal/explorer/stages.go, internal/io/io.go, internal/io/io_test.go, internal/lsp/bundles/cache.go, internal/lsp/cache/cache.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/providers/policy_test.go, internal/lsp/completions/refs/defined.go, internal/lsp/completions/refs/used.go, internal/lsp/eval.go, internal/lsp/opa/oracle/oracle.go, internal/lsp/opa/scanner/scanner.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/store.go, internal/parse/parse.go, internal/util/util.go, pkg/config/config.go, pkg/config/filter.go, pkg/fixer/fileprovider/inmem.go, pkg/fixer/fixes/directorypackagemismatch.go, pkg/fixer/fixes/fmt.go, pkg/linter/linter.go, pkg/reporter/reporter.go, pkg/rules/fmt.go, pkg/rules/rules.go
Using the new `ToOPAInput` function from RoAST cuts the number of allocations related to input transformation in half.
This doesn't constitute a bottleneck for command line linting, but will help the language server process files as quickly as possible on changes.
Also convert a few bytes/string conversions to allocation-free variants. I don't think these matter much, but having them around will help remind us that's an option for when it does matter.
=> Roast v0.5.0, faster input conversion

internal/capabilities/capabilities_integration_test.go, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
Fixes #1306
Thanks @OhMyGuus for reporting the issue!
=> Fix nil pointer dereference in JUnit reporter

.github/dependabot.yml
This should reduce the number of PRs we have when there are many updates to GHA deps, not just for go.mod deps.
=> dependabot: Update GHA dependencies in groups

internal/lsp/cache/cache.go, internal/lsp/connection.go, internal/lsp/hover/hover.go, internal/lsp/server.go, internal/util/concurrent/map.go
To avoid mutex handling cluttering up the code, use a concurrent wrapper for maps where we need it.
=> Use concurrent map implementation

e2e/cli_test.go, e2e/testdata/configs/v0-with-import-rego-v1.yaml
Mainly, this is ensuring the configs for each test are correct.
=> e2e: Fix CLI test for 1.0 preparations and defaults

cmd/languageserver.go
Fixes https://github.com/StyraInc/regal/issues/1324
=> cmd/languageserver: Log path & version at startup

internal/lsp/server.go, internal/lsp/server_all_rego_versions_test.go, internal/lsp/server_template_test.go, internal/util/concurrent/map.go
This does not reload when a .manifest file is changed yet.
=> lsp/server: Cache AllRegoVersions at config load

bundle/regal/lsp/completion/providers/regov1/regov1.rego, bundle/regal/lsp/completion/providers/regov1/regov1_test.rego, bundle/regal/lsp/completion/providers/test_utils/test_utils.rego, internal/embeds/schemas/regal-ast.json, internal/lsp/completions/providers/options.go, internal/lsp/completions/providers/policy.go, internal/lsp/server.go, internal/lsp/types/types.go
Also, use new version cache to determine version for formatting
=> lsp/completions: No rego.v1 import when in v1 file

docs/rules/style/opa-fmt.md
This explains the different behaviour of `opa fmt` between v0 and v1 when working with v0/v1 files in Rego.
=> docs: opa-fmt v1/v0 notes

cmd/languageserver.go, internal/lsp/connection.go, internal/lsp/server.go, pkg/fixer/fixes/directorypackagemismatch.go
As suggested here: https://github.com/StyraInc/regal/pull/1326#discussion_r1908895712
Sure there are more, but these are the first ones I found
=> tidy: Use cmp.Or in a few places

go.mod, go.sum, internal/lsp/opa/oracle/oracle.go, pkg/builtins/builtins_test.go, pkg/config/config.go, pkg/linter/linter_test.go
Roast now also on OPA 1.0, and v0.6.0 brings slightly faster serialization of terms as well.
Included in this PR too some minor fixes that don't deserve their own PR.
=> Upgrade Roast to v0.6.0

internal/lsp/server.go
There were two places where a file would be processed after a rename incorrectly:
- inlay hints were still requests if the file wasn't rego
- new files were still formatting if the file wasn't rego any more
Fixes https://github.com/StyraInc/regal/issues/1092
=> lsp: ignore after rename if not Rego

internal/lsp/server.go
This PR fixes a bug with filtering out `regal.debug` codelens when `enableDebugCodelens != true`
I ran into it a few days ago and it seems like it has been here since the implementation (https://github.com/StyraInc/regal/pull/1176)
=> fix: filter out `regal.debug` codelens

internal/lsp/server.go, internal/lsp/types/types.go
Ironic quotes on support since this seems to be a client feature only, but I figured we'd still document that in the code rather than elsewhere, for reference next time we look into that.
Next up to look into supporting this in the OPA VS Code extension.
=> Add workspace folder type, and "support" that capability

.github/workflows/build.yaml, internal/lsp/cache/cache.go, internal/lsp/handler/handler.go, internal/lsp/server.go, internal/lsp/server_formatting_test.go
While there's more to do here, we've got to start somewhere.
- Simplify handlers by extracting shared logic
- Use "global" vars for static slices to avoid needless allocations
- No named return values
- Add GetContentAndModule convenience function to reduce boilerplate
- Various fixes
This should not change behavior of anything, just nake server.go a little more manageable.
=> Language server refactoring

bundle/regal/main/main.rego
In main.rego there are two places where we extract a relative path from the input policy file. This was however done in a loop despite only using variables from outside of the loop. Turns out there was close to a million allocations hiding there, lol.
**BenchmarkRegalLintingItself-10 Before**
```
1875658375 ns/op    3539151104 B/op    70020076 allocs/op
```
**BenchmarkRegalLintingItself-10 After**
```
1821361667 ns/op    3499082704 B/op    69062781 allocs/op
```
=> perf: move config check out of loop

internal/lsp/lint.go, internal/lsp/lint_test.go, internal/lsp/server.go
Fixes https://github.com/StyraInc/regal/issues/1344
Fixes https://github.com/StyraInc/regal/issues/1123
(in fact, the final two lsp bugs we have in the tracker: https://github.com/StyraInc/regal/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22language%20server%20protocol%22%20label%3Abug)
=> lsp: Ensure parse errors are saved as diagnostics correctly

bundle/regal/rules/custom/missing-metadata/missing_metadata.rego, bundle/regal/rules/custom/missing-metadata/missing_metadata_test.rego, internal/lsp/lint.go, internal/lsp/server_aggregates_test.go
Also, update the missing-metadata rule to report violation locations on the rule head ref and not the whole rule head.
=> Fix missing annotations in LSP parsing

internal/explorer/stages.go, pkg/rules/rules_test.go
https://github.com/StyraInc/regal/pull/1354
=> chore: Use regal's parse options

pkg/linter/linter.go
Found out just last night that querying a data path that isn't found is treated as `error` by the storage module, and as such a source of allocations. So let's avoid it where we can.
```
Before  3519103080 B/op	 69457852 allocs/op
After   3508152464 B/op  69203795 allocs/op
```
=> perf: always include `ignore_files` in data

p.rego, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
ref: #1364 
Thanks to @anderseknert  for guiding me on this.
heres how the copmact reoprt looked like before :
heres what it will look like now :
special mention to my roomates who dont have a github, for choosing which one of the styles looked better.
=> The compact output format should include a summary #1364

bundle/regal/rules/idiomatic/use-if/use_if.rego, bundle/regal/rules/idiomatic/use-if/use_if_test.rego
Fixes #1361
Instead of highlighting the whole rule, we now only highlight the rule ref
=> fix: better location reporting in `use-if` rule

docs/rules/bugs/deprecated-builtin.md
Thanks @tsandall for suggesting this!
=> docs: deprecated built-in replacements

bundle/regal/config/exclusion.rego, internal/lsp/completions/providers/policy.go, internal/lsp/store.go, internal/lsp/store_test.go, pkg/config/config.go
- Use `count` on `data.eval.params.ignore_files` as it's now always defined
- Set `inmem.OptReturnASTValuesOnRead(true)` on the LSP inmem store for a substantial performance boost!
- Remove `rego.StoreReadAST(true)` which was ignored since we set the store explicitly
=> Small fixes

pkg/builtins/builtins.go
Not so much about performance this time (although of course, it saves a handful of allocations ;) but the fact that it's occasionally helpful to check the strict built-in errors logged. Since this built-in is frequently called on empty arrays, this is noisy.
=> Don't return error from `regal.last`

internal/lsp/config/find.go, internal/lsp/config/find_test.go, internal/lsp/server.go
This makes the configuration for the server closer to the configuration for the lint command. A config directory or file found within the
client-supplied workspace root is used instead of only searching
upwards.
If more than one .regal* root is found within the dir, then the first is used. Ideally, we'd support many different config files but this is harder to implement.
If none are found, then the previous behavior of searching upwards is used.
Fixes https://github.com/StyraInc/regal/issues/1365
=> lsp: Use nested workspace configuration if found

README.md, cmd/lint.go, cmd/utils.go, internal/lsp/server.go, pkg/config/global.go
If a config file is not found in a parent of the workspace, then we attempt to load the user's global default file instead.
Fixes https://github.com/StyraInc/regal/issues/1075
LS will also log the location of the file used.
=> config: Use global user config if required

bundle/regal/lsp/codelens/codelens.rego, bundle/regal/lsp/codelens/codelens_test.rego, docs/fixing.md, docs/rules/idiomatic/non-raw-regex-pattern.md, internal/lsp/command.go, internal/lsp/command_test.go, internal/lsp/commands/parse.go, internal/lsp/commands/parse_test.go, internal/lsp/handle_text_document_code_action_test.go, internal/lsp/server.go, internal/util/util.go, pkg/fixer/fixer.go, pkg/fixer/fixes/fixes.go, pkg/fixer/fixes/nonrawregexpattern.go, pkg/fixer/fixes/nonrawregexpattern_test.go, pkg/fixer/fixes/nowhitespacecomment.go, pkg/fixer/fixes/nowhitespacecomment_test.go, pkg/fixer/fixes/useassignmentoperator.go, pkg/fixer/fixes/useassignmentoperator_test.go
Also update the lsp commands to support the end locations so that we can operate more accurately rather than guessing the end of the target range.
Fixes https://github.com/StyraInc/regal/issues/1380
=> fix: non-raw regex pattern

.vscode/settings.json, cmd/fix.go, cmd/table.go, cmd/test.go, e2e/cli_test.go, internal/lsp/cache/cache.go, internal/util/util.go, pkg/config/config.go, pkg/fixer/fileprovider/cache.go, pkg/fixer/fileprovider/cache_test.go, pkg/fixer/fileprovider/inmem.go, pkg/reporter/reporter.go
This was added by @charlieegan3 yesterday, and I much prefer the ergonomics of this compared to using `map[T]struct{}` directly. So let's do it!
=> Consistently use new `Set` type

internal/lsp/server_aggregates_test.go
=> lsp/test: Error in test should be log instead

bundle/regal/rules/bugs/unused-output-variable/unused_output_variable.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable_test.rego
Comprehension term vars are never unused, and should not be flagged.
Fixes #1353
=> Fix false positive in `unused-output-variable`

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/use-object-keys/use_object_keys.rego, bundle/regal/rules/idiomatic/use-object-keys/use_object_keys_test.rego, docs/rules/idiomatic/use-object-keys.md, e2e/testdata/violations/most_violations.rego
=> Rule: `use-object-keys`

internal/lsp/server.go
Avoids confusion that regal is running as root.
=> lsp: update log messages for root dir note

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/rules/idiomatic/use-object-keys/use_object_keys.rego, bundle/regal/rules/idiomatic/use-object-keys/use_object_keys_test.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression_test.rego, bundle/regal/util/util.rego, bundle/regal/util/util_test.rego, docs/rules/performance/non-loop-expression.md, e2e/testdata/violations/most_violations.rego
Fixes https://github.com/StyraInc/regal/issues/93
TODO:
=> bundle: Add non-loop-expression rule

internal/lsp/server.go
Unsure when this was lost, but this is an important behavior to have back!
=> lsp: show parse errors in diagnostics

docs/rules/performance/non-loop-expression.md
This example role is clearer as a string rather than some random var.
=> docs: Use strings for non-loop expression role

.github/workflows/build.yaml, .golangci.yaml, go.mod, go.sum, internal/lsp/examples/examples.go, pkg/hints/hints.go
Although tbh, I'm not sure why we rely on the mapstructure dependency in the first place. It's only used in a single location, and it looks like we could easily do what it does there without it..
=> Bump Go to 1.23, and replace archived dependency

cmd/lint.go, internal/lsp/server.go
Previously, there was an incorrect assumption that abs paths started with /.
This commit also fixes a test bug where the server's logger was used before it was defined.
Fixes https://github.com/StyraInc/regal/issues/1414
=> cmd/lint: Fix windows Abs path handling

bundle/regal/main/main.rego, bundle/regal/main/main_test.rego
When the root is also the root of the filesystem, the linter will  now handle ignore patterns correctly.
Fixes https://github.com/StyraInc/regal/issues/1415
=> lint: Handle root filesystem root prefix

internal/lsp/cache/cache.go, internal/lsp/lint.go, internal/lsp/server.go
Previously, when editing a line, if parse errors come and go as you edit, the Code Lenses will toggle on and off as the parse error list is updated.
Now, only if the line count is different from the last successful parse, will the Code Lenses be disabled.
This means that a line can be typed while it contains errors, and code lenses will now come and go.
https://github.com/user-attachments/assets/861c837a-375a-48da-97d9-1867fe2e5ba7
=> lsp: Fix Code Lenses jank

internal/lsp/server.go
This had not been updated to the new arg format causing it to look up the wrong file path.
Also only log the use of the global file if a file is found.
=> lsp: Correct path when fixing dir package mismatch

internal/lsp/server.go, internal/lsp/server_rename_test.go
Fixes https://github.com/StyraInc/regal/issues/1431
=> lsp: Ensure rename target is within workspace root

.goreleaser.yaml, internal/novelty/holidays.go, internal/novelty/novelty.go
This allows Regal to be built without the go-asciisprite dependency.
=> build: Make novelty package opt-in

.github/workflows/build.yaml, .golangci.yaml, build/do.rq, bundle/bundle.go, cmd/lint.go, cmd/root.go, cmd/test.go, internal/explorer/stages.go, internal/io/io.go, internal/lsp/completions/providers/rulehead.go, internal/lsp/completions/refs/used.go, internal/lsp/eval.go, internal/lsp/examples/examples.go, internal/lsp/hover/hover.go, internal/lsp/lint.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/parse/parse.go, internal/update/update.go, internal/util/util.go, internal/web/server.go, pkg/builtins/builtins.go, pkg/fixer/fixer.go, pkg/hints/hints.go, pkg/linter/linter.go, pkg/report/report.go, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go, pkg/version/version.go
This was made pretty easy with the help of `golangci-lint migrate`.
Also:
- disable gochecknoglobals linter (because annoying)
- disable exhaustive linter (new? annoying either way)
=> golangci-lint v2

bundle/regal/ast/ast.rego, bundle/regal/rules/custom/naming-convention/naming_convention.rego, bundle/regal/rules/idiomatic/use-strings-count/use_strings_count.rego
This saves almost a million allocations. The redundant loop in use-strings-count was particularly embarrassing, and should certainly be made a linter rule, if not a strict mode unused violation.
=> Some perf fixes

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/argument-always-wildcard/argument_always_wildcard.rego, bundle/regal/rules/bugs/constant-condition/constant_condition.rego, bundle/regal/rules/bugs/import-shadows-rule/import_shadows_rule.rego, bundle/regal/rules/bugs/leaked-internal-reference/leaked_internal_reference.rego, bundle/regal/rules/bugs/not-equals-in-loop/not_equals_in_loop.rego, bundle/regal/rules/bugs/redundant-existence-check/redundant_existence_check.rego, bundle/regal/rules/bugs/rule-assigns-default/rule_assigns_default.rego, bundle/regal/rules/bugs/rule-shadows-builtin/rule_shadows_builtin.rego, bundle/regal/rules/bugs/unassigned-return-value/unassigned_return_value.rego, bundle/regal/rules/custom/one-liner-rule/one_liner_rule.rego, bundle/regal/rules/imports/redundant-data-import/redundant_data_import.rego, bundle/regal/rules/performance/defer-assignment/defer_assignment.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression.rego, bundle/regal/rules/performance/walk-no-path/walk_no_path.rego, bundle/regal/rules/style/default-over-not/default_over_not.rego, bundle/regal/rules/style/double-negative/double_negative.rego, bundle/regal/rules/style/function-arg-return/function_arg_return.rego, bundle/regal/rules/style/line-length/line_length.rego, bundle/regal/rules/style/prefer-some-in-iteration/prefer_some_in_iteration.rego, bundle/regal/rules/testing/print-or-trace-call/print_or_trace_call.rego, pkg/linter/linter_test.go
This started out as simply improving the performance of ref comparisons, where we should avoid stringifying if possible. But eventually led to a series of smallish optimizations, mostly related to iteration, and to keep the scope of _what_ is iterated down to smaller components. This saves about 300k allocations in `regal lint bundle`.
=> perf: various improvements

bundle/regal/ast/ast_test.rego, bundle/regal/config/provided/data.yaml, bundle/regal/lsp/completion/location/location_test.rego, bundle/regal/lsp/completion/providers/default/default_test.rego, bundle/regal/lsp/completion/providers/inputdotjson/inputdotjson_test.rego, bundle/regal/lsp/completion/providers/packagename/packagename_test.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego, bundle/regal/main/main_test.rego, bundle/regal/result/result_test.rego, bundle/regal/rules/bugs/duplicate-rule/duplicate_rule_test.rego, bundle/regal/rules/bugs/impossible-not/impossible_not_test.rego, bundle/regal/rules/bugs/not-equals-in-loop/not_equals_in_loop_test.rego, bundle/regal/rules/custom/missing-metadata/missing_metadata_test.rego, bundle/regal/rules/custom/naming-convention/naming_convention_test.rego, bundle/regal/rules/idiomatic/no-defined-entrypoint/no_defined_entrypoint_test.rego, bundle/regal/rules/idiomatic/use-some-for-output-vars/use_some_for_output_vars_test.rego, bundle/regal/rules/imports/circular-import/circular_import_test.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports_test.rego, bundle/regal/rules/imports/unresolved-import/unresolved_import_test.rego, bundle/regal/rules/style/file-length/file_length_test.rego, bundle/regal/rules/style/rule-length/rule_length.rego, bundle/regal/rules/style/rule-length/rule_length_test.rego, bundle/regal/rules/style/rule-name-repeats-package/rule_name_repeats_package_test.rego, bundle/regal/rules/style/use-assignment-operator/use_assignment_operator_test.rego, docs/rules/style/rule-length.md
Since tests are often mostly data, there is little to gain by moving relevant data outside of tests. This PR introduces a max-test-rule-length setting, which by default is set to 60 rather than 30, which is the default for other rules.
Finally getting rid of all inline ignore directives related to this in our tests!
Fixes #1125
=> Add max-test-rule-length setting to rule-length rule

bundle/regal/ast/imports.rego, bundle/regal/ast/imports_test.rego, bundle/regal/rules/style/unnecessary-some/unnecessary_some.rego
And a few tweaks to the import checking functions.
Fixes #1483
=> Fix unnecessary-some rule not working after OPA 1.0+

internal/lsp/config/find.go
Stumbled upon this when playing with the LSP and sending bad init parameters -- that caused `err` to be non-nil, and ran into a nil deref on `info.IsDir()` 💥 
Happy to add a test if you can point out a good spot 😄
=> FindConfigRoots: return error, not panic

bundle/regal/config/config.rego, bundle/regal/config/config_test.rego, bundle/regal/main/main.rego, bundle/regal/result/result.rego, pkg/linter/linter.go, pkg/linter/linter_test.go
**main**
```
1188808042 ns/op	3332404200 B/op	63908530 allocs/op
```
**this**
```
1148661583 ns/op	3173734464 B/op	61290539 allocs/op
```
2,7 million allocs!
Mostly guided by `--profile` metrics, which suggested a lot of time being spent in config.rego. That is interesting, as there isn't really anything there that would easily map to the pprof heap dumps. And there weren't any real bottlenecks to be found either. Just custom functions called very frequently, and some objects getting unioned constantly, even though the info added (the calculated level) almost never matters, as the main route won't even consider ignored policies.
This makes it much cheaper to check for the actual level for a rule from the main.rego composition, while also making it much cheaper to get the config for a rule …
=> perf: Improve how config is parsed, and when

bundle/regal/ast/ast.rego, bundle/regal/ast/search.rego, bundle/regal/main/main.rego, bundle/regal/rules/bugs/unused-output-variable/unused_output_variable.rego, bundle/regal/rules/style/use-assignment-operator/use_assignment_operator.rego, docs/rules/idiomatic/use-some-for-output-vars.md, docs/rules/style/use-assignment-operator.md, docs/rules/testing/dubious-print-sprintf.md, pkg/linter/linter_test.go
Also a small few perf fixes I hadn't committed before. Small but
with quite an impact. ~2 million allocs!
```
1088929208 ns/op        3104908016 B/op 59995728 allocs/op
1070530708 ns/op        3041023912 B/op 58063258 allocs/op
```
=> docs: fix docs that still used v0 syntax

bundle/regal/ast/ast.rego, bundle/regal/ast/search.rego, bundle/regal/rules/style/external-reference/external_reference.rego, bundle/regal/rules/style/prefer-some-in-iteration/prefer_some_in_iteration.rego, pkg/linter/linter_test.go
Avoids walking `.annotations` in rules, which is particularly expensive in the few places where we need the path from each iteration. We could probably use this everywhere we walk, but it would be more noisy and for less gain, so stopping here for now.
```
1048394166 ns/op	2953960968 B/op	56616841 allocs/op
1034816959 ns/op	2910685336 B/op	55738401 allocs/op
```
=> perf: walk less, save allocations

bundle/regal/rules/imports/circular-import/circular_import.rego, cmd/fix.go, cmd/lint.go, e2e/cli_test.go, internal/io/io.go, pkg/linter/linter.go, pkg/linter/linter_test.go
This paves the way for moving initialization logic to Rego later: https://github.com/StyraInc/regal/issues/359
As well as moving the `DetermineEnabledRules` and
`DetermineEnabledAggregateRules` methods to instead use the same query later on.
Fixes #1394
=> Add Prepare method for reusing state across linter runs

cmd/lint.go, internal/update/update.go, internal/update/update.rego, internal/update/update_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go
Just something little I wanted to try :)
=> Move more of version check to Rego

docs/custom-rules.md
https://www.openpolicyagent.org/docs/latest/policy-language/#annotations is the correct place now as I understand.
=> docs: Fix annotations link

bundle/regal/ast/ast.rego, bundle/regal/rules/imports/unresolved-reference/unresolved_reference.rego, bundle/regal/util/util.rego, pkg/linter/linter_test.go
We've had a few heavy rules in the past, but nothing like this one. That's not really due to the implementation of the rule, but simply the fact that it aggregates every ref found everywhere, which will be a lot no matter what.
Using the standard "regal linting itself" benchmark on main before the rule was merged and after shows a 10%+ increase in memory allocated as well as wall clock time:
```
1111071791 ns/op	3001557280 B/op	58184205 allocs/op
1289814875 ns/op	3363166528 B/op	64788506 allocs/op - unresolved-reference merged
```
There are [some design issues](https://github.com/StyraInc/regal/issues/1265) to address with aggregate rules that likely would mean bigger wins across the board, but the focus of this PR is solely to optimize the code for the rule itself.
While this remains an …
=> perf: improve performance of new unresolved-reference rule

bundle/regal/rules/custom/missing-metadata/missing_metadata.rego, bundle/regal/rules/imports/circular-import/circular_import.rego, bundle/regal/rules/imports/circular-import/circular_import_test.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports_test.rego, bundle/regal/rules/imports/unresolved-import/unresolved_import.rego, bundle/regal/rules/imports/unresolved-import/unresolved_import_test.rego, bundle/regal/util/util.rego, internal/lsp/server_aggregates_test.go, pkg/linter/linter_test.go
Make aggregate rules more efficient by only aggregating data that's absolutely needed, and try to use more compact representations for the aggregated data, the same way just done for unresolved-reference.
```
1130275167 ns/op	3204268280 B/op	62150928 allocs/op
1166222041 ns/op	3189028336 B/op	61860532 allocs/op - circular-import: defer to_location to report
1107372792 ns/op	3191798600 B/op	61459275 allocs/op - circular-import: use compact array format for aggregates
1122124750 ns/op	3183487808 B/op	61315825 allocs/op - prefer-package-imports: same as above
1095128583 ns/op	3171781928 B/op	61097537 allocs/op - unresolved-import: same as above
```
=> perf: improve aggregate rules

.regal/config.yaml, bundle/regal/ast/ast_test.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/lsp/codelens/codelens.rego, bundle/regal/lsp/completion/providers/packagename/packagename_test.rego, bundle/regal/lsp/completion/ref_names.rego, bundle/regal/main/main.rego, bundle/regal/rules/custom/one-liner-rule/one_liner_rule.rego, bundle/regal/rules/custom/one-liner-rule/one_liner_rule_test.rego, bundle/regal/util/util_test.rego
Also, enable the rule! We almost always did this anyway.
Finally, update tests to not mock config for error level, as that's no longer needed.
Fixes #1527
=> Fix false positive in one-liner-rule

.regal/config.yaml, bundle/regal/ast/ast.rego, bundle/regal/ast/imports.rego, bundle/regal/ast/search.rego, bundle/regal/lsp/completion/location/location.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs_test.rego, bundle/regal/rules/custom/narrow-argument/narrow_argument.rego, bundle/regal/rules/custom/prefer-value-in-head/prefer_value_in_head.rego, bundle/regal/rules/custom/prefer-value-in-head/prefer_value_in_head_test.rego, bundle/regal/rules/imports/circular-import/circular_import.rego, bundle/regal/rules/imports/unresolved-import/unresolved_import.rego, bundle/regal/rules/style/rule-name-repeats-package/rule_name_repeats_package.rego, docs/rules/custom/prefer-value-in-head.md
Although with `only-scalars` set to `true`. I did review the violations reported without that, and while most didn't warrant "fixing", a a few did, and so I did.
Also added an option to the rule to be able to list variable names that should be excluded.
It's fun to play around, but the high-level goal here is mostly to have `regal lint bundle` run all rules, even if with some exceptions defined in the config.
=> Enable prefer-values-in-head

cmd/lint.go, internal/dap/logger.go, internal/lsp/bundles/cache.go, internal/lsp/commands/parse_test.go, internal/lsp/completions/providers/policy_test.go, internal/lsp/completions/providers/ruleheadkeyword_test.go, internal/lsp/completions/refs/used.go, internal/lsp/connection.go, internal/lsp/lint.go, internal/lsp/opa/tokens/tokens.go, internal/lsp/rego/rego.go, internal/lsp/store_test.go
Not a whole lot of them, but the contains checks are nice! I wish this would integrate with golangci-lint, but for now I don't think the overhead of running this separately in CI is worth it, as I don't expect us to have many things to fix in future code.
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...
```
=> Apply modernize fixes

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/search.rego, bundle/regal/lsp/completion/location/location.rego, bundle/regal/lsp/completion/providers/booleans/booleans.rego, bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego, bundle/regal/rules/bugs/impossible-not/impossible_not.rego, bundle/regal/rules/bugs/inconsistent-args/inconsistent_args.rego, bundle/regal/rules/bugs/not-equals-in-loop/not_equals_in_loop.rego, bundle/regal/rules/bugs/time-now-ns-twice/time_now_ns_twice.rego, bundle/regal/rules/bugs/top-level-iteration/top_level_iteration.rego, bundle/regal/rules/idiomatic/use-object-keys/use_object_keys.rego, bundle/regal/rules/imports/circular-import/circular_import.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego, bundle/regal/rules/imports/unresolved-import/unresolved_import.rego, bundle/regal/rules/imports/unresolved-reference/unresolved_reference.rego, bundle/regal/rules/style/external-reference/external_reference.rego, bundle/regal/rules/style/prefer-some-in-iteration/prefer_some_in_iteration.rego, bundle/regal/rules/style/rule-length/rule_length.rego, bundle/regal/rules/style/rule-length/rule_length_test.rego, bundle/regal/rules/style/rule-name-repeats-package/rule_name_repeats_package.rego, pkg/linter/linter_test.go
- My new favorite trick! Using `regex.replace` to extract values out from a text instead of `split`-ing a string on a delimiter. This is surprisingly *much* cheaper
- Use fixed max length of 100 in array.slice instead of `count`, where appropriate (like when slicing terms)
- Simplify and/or inline some custom functions
About 1.2 million allocations saved (see benchmark in PR for details)
=> perf: various optimizations

bundle/regal/ast/ast.rego, bundle/regal/lsp/codelens/codelens.rego, bundle/regal/lsp/completion/location/location.rego, bundle/regal/lsp/completion/providers/commonrule/commonrule.rego, bundle/regal/lsp/completion/providers/packagename/packagename.rego, bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego, bundle/regal/rules/bugs/impossible-not/impossible_not.rego, bundle/regal/rules/bugs/invalid-metadata-attribute/invalid_metadata_attribute.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego
And simplify invalid-metadata-attribute rule. Doesn't show much on our benchmarks as most of these locations aren't hit by them.
=> perf: some Rego micro-optimizations

bundle/regal/ast/ast.rego, bundle/regal/ast/comments.rego, bundle/regal/ast/search.rego, bundle/regal/main/main.rego, bundle/regal/rules/bugs/invalid-metadata-attribute/invalid_metadata_attribute.rego, bundle/regal/rules/idiomatic/use-in-operator/use_in_operator.rego, bundle/regal/rules/imports/prefer-package-imports/prefer_package_imports.rego, bundle/regal/rules/imports/unresolved-reference/unresolved_reference.rego, bundle/regal/rules/style/detached-metadata/detached_metadata.rego, bundle/regal/rules/style/external-reference/external_reference.rego, bundle/regal/rules/style/no-whitespace-comment/no_whitespace_comment.rego, pkg/linter/linter_test.go
A bit of everything really, but mostly try to avoid/defer code that allocates wherever possible, and try to replace some built-in calls that allocate with equivalent calls that don't.
**main vs. change**
```
1038017000 ns/op    3059460456 B/op    58499170 allocs/op
968805333 ns/op    2970674744 B/op    56876788 allocs/op
```
Down by about ~2.4 million allocs and ~2% allocated space.
For the first time since I started benchmarking, ns/op is now below a second, and with some margin even! That means each benchmark now runs `regal lint bundle` 2 times instead of just one, as the first run is now under the one second threshold. Neat!
=> perf: Rego optimizations to avoid alloactions

bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/unresolved-reference/unresolved_reference.rego
Test references are more than half the `refs` in the aaggregate. Tests should not be referenced, an as such there is a big overhead in performance. We also expected that it had a big overhead in storage, but that was not the case.
Benchmark on main
```BenchmarkRegalLintingItself-10    	       1	15386247125 ns/op	3171539784 B/op	61023512 allocs/op```
Benchmark on this branch
```BenchmarkRegalLintingItself-10    	       1	11105144576 ns/op	3176159616 B/op	61074987 allocs/op```
=> Ignore test 'rules' as they take up a lot of memory and cpu

bundle/regal/ast/comments.rego, bundle/regal/rules/bugs/annotation-without-metadata/annotation_without_metadata.rego, bundle/regal/rules/style/function-arg-return/function_arg_return.rego, internal/lsp/server.go
And remove handleTextDocumentCodeAction debug logging
=> Small perf fixes

bundle/regal/ast/ast.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression.rego, internal/cache/cache.go, internal/cache/cache_test.go
The non-loop-expression reordering is the major change here, as it accounts for almost 700k allocations less! Which is of course ironic for that rule :P
=> Small fixes before next release

bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego, internal/cache/cache_test.go, pkg/builtins/builtins_test.go, pkg/linter/linter_test.go
While most editors seemed to be capable of filtering out these suggestions by themselves, not all did. And we should obviously not send suggestions that aren't valid in any case.
Fixes #1588
=> fix: improve snippets suggestion condition

bundle/regal/lsp/completion/providers/input/input.rego, bundle/regal/lsp/completion/providers/input/input_test.rego
While it's perhaps possible to have something like `data.foo.input.bar`, that `input` wouldn't be the same `input` as suggested here: we're explicitly documenting it as "the input document".
This should fix the situation where you can use suggestions to come up with
input.input.input.input
=> lsp/completion/input: don't suggest 'input' following dot

.golangci.yaml, internal/compile/compile_bench_test.go
This is really testing OPA rather than Regal, but since it's a good test case for improving OPA for Regal, it belongs here.
Used in https://github.com/open-policy-agent/opa/pull/7740
=> Add Regal bundle compilation benchmark

internal/io/io.go, internal/lsp/eval_test.go, internal/lsp/server.go
This is in preparation of some refactoring for io.FindInput(), which I'd like to make somehow aware of the cached files... but I think it's an OK change as-is. A bit of duplication, but less work when we don't care for the file content.
=> internal/io: add FindInputPath when the content isn't needed

bundle/regal/lsp/completion/providers/packagename/packagename.rego, bundle/regal/lsp/completion/providers/packagename/packagename_test.rego
Fixes https://github.com/StyraInc/regal/issues/1391
=> lsp/completions: Handle hyphenated package names

internal/lsp/server.go, internal/lsp/server_template_test.go
Fixes https://github.com/StyraInc/regal/issues/1608
Extract StartTemplateWorker body into processTemplateJob method to make it possible to test.
It might be good to implement more general locking and unlocking of file contents if we make more modifications but for now, I think this is ok as it addresses the main issue in question.
=> lsp: fix didOpen templating race

README.md, build/lsp/go.mod, build/ws/go.mod, docs/adopters.md, docs/readme-sections/getting-started.md, docs/readme-sections/intro.md, docs/readme-sections/roadmap.md, e2e/testbuild/go.mod, e2e/testbuild/go.sum, go.mod
- Since the `brew` package is now available as an official Homebrew formula, we now recommend using that instead. Later, we should also look into [deprecating](https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#deprecate-and-disable-reasons) the styrainc formula, so that users will get notified when using the old one.
- Roadmap progress update
- Bump Go versions and some other minor fixes in our go.mod files
- Update adopters.md with more companies and organizations
=> Some doc updates

cmd/new.go, e2e/cli_test.go, e2e/runner.go, e2e/testdata/aggregates/custom/regal/rules/testcase/aggregates/custom_rules_using_aggregates.rego, go.mod, internal/io/io.go, internal/testutil/testutil.go, pkg/roast/util/set.go
While really important, the e2e tests have been a bit painful to work with, much because so much of the tests have been procedural scaffolding rather than test logic. With this refactor, I'm hoping to improve that by introducing a more declararative approach in the form of a tiny DSL for a command runner.
The result is less than half the lines of test code, and tests that IMHO make it quite easy to quickly understand what's being tested. I hope others feel the same :)
=> test: refactor e2e test, add new regal command runner

.regal/config.yaml, internal/lsp/handle_text_document_code_action_test.go, internal/lsp/rego/rego.go, internal/lsp/server.go
This went missing without us noticing :( Due to the input not being what the policy expected (and even verified at compile time). We should look into how to leverage those schemas for runtime checks, as that could save a lot of time troubleshooting. But for now, fixing the issue and adding a regression test for the handler.
=> Fix missing source.explore code action

internal/lsp/lint.go, internal/lsp/lint_test.go, internal/lsp/server.go
This makes a change so that when a file is shown in an error message, we show the filename relative to the root of the project rather than the full URI.
This is done by changing the name of the file used in parsing.
I have also adjusted updateParse to take Opts struct instead to make it less verbose.
Fixes https://github.com/StyraInc/regal/issues/1635
=> lsp: Present filename relative to root in errors

bundle/bundle.go, cmd/lint.go, cmd/test.go, internal/compile/compile_bench_test.go, internal/io/io.go, internal/io/io_test.go, internal/lsp/completions/providers/policy.go, internal/lsp/completions/refs/used.go, internal/lsp/eval.go, internal/lsp/rego/rego.go, internal/lsp/server.go, pkg/linter/linter.go, pkg/linter/linter_test.go
This allows live editing of Rego in the language server, and see the result propagated to the UI right away. A very nice development experience!
This is however very much experimental at this point, and only by setting an `REGAL_BUNDLE_PATH` to point at the bundle path will this be enabled. Most likely a few issues left to resolve here, but let's take it from here!
If we start using this often, we'll also want to optimize bundle loading too, as that happens *very* frequently. Perhaps we could have a file watcher notify us of changes or something like that, and only refresh the bundle when that happens. @charlieegan3 let's talk about that some time :)
https://github.com/user-attachments/assets/40b96ef7-d180-42d8-9c4a-d35a4306f8de
=> Provide development option to load bundle from disk

internal/io/io.go
For virtually all OPA users, this will make no difference. But if you use Regal together with OPA and bundle activation plugin(s), like EOPA, the default will be flipped. As a consequence, the internal Regal bundle cannot be loaded, and every linting fails.
This only affects users that
1. build something that embeds Regal as Go module
2. register extensions with OPA's bundle loader
Since de-registering such extensions isn't well-supported, it's hard to test for this.
=> internal/io: explicitly disable lazy loading of regal bundle

README.md, docs/readme-sections/intro.md, internal/compile/compile.go, internal/io/files/walker.go
Also moved the "important" section in the readme somewhat as it's not as important now.
Fixes #1679
=> fix: Don't use OS path separator when walking FS

.github/workflows/update-caps.yml
The goal of this change is to improve the OpenSSF Scorecard score (this repo self-publishes to https://scorecard.dev/viewer/?uri=github.com/open-policy-agent/regal).
There's a pretty harsh penalty for any top-level workflow permission set to `write` (see [Token Permissions](https://github.com/ossf/scorecard/blob/ab2f6e92482462fe66246d9e32f642855a691dc1/docs/checks.md#token-permissions)), so this would be a good improvement to the score.
=> build: reduce update-caps top-level workflow permission to read

internal/lsp/server.go, internal/lsp/server_no_workspace_test.go, internal/lsp/server_test.go
Fixes https://github.com/open-policy-agent/regal/issues/1671
when there is a user level config
when there is no config at all
=> lsp: Fix missing initial root
