open-policy-agent/regal

.goreleaser.yaml
Fixes https://github.com/StyraInc/regal/issues/163
This will likely need to be merged and a test release created to test.
=> Add ko build for container images

README.md, bundle/regal/rules/idiomatic/common_test.rego, bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom_has_key_construct_test.rego, bundle/regal/rules/idiomatic/custom_in_construct.rego, bundle/regal/rules/idiomatic/custom_in_construct_test.rego, cmd/table.go, docs/rules/idiomatic/custom-has-key-construct.md, docs/rules/idiomatic/custom-in-construct.md
And two new rules:
- custom-has-key-construct
- custom-in-construct
=> Add idiomatic category

bundle/regal/rules/style/unconditional_assignment.rego, bundle/regal/rules/style/unconditional_assignment_test.rego
To be revisited once the issue in OPA is resolved.
Fixes #178
=> Fix unconditional-assignment with else clause

bundle/regal/rules/style/external_reference.rego, bundle/regal/rules/style/external_reference_test.rego
=> external-reference: don't count wildcard as external ref

bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom_has_key_construct_test.rego
=> Don't assume a single wildcard in custom-has-key-construct

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/detached_metadata.rego, bundle/regal/rules/style/detached_metadata_test.rego, docs/rules/style/detached-metadata.md
=> New style rule: detached-metadata

.github/workflows/build.yaml
=> ci/build: run on PRs

docs/custom-rules.md
=> Improve docs on custom rules authoring

.editorconfig, README.md
* Update OPA version in README
* Simplify .editorconfig
* Add Docker option to downloads section in README
* Add some links in roadmap, remove unclear item
=> Some minor fixes

README.md
=> Update roadmap status

docs/rego-style-guide.md, docs/rules/bugs/invalid-metadata-attribute.md, docs/rules/idiomatic/custom-has-key-construct.md, docs/rules/idiomatic/use-some-for-output-vars.md
Thanks @charlieegan3 for catching one of the issues.
=> Some doc fixes

docs/development.md
Fixes #261 - Just a minor update to the docs.
Let me know if any wording needs to be changed 😃
=> Update development docs

bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/file_length.rego, bundle/regal/rules/style/file_length_test.rego, docs/rules/style/file-length.md, e2e/cli_test.go, e2e/testdata/configs/ignore_files_prefer_snake_case.yaml
Add a rule to limit the length of file to a configured value, where the default is 500 lines.
=> Rule: file-length

bundle/regal/ast.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/non_raw_regex_pattern.rego, bundle/regal/rules/idiomatic/use_some_for_output_vars.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/prefer_some_in_iteration.rego, docs/rules/style/function-arg-return.md
=> Except walk from function-arg-return

README.md, docs/architecture.md, docs/development.md, docs/pre-commit-hooks.md, docs/rego-style-guide.md
Some risk that this gets outdated, obviously, so I've tried to avoid referencing locations in code and such. Will still need to revisit every once in a while, but hopefully this is useful for people looking to contribute.
Also made some minor updates to related documentation.
=> Add documentation on architecture

README.md, cmd/table.go
This has been an annoyance for a **long** time 😅
Fixes #142
=> Sort table by category *and* rule name

cmd/lint.go, docs/integration.md, internal/parse/parse.go, internal/parse/parse_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go, pkg/rules/rules.go
This is just one way to make progress towards: https://github.com/StyraInc/regal/issues/248.
=> Expose rules and parser opts for use as library

docs/integration.md
Fixes https://github.com/StyraInc/regal/issues/248
=> Add note about prod use of Go API

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/testing/dubious_print_sprintf.rego, bundle/regal/rules/testing/dubious_print_sprintf_test.rego, e2e/testdata/violations/most_violations.rego
Adding dubious-print-sprintf under testing category.
This PR is to address #220
=> print sprintf testing rule

README.md
Add link to integration documentation
=> Update documentation resources index

.gitattributes, .github/workflows/build.yaml, build/do.rq
I haven't updated the readme yet -- let's first discuss if this is a direction we'd like to take 😃
=> build: use rq

cmd/lint.go, pkg/linter/linter.go, pkg/linter/linter_test.go, pkg/linter/testdata/printer.rego
=> Add `--enable-print` flag to `regal lint`

bundle/regal/rules/imports/prefer_package_imports.rego, bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/line_length_test.rego, docs/rules/style/line-length.md
=> Add `non-breakable-word-threshold` option to `line-length` rule

bundle/regal/ast.rego, bundle/regal/rules/style/prefer_snake_case.rego, bundle/regal/rules/testing/metasyntactic_variable.rego
And use rule.head.ref consistently
Fixes #331
=> Remove rule.head.name usage

.github/workflows/build.yaml
=> Cancel concurrent CI execution on pushes to same PR

e2e/cli_test.go, internal/parse/parse_test.go, internal/test/rego_test.go, internal/test/test.go, internal/testutil/testutil.go, pkg/config/config_test.go, pkg/linter/linter_test.go, pkg/rules/fmt_test.go
=> Use `Must` test helper

README.md, docs/custom-rules.md
I'm sure there's more to it, but we can iterate on this when we hear back from the first custom aggregate rules authors.
Fixes #342
=> Aggregate rules documentation

.github/workflows/build.yaml
Uses https://github.com/StyraInc/setup-regal
=> Dogfood setup-regal action

.github/workflows/build.yaml, build/capabilities.json, build/do.rq, cmd/capabilities.go
=> Add capabilities.json and use for `opa check --strict`

README.md
Pinging @dkorolev @iamleot @mcguiresm for approval. 
Quotes from Slack, slightly modified to provide context.
=> Add testimonials to the README

.gitattributes, docs/rules/style/prefer-some-in-iteration.md, e2e/cli_test.go, internal/parse/parse.go
Could be more are needed, but I'll need this in main to test cloning from a blank state.
=> Fixes to run on Windows

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/import_after_rule.rego, bundle/regal/rules/imports/import_after_rule_test.rego, docs/rules/imports/import-after-rule.md, e2e/testdata/violations/most_violations.rego
=> Rule: `import-after-rule`

.github/workflows/build.yaml
=> cicd: Use go.mod as source for Go version

docs/rules/testing/dubious-print-sprintf.md
=> Fix heading for dubious-print-sprintf

bundle/regal/rules/bugs/top_level_iteration.rego, bundle/regal/rules/bugs/top_level_iteration_test.rego
=> Fix false positive in `top-level-iteration`

docs/rules/custom/forbidden-function-call.md, docs/rules/idiomatic/non-raw-regex-pattern.md, docs/rules/idiomatic/use-some-for-output-vars.md, docs/rules/imports/avoid-importing-input.md, docs/rules/style/use-assignment-operator.md
=> Docs: consistent casing of "OPA Docs"

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/zero_arity_function.rego, bundle/regal/rules/bugs/zero_arity_function_test.rego, docs/rules/bugs/zero-arity-function.md, e2e/testdata/violations/most_violations.rego
Forbid using functions without arguments
This commit is a milestone for Regal, as we now have 50 rules in total! 🎉 Roadmap goal updated, and only one more goal to meet before all the goals have been met, and we'll get to plan ahead with a new one.
Fixes #396
=> Rule: `zero-arity-function`

bundle/regal/rules/idiomatic/prefer_set_or_object_rule.rego, bundle/regal/rules/idiomatic/prefer_set_or_object_rule_test.rego
=> `prefer-set-or-object-rule`: cover more array->set cases

README.md
=> Add New Stack article by @charlieegan3

README.md
=> docs: remove logo attr

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/style/yoda_condition.rego, bundle/regal/rules/style/yoda_condition_test.rego, docs/rules/style/yoda-condition.md, e2e/testdata/violations/most_violations.rego, pkg/linter/linter_test.go
=> Rule: `yoda-condition`

README.md, bundle/regal/main.rego, bundle/regal/main_test.rego, bundle/regal/rules/bugs/inconsistent_args.rego, bundle/regal/rules/custom/one_liner_rule.rego
Also some minor fixes tangentially related to ignore directives.
Fixes #447
=> Allow ignore directive on same line

bundle/regal/rules/style/unnecessary_some.rego, bundle/regal/rules/style/unnecessary_some_test.rego
=> Fix false positive in `unnecessary-some`

.gitignore, cmd/lint.go, e2e/cli_test.go
Took a quick cut at resolving #439
=> Error out if config-file is explictly provided but non-existent

bundle/regal/rules/bugs/constant_condition.rego, bundle/regal/rules/bugs/not_equals_in_loop.rego, bundle/regal/rules/bugs/unused_return_value.rego, bundle/regal/rules/idiomatic/use_in_operator.rego, bundle/regal/rules/imports/import_shadows_import.rego, bundle/regal/rules/style/function_arg_return.rego, bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/no_whitespace_comment.rego, bundle/regal/util/util.rego
Mostly farting around today while home sick, and didn't have the energy for more than these silly tricks.
Unsurprisingly, micro-optimizations render micro-improvements, but I'd like to think I learnt some things in the process too.
```
hyperfine --warmup 1 "regal-main lint bundle" "regal-tricks lint bundle"
```
```
Benchmark 1: regal-main lint bundle
Time (mean ± σ):      1.640 s ±  0.027 s    [User: 11.746 s, System: 0.464 s]
Range (min … max):    1.599 s …  1.679 s    10 runs
Benchmark 2: regal-tricks lint bundle
Time (mean ± σ):      1.619 s ±  0.033 s    [User: 11.500 s, System: 0.458 s]
Range (min … max):    1.562 s …  1.666 s    10 runs
Summary
regal-tricks lint bundle ran
1.01 ± 0.03 times faster than regal-main lint bundle
```
=> Various micro-optimizations

pkg/rules/rules.go
Good news is this reduced the total time to parse, as expected. The bad news is that this wasn't the metric I thought it was, and the real killer is `timer_rego_input_parse_ns`, which we can't fix as easily.
Oh well, a small win is still a win.
Fixes #462
=> Concurrent parse in `InputFromPaths`

bundle/regal/rules/style/detached_metadata.rego, bundle/regal/rules/style/detached_metadata_test.rego
Fixes #466
Thanks @hans-d for the pointer!
=> `detached-metadata`: allow detached if document scope

bundle/regal/rules/style/line_length.rego, bundle/regal/rules/style/line_length_test.rego
=> Use 120 characters as max line length if not configured

README.md
And how it relates to Regal. Also add a link to the editor support page.
Fixes #481
=> Add section on `opa check --strict`

README.md
=> docs: minor readme updates

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/boolean_assignment.rego, bundle/regal/rules/idiomatic/boolean_assignment_test.rego, docs/rules/idiomatic/boolean-assignment.md, docs/rules/idiomatic/equals-pattern-matching.md, docs/rules/idiomatic/no-defined-entrypoint.md, docs/rules/idiomatic/non-raw-regex-pattern.md, docs/rules/idiomatic/use-if.md, docs/rules/idiomatic/use-in-operator.md, docs/rules/idiomatic/use-some-for-output-vars.md, docs/rules/style/opa-fmt.md, docs/rules/style/prefer-snake-case.md, docs/rules/style/todo-comment.md, docs/rules/style/unnecessary-some.md, e2e/testdata/violations/most_violations.rego
Prefer boolean expression in rule body over assigning the result in the rule head.
Also did some consistency fixes in the docs "Related Resources" sections.
Fixes #465
=> Rule: `boolean-assignment`

README.md, docs/adopters.md
=> Add adopters file

docs/adopters.md
=> Add Rego Playground as integrator

pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
=> SARIF: Omit region if no row/column provided

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/deprecated_builtin.rego, bundle/regal/rules/bugs/deprecated_builtin_test.rego, docs/rules/bugs/deprecated-builtin.md, e2e/testdata/violations/most_violations.rego
=> Rule: `deprecated-builtin`

build/capabilities.json, go.mod, go.sum
=> OPA v0.60.0

.github/workflows/update-docs.yaml
=> docs: correctly set version when updating

.github/workflows/update-docs.yaml
=> docs: allow updating with workflow dispatch, and only on tags

.github/workflows/update-docs.yaml
=> docs: use pinned addon for docs.styra.com updates

.github/workflows/update-docs.yaml
=> docs: update action no longer needs local write

README.md
=> Use v1 of setup-regal

.github/workflows/build.yaml, cmd/languageserver.go, cmd/lint.go, cmd/new.go, cmd/table.go, cmd/test.go, cmd/version.go, internal/lsp/lint.go, internal/lsp/server.go, internal/lsp/server_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/linter/linter.go
Not sure if these are from a local upgrade or we're not running this as we think we are in CI. Some rules here are definitely new, but not all of them. I guess existing linters could have seen fixes as well. Will look into it.
=> Fix golangci-lint violations

internal/lsp/server.go
And avoid excessive stat-ing. https://benhoyt.com/writings/go-readdir/
=> Use filepath.WalkDir

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/circular_import.rego, bundle/regal/rules/imports/circular_import_test.rego, bundle/regal/rules/style/rule_name_repeats_package.rego, bundle/regal/rules/style/rule_name_repeats_package_test.rego, docs/rules/imports/circular-import.md, docs/rules/style/rule-name-repeats-package.md, e2e/testdata/violations/circular_import.rego, e2e/testdata/violations/most_violations.rego
=> rules: Include rules from xmas promotion

README.md
As reported by @bdumpp
Fixes #561
=> Docs: Make it obvious how to ignore rules and files

.github/workflows/update-docs.yaml
This is not blocking to fix docs, but is needed for next time
=> docs: update path where version is saved to

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/unused_return_value.rego, bundle/regal/rules/bugs/unused_return_value_test.rego, docs/rules/bugs/unassigned-return-value.md, docs/rules/bugs/unused-return-value.md, e2e/testdata/violations/most_violations.rego
=> Rename `unused-return-value` -> `unassigned-return-value`

docs/editor-support.md
=> [docs] Add note about vscode support

internal/lsp/lint.go, internal/lsp/messages.go, internal/lsp/server_test.go
Fixes https://github.com/StyraInc/regal/issues/585
Changes:
- make sure that errors are 1 not 0s in severity codes
- Use code desc for Href to lint docs
TODO:
=> lsp: Make server messages compliant

README.md
=> Add Linting Rego with... Rego! blog

bundle/regal/rules/imports/prefer_package_imports.rego, bundle/regal/rules/imports/prefer_package_imports_test.rego, pkg/linter/linter_test.go
This fixes one issue reported in #605, but not the issue itself, as that'll need more consideration — concerns mostly described in #344.
CC @devin-brenton
=> Don't flag unresolved imports in `prefer-package-imports`

internal/lsp/server.go
=> fix: avoid panic in walkdir traversal

README.md
=> Add quote from Jimmy Ray

bundle/regal/rules/style/use_assignment_operator.rego, bundle/regal/rules/style/use_assignment_operator_test.rego
=> Calculate column index from 1 in `use-assignment-operator`

internal/lsp/hover.go, internal/lsp/server.go
This PR contains three fixes or adjustments to the errors shown and returned in the Regal language server, each commit has its own note.
=> lsp: Error handling fixes

internal/lsp/server.go
=> fix: log but don't send back file read errors in documentSymbol handle

.golangci.yaml, cmd/lint.go, internal/lsp/documentsymbol_test.go, internal/lsp/server.go, internal/lsp/server_test.go, pkg/linter/linter.go
Fixes #679
unrelated: disabled the gocognit linter as it's annoying
=> fix: make sure deleted items aren't added back to the cache

.github/workflows/build.yaml
=> Use macos-13 for amd64 build

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/impossible_not.rego, bundle/regal/rules/bugs/impossible_not_test.rego, bundle/regal/rules/imports/unresolved_import.rego, docs/rules/bugs/impossible-not.md, e2e/testdata/violations/most_violations.rego
See docs in PR (and issue) for further details.
Fixes #603
=> Rule: `impossible-not`

cmd/new.go, internal/embeds/templates/builtin/builtin.md.tpl
=> Add docs as part of `regal new rule` command

cmd/fix.go, docs/fixing.md, docs/rules/imports/use-rego-v1.md, docs/rules/style/function-arg-return.md, docs/rules/style/no-whitespace-comment.md, docs/rules/style/opa-fmt.md, docs/rules/style/use-assignment-operator.md, internal/embeds/templates/builtin/builtin.md.tpl
Fixes https://github.com/StyraInc/regal/issues/665
=> docs: add docs for regal fix function

go.mod, go.sum, internal/lsp/opa/oracle/oracle.go, internal/lsp/server.go
=> lsp: find definition should honor ignored files

README.md
We have added completion recently.
=> docs: update the readme with the lsp features

internal/lsp/clients/clients.go
=> lsp: Identify Zed editor client

docs/rules/style/messy-rule.md
Hey Team! :wave: 
I had the `messy-rule` regal issue in my policy and while reading the docs saw a small typo :sweat_smile: 
Thanks!
=> Fixes typo in messy rule docs

bundle/regal/rules/imports/ignored_import.rego, bundle/regal/rules/imports/ignored_import_test.rego
=> Fix false positive when importing input/data in `ignored-import`

internal/ast/ref.go, internal/ast/ref_test.go, internal/ast/rule.go, internal/ast/rule_test.go, internal/lsp/cache.go, internal/lsp/cache/cache.go, internal/lsp/completions/manager.go, internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/package.go, internal/lsp/completions/providers/packagename.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/providers/regov1.go, internal/lsp/completions/providers/rulerefs.go, internal/lsp/completions/providers/rulerefs_test.go, internal/lsp/completions/providers/utils.go, internal/lsp/completions/refs/refs.go, internal/lsp/completions/refs/refs_test.go, internal/lsp/documentsymbol.go, internal/lsp/documentsymbol_test.go, internal/lsp/lint.go, internal/lsp/server.go, internal/lsp/types/internal.go
Fixes https://github.com/StyraInc/regal/issues/724
https://github.com/StyraInc/regal/assets/1774239/40f630bc-03d5-4f00-acb3-c6530d1943da
=> lsp: Implement first pass at package and rule ref based completions

internal/lsp/completions/providers/rulerefs.go, internal/lsp/completions/providers/rulerefs_test.go, internal/lsp/completions/refs/refs.go, internal/lsp/completions/refs/refs_test.go, internal/lsp/types/internal.go
=> Don't suggest completions for internal rules or functions

internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/package.go, internal/lsp/completions/providers/packagename.go, internal/lsp/completions/providers/packagerefs.go, internal/lsp/completions/providers/regov1.go, internal/lsp/completions/providers/rulerefs.go, internal/lsp/types/completion/completion.go, internal/lsp/types/types.go
=> Use completion item kind table for completions icons

internal/lsp/completions/manager.go, internal/lsp/completions/providers/default.go, internal/lsp/completions/providers/default_test.go, internal/lsp/completions/providers/import.go, internal/lsp/completions/providers/import_test.go, internal/lsp/types/completion/completion.go, internal/lsp/types/types.go
=> Add completions for default and import keywords

internal/lsp/completions/manager.go
Not sure how this got missed in https://github.com/StyraInc/regal/pull/773 but here it is now.
=> lsp: Enable common rule completions

README.md, docs/adopters.md
And some links to package managers including Regal in the adopters file
=> Add asdf instructions

docs/SECURITY.md
=> Add basic security disclosure doc

internal/lsp/cache/cache.go, internal/lsp/completions/manager.go, internal/lsp/completions/providers/commonrule_test.go, internal/lsp/completions/providers/packagerefs_test.go, internal/lsp/completions/providers/rulehead_test.go, internal/lsp/completions/providers/rulerefs_test.go, internal/lsp/completions/providers/used_refs.go, internal/lsp/completions/providers/used_refs_test.go, internal/lsp/completions/refs/defined.go, internal/lsp/completions/refs/defined_test.go, internal/lsp/completions/refs/rego/ref_names.rego, internal/lsp/completions/refs/used.go, internal/lsp/completions/refs/used_test.go, internal/lsp/lint.go, internal/lsp/server.go
This implements a completions provider that makes suggestions based on refs users have already typed into their files.
Fixes https://github.com/StyraInc/regal/issues/774
=> lsp: implement used refs completions

README.md, bundle/regal/ast/ast.rego, bundle/regal/ast/imports.rego, bundle/regal/capabilities.rego, bundle/regal/config/config.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/ambiguous_scope.rego, bundle/regal/rules/idiomatic/ambiguous_scope_test.rego, bundle/regal/rules/idiomatic/custom_has_key_construct.rego, bundle/regal/rules/idiomatic/custom_in_construct.rego, bundle/regal/rules/idiomatic/equals_pattern_matching.rego, bundle/regal/util/util.rego, docs/rules/idiomatic/ambiguous-scope.md, e2e/testdata/violations/most_violations.rego
=> Rule: `ambiguous-scope`

.goreleaser.yaml
```
❯ goreleaser check
• checking                                 path=.goreleaser.yaml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
=> Prepare for goreleaser 2.0.0

internal/lsp/completions/refs/used.go
This was being slow to start and adding around 100ms to all regal command runs, even though this is only needed for the lsp.
This change makes the initialization of the pq var happen at the first call instead.
=> lsp/refs: Just in time init for refs util

cmd/lint.go, e2e/cli_test.go
Fixes https://github.com/StyraInc/regal/issues/482
=> cmd/lint: show JSON errors

internal/lsp/lint.go
=> Drop print statement

bundle/regal/lsp/completion/providers/rulerefs/rulerefs.rego
Limit calls counting chars in grouping
=> Improve performance of rulerefs

README.md
=> Add new blog to README

README.md, docs/adopters.md
=> docs: update adopters and roadmap

README.md, bundle/regal/ast/comments.rego, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/annotation_without_metadata.rego, bundle/regal/rules/bugs/annotation_without_metadata_test.rego, docs/rules/bugs/annotation-without-metadata.md, e2e/testdata/violations/most_violations.rego
=> Rule: `annotation-without-metadata`

go.mod, go.sum, pkg/reporter/reporter_test.go
Replaces https://github.com/StyraInc/regal/pull/908 with a fix
=> Dependabot/go modules/GitHub.com/owenrumney/go sarif/v2 2.3.3

bundle/regal/lsp/completion/providers/snippet/snippet.rego, bundle/regal/lsp/completion/providers/snippet/snippet_test.rego
Fixes https://github.com/StyraInc/regal/issues/913
This makes it more consistent with other providers.
=> Show snippet completions for complete word

docs/adopters.md
I've added a link to the package on nixpkgs.
=> docs: add nixpkgs/regal to the adopters list

cmd/test.go
=> Add `--var-values` flag to `regal test` command

pkg/reporter/reporter.go, pkg/reporter/reporter_test.go
Fixes https://github.com/StyraInc/regal/issues/936
=> reporter: Trim long lines of location text

.github/workflows/update-example-index.yaml
This is needed in addition to the commit message
=> lsp: Update example index PR title

internal/lsp/server.go
=> Fix code lens issue with ref head rules

build/capabilities.json
=> Update capabilities.json to include `strings.count`

build/capabilities.json, bundle/regal/ast/ast.rego, bundle/regal/result.rego, bundle/regal/result_test.rego, bundle/regal/rules/bugs/annotation_without_metadata_test.rego, bundle/regal/rules/idiomatic/use_in_operator.rego, bundle/regal/rules/imports/prefer_package_imports_test.rego, bundle/regal/rules/style/detached_metadata_test.rego, bundle/regal/rules/style/messy_rule_test.rego, bundle/regal/rules/style/todo_comment_test.rego, docs/custom-rules.md, docs/language-server.md, docs/rules/idiomatic/use-contains.md, docs/rules/style/default-over-else.md, docs/rules/testing/print-or-trace-call.md, e2e/testdata/ast_type_failure/custom_type_fail.rego, e2e/testdata/not_rego_v1/not_rego_v1.rego, e2e/testdata/violations/most_violations.rego, internal/ast/rule.go, internal/lsp/lint.go
Perusing the docs found a few typos... checked over the whole code base while I was at it.
=> cosmetic: fix a few typos

build/capabilities.json, bundle/regal/ast/ast.rego, bundle/regal/result.rego, bundle/regal/result_test.rego, bundle/regal/rules/bugs/annotation_without_metadata_test.rego, bundle/regal/rules/idiomatic/use_in_operator.rego, bundle/regal/rules/imports/prefer_package_imports_test.rego, bundle/regal/rules/style/detached_metadata_test.rego, bundle/regal/rules/style/messy_rule_test.rego, bundle/regal/rules/style/todo_comment_test.rego, docs/custom-rules.md, docs/language-server.md, docs/rules/idiomatic/use-contains.md, docs/rules/style/default-over-else.md, docs/rules/testing/print-or-trace-call.md, e2e/testdata/ast_type_failure/custom_type_fail.rego, e2e/testdata/not_rego_v1/not_rego_v1.rego, e2e/testdata/violations/most_violations.rego, internal/ast/rule.go, internal/lsp/lint.go
Looks like I misconfigured my previous PR, it merged from my fork to a branch of this repo rather than `main` in this repo.
So this is the same changes, now going to merge to main.
=> cosmetic: fix a few typos (reprise)

.github/workflows/build.yaml, .github/workflows/update-example-index.yaml
This should honestly have been the case from the start..
=> Pin OPA version in Actions to v0.67.1

README.md, internal/lsp/server_test.go
=> Fix build issue + version in README

.github/workflows/build.yaml, .github/workflows/update-example-index.yaml, README.md, bundle/regal/main/main.rego, go.mod, go.sum, internal/lsp/completions/refs/defined_test.go
Bump dependency and fix the few places where entrypoint rule scope was assumed.
=> OPA v0.68.0

bundle/regal/rules/style/prefer-snake-case/prefer_snake_case.rego, bundle/regal/rules/style/prefer-snake-case/prefer_snake_case_test.rego
=> Remove code to workaround bug fixed in OPA v0.68.0

docs/editor-support.md
=> docs/editors: add helix config

.github/workflows/build.yaml, build/simplecov/simplecov.rego
=> Codecov experiment

internal/lsp/completions/providers/builtins.go, internal/lsp/completions/providers/builtins_test.go
Related to https://github.com/StyraInc/regal/issues/1010
=> completion: Don't show builtins on default rules

internal/lsp/server.go
Related https://github.com/StyraInc/regal/pull/1088
=> lsp: Fix Eval issue caused by missing comments

.github/workflows/build.yaml, README.md
=> Bump OPA to v0.69.0

docs/CONTRIBUTING.md, internal/capabilities/embedded/eopa/v1.25.0.json, internal/capabilities/embedded/eopa/v1.25.1.json, internal/capabilities/embedded/eopa/v1.26.0.json, internal/capabilities/embedded/eopa/v1.27.0.json
=> update eopa caps and CONTRIBUTING.md

.github/workflows/update-caps.yml
~🚧 I'll test it on my fork before we merge it here~
✔️ Works: https://github.com/srenatus/regal/pull/2
=> workflow: add update-caps

.github/workflows/update-example-index.yaml
This workflow is failing due to the file having been moved: https://github.com/StyraInc/regal/actions/runs/11207050280
=> Correct example index rego path

docs/rules/bugs/duplicate-rule.md, docs/rules/style/comprehension-term-assignment.md
Thanks @geirs73 for reporting!
=> docs: Fix typos in config examples

internal/lsp/eval.go, internal/lsp/eval_test.go
When developing Regal rules it's useful to be able to access the server's capabilities and configuration. This change adds these to the rego evaluation context.
=> lsp/eval: Load capabilities and config into eval

internal/lsp/eval.go
Left over from https://github.com/StyraInc/regal/pull/1217
=> lsp/eval: Remove missed print statement

bundle/regal/config/exclusion_test.rego, bundle/regal/lsp/completion/providers/packagename/packagename_test.rego, bundle/regal/main/main_test.rego, bundle/regal/rules/imports/circular-import/circular_import_test.rego
Should have been done in https://github.com/StyraInc/regal/pull/1228
=> Remove leaked-internal-reference comments

docs/adopters.md
Hello! 👋 
Adding VFZ to adopters as we use it in our pipelines for our policies!
Thanks! 🙏
=> Add VodafoneZiggo as adopters

.github/workflows/build.yaml, .github/workflows/update-example-index.yaml
Just reducing the manual work required when updating the OPA version... 🤞
=> workflow: read OPA version from go.mod

.github/workflows/build.yaml
As this is takes too much time to run serially
=> actions: run race detector separately

go.mod, go.sum, pkg/linter/linter_test.go
This must have gotten here by mistake..
=> Remove yaml.v2 dependency

.golangci.yaml
=> ci: add depguard for gopkg.in/yaml.v2

internal/lsp/server_multi_file_test.go
This updates the server_multi_file_test to wait for the aggregate state to be set after the server starts up. This state is required to correctly lint the authz.rego file in the following step. This was sometimes happening too late, causing the test to fail due to the state not being present at the time of linting.
=> lsp/test: Wait for aggregate state to be set

bundle/regal/rules/performance/defer-assignment/defer_assignment.rego, bundle/regal/rules/performance/defer-assignment/defer_assignment_test.rego
=> Fix false positive in defer-assignment and `with`

cmd/fix.go
=> Fix issue where --force wasn't honored in git check

bundle/regal/result/result.rego, bundle/regal/rules/bugs/redundant-existence-check/redundant_existence_check.rego, bundle/regal/rules/bugs/redundant-existence-check/redundant_existence_check_test.rego, docs/rules/bugs/redundant-existence-check.md, pkg/linter/linter.go
=> Have `redundant-existence-check` include function args

bundle/regal/ast/ast.rego, bundle/regal/rules/bugs/top-level-iteration/top_level_iteration.rego, bundle/regal/rules/bugs/top-level-iteration/top_level_iteration_test.rego, bundle/regal/rules/style/comprehension-term-assignment/comprehension_term_assignment.rego
=> Fix false positive in `top-level-assignment`

bundle/regal/rules/style/external-reference/external_reference.rego, bundle/regal/rules/style/external-reference/external_reference_test.rego
=> Fix false positive in external-reference and vars in composite values

.golangci.yaml, .vscode/settings.json
=> dev: Fix golangci-lint reporting issues in ignored files in VS Code

internal/lsp/server.go
=> Evaluate should work even when input missing

docs/rules/idiomatic/directory-package-mismatch.md
Fixes https://github.com/StyraInc/regal/issues/1300
=> docs: add note about roots in directory-package-mismatch rule

pkg/hints/hints.go
Adjusting for https://github.com/open-policy-agent/opa/pull/7164
=> hints: remove tail anchor for multiple-default-rules hint

internal/lsp/server_multi_file_test.go
This has been flaky for too long and so it's being skipped until it can be corrected.
=> tests: Skip server multi file test

README.md
=> Add new blog!

README.md
=> Update badge to 1.0.0

cmd/fix.go, pkg/config/config.go, pkg/config/config_test.go, pkg/fixer/fixer.go
Fixes https://github.com/StyraInc/regal/issues/1341
=> fix: add error based on expected regal dir

internal/lsp/server.go, pkg/fixer/fixer.go, pkg/fixer/fixer_test.go
This functionality is no longer used.
=> fix: Remove mandatory fixes

pkg/reporter/reporter.go
=> Some style fixes

.golangci.yaml, pkg/report/report.go
=> Add optional govet checks

cmd/table.go, internal/util/ast.go, internal/util/set.go, internal/util/set_test.go, pkg/linter/linter.go, pkg/linter/linter_test.go
Fixes https://github.com/StyraInc/regal/issues/1214
=> linter: Show error if rule or category is invalid

go.mod, go.sum, internal/lsp/server.go, internal/util/util.go, internal/web/server.go
Example of a project going from 1 rego file to 100s
=> lsp: Add statsviz for profiling visuals

pkg/fixer/fixer.go
Since we no longer have mandatory fixes, we don't need code to deal with that. If we do later, it'll be in git history :)
=> Remove unused fixer code

pkg/reporter/reporter.go, pkg/reporter/testdata/pretty/reporter-long-text.txt, pkg/reporter/testdata/pretty/reporter.txt
=> Some minor cleanups in reporter code

pkg/linter/linter.go
=> refactor: simplify data bundle creation

internal/lsp/command.go, internal/lsp/server.go
These had been missed in https://github.com/StyraInc/regal/pull/1382
=> lsp: Correctly parse eval and debug params

README.md
=> docs: Make editor support link clearer in README

docs/debug-adapter.md, docs/language-server.md
=> docs: Add debug code lens to LS docs

docs/adopters.md
=> adopters: mention mise+aqua

bundle/regal/rules/performance/non-loop-expression/non_loop_expression.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression_test.rego
Thanks @drewcorlin1 for reporting the issue1
Fixes #1436
=> Fix non-loop-expression false positive

bundle/regal/rules/style/messy-rule/messy_rule.rego, bundle/regal/rules/style/messy-rule/messy_rule_test.rego
=> Ignore tests in messy-rule

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/import-shadows-rule/import_shadows_rule.rego, bundle/regal/rules/bugs/import-shadows-rule/import_shadows_rule_test.rego, docs/rules/bugs/import-shadows-rule.md
=> Rule: import-shadows-rule

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/redundant-loop-count/redundant_loop_count.rego, bundle/regal/rules/bugs/redundant-loop-count/redundant_loop_count_test.rego, docs/rules/bugs/redundant-loop-count.md, e2e/testdata/violations/most_violations.rego
=> Rule: redundant-loop-count

bundle/regal/rules/style/yoda-condition/yoda_condition.rego, bundle/regal/rules/style/yoda-condition/yoda_condition_test.rego
After review https://github.com/StyraInc/regal/pull/1452#discussion_r2010107989
=> Add >, >=, <, <= to yoda-condition rule

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/bugs/time-now-ns-twice/time_now_ns_twice.rego, bundle/regal/rules/bugs/time-now-ns-twice/time_now_ns_twice_test.rego, docs/rules/bugs/time-now-ns-twice.md, e2e/testdata/violations/most_violations.rego
=> Rule: time-now-ns-twice

bundle/regal/config/config_test.rego, bundle/regal/config/exclusion_test.rego, bundle/regal/lsp/completion/location/location_test.rego, bundle/regal/rules/bugs/argument-always-wildcard/argument_always_wildcard_test.rego, bundle/regal/rules/bugs/if-object-literal/if_object_literal_test.rego, bundle/regal/util/util_test.rego
This was mostly done to try things out last night. Not sure yet if there's one particular model / style for how we should do this, but some alternative approaches have been tested here. Commiting this in the meantime for us to have some real examples to keep that discussion around.
As a bonus, the number of tests reported are now 701, compared to 685 without parameterization :)
=> Parameterize some tests

docs/rules/bugs/rule-named-if.md
=> docs: rule-named-if

bundle/regal/ast/ast.rego, bundle/regal/ast/ast_test.rego, bundle/regal/ast/keywords.rego, bundle/regal/config/config_test.rego, bundle/regal/lsp/codelens/codelens.rego
Fixes about half the currently reported missing coverage. I could go on, but the rest of the lines were even less interesting, so I'll leave them be for now. Nice to get rid of some unused things though!
=> Increase coverage

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/imports/confusing-alias/confusing_alias.rego, bundle/regal/rules/imports/confusing-alias/confusing_alias_test.rego, docs/rules/imports/confusing-alias.md, e2e/testdata/violations/most_violations.rego, internal/embeds/templates/builtin/builtin_test.rego.tpl
=> Rule: confusing-alias

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/in-wildcard-key/in_wildcard_key.rego, bundle/regal/rules/performance/non-loop-expression/non_loop_expression.rego, bundle/regal/rules/style/mixed-iteration/mixed_iteration.rego, bundle/regal/rules/style/mixed-iteration/mixed_iteration_test.rego, docs/rules/style/mixed-iteration.md, e2e/testdata/violations/most_violations.rego
=> Rule: mixed-iteration

e2e/cli_test.go, pkg/rules/rules.go
=> fix: ensure policy from stdin is enumerated correctly

pkg/builtins/builtins.go
=> builtins.RegalIsFormatted: recover from formatter panics

README.md
=> Add link to KubeCon London talk

internal/lsp/server.go
Related https://github.com/StyraInc/regal/issues/1501
=> lsp: Handle and log case of no Href for diagnostic

README.md
=> Add Renovating Rego blog

.github/workflows/build.yaml
=> Bump golangci-lint

README.md, bundle/regal/config/provided/data.yaml, bundle/regal/rules/idiomatic/single-item-in/single_item_in.rego, bundle/regal/rules/idiomatic/single-item-in/single_item_in_test.rego, docs/rules/idiomatic/single-item-in.md
=> Rule: single-item-in

README.md
=> docs: Update roadmap for Regal 1.0

.goreleaser.yaml
=> Fix deprecated notices in .goreleaser.yaml

bundle/regal/rules/bugs/sprintf-arguments-mismatch/sprintf_arguments_mismatch.rego, bundle/regal/rules/bugs/sprintf-arguments-mismatch/sprintf_arguments_mismatch_test.rego
=> fix: consider padding pattern in sprintf-arguments-mismatch

go.mod, go.sum, pkg/reporter/reporter.go, pkg/reporter/reporter_test.go, pkg/reporter/testdata/pretty/reporter-long-text.txt, pkg/reporter/testdata/pretty/reporter.txt
These were not possible to include in an OPA build and since this dependency is soon be removed, we should revert this change.
=> deps: Revert 47c70f0 tablewriter changes

README.md, docs/readme-sections/opa1.md
Website has been manually fixed
=> docs: Update typo in link

bundle/regal/main/main_test.rego, e2e/testbuild/go.mod, e2e/testbuild/go.sum, go.mod, go.sum
Most of the fix is in Roast, just verified here.
Fixes #1592
=> Fix issue with handling big numbers

.github/workflows/build.yaml, go.mod, go.sum, main.go
This is mostly an internal update, removing roasts own interning in favor of using the one in OPA, which is now possible.
=> Bump Roast -> v0.12.0

docs/language-server.md
x-ref: https://github.com/StyraInc/regal/issues/1596#issuecomment-2983656578
=> docs: Update Evaluation Code Lens docs

docs/custom-rules.md, internal/lsp/lint.go, internal/lsp/lint_test.go, internal/lsp/server.go, internal/lsp/server_custom_rules_test.go, internal/lsp/server_test.go
Fixes https://github.com/StyraInc/regal/issues/1571
=> lsp: Add support for custom rules

bundle/regal/lsp/signature-help/main.rego, bundle/regal/lsp/signature-help/main_test.rego, e2e/cli_test.go, internal/lsp/rego/rego.go, internal/lsp/server.go, internal/lsp/server_signature_help_test.go, internal/lsp/store.go, internal/lsp/store_test.go, internal/lsp/types/types.go
=> lsp: Add signature help

internal/lsp/server.go, internal/lsp/server_signature_help_test.go
E.g. https://github.com/StyraInc/regal/actions/runs/16962142183/job/48077281888?pr=1653
=> lsp: Fix server signature race in test

bundle/regal/lsp/documenthighlight/documenthighlight_test.rego
=> lsp/documenthighlight: Add tests

internal/web/server.go
=> Enable pprof endpoint only with env var set

README.md, docs/adopters.md, docs/architecture.md, docs/readme-sections/next-steps.md, docs/rules/custom/one-liner-rule.md, docs/rules/idiomatic/non-raw-regex-pattern.md
https://github.com/open-policy-agent/opa/issues/7888
=> docs: Address some broken links from OPA report
